### ISSUE TITLE
[Libretro] Game-specific save file for Sega CD

### ISSUE THREAD

**Issue by ape123** [ekeeke/Genesis-Plus-GX#100]
The Sega CD's internal memory cannot hold a lot of saves. Just increasing the capacity would probably also introduce compatibility issues. However, having one brm file per game would negate any need for higher capacity while there would still be enough space for saving in every game.

Example: You save in a game that has the file name "Sonic CD.cue". The game would save to the file "Sonic CD.brm".

**Comment by ekeeke** [comment]
This would be handled by the frontend, not the emulation core. For which frontend are you requesting this ?

**Comment by ape123** [comment]
Oh, I thought it was usually the other way around (core handles it), my bad. Well, I use RetroArch a lot so that would be best, but really, I would move over to whichever frontend would get this feature first.

**Comment by ekeeke** [comment]
No, it's the frontend which decides what to do with internal backup ram, when to load / save it, how to name files, etc... 

In case of retroarch, it's the libretro core interface (libretro.c) which deals with .brm files ctuallt because libretro API does not really provide a way with system generic save file. I guess it should be possible to handle internal backup ram like typical game sram and the frontend (retroarch) would simply read/write .srm files for each Sega CD games like it does for Genesis games. 

However, everybody would need to rename / duplicate their .brm file if they have Sega CD games with internal saves and this will likely cause many "bug" reports or incomprehension, so I'm not sure if that's a so good idea. How people did with real Sega CD? Are so much saves at the same time really unavoidable? If you really need space, you can move saves to emulated backup cartridge RAM (which is 512KB i.e 64x larger than internal backup RAM), this can be done through the bios interface, by pressing A Button when any CD game is booting.

**Comment by ape123** [comment]
I see, I've never heard anyone refer to libretro as a frontend, but that makes sense.

It's possible, though I have never seen any bug reports like that for any other emulator projects that use game-specific save files.

Yes, the backup cartridge certainly improves things. The problem with that is that of the games I've tried, few games can save directly to the backup cartridge. This means quite a bit of copying back and forth (I only saved in like 2 games and internal memory was already full). Now, of course if the player is desperate enough to play a game, he will consider anything, including deleting saves. Being able to save in all games directly is just much more convenient.

Anyway, this is just my reasoning. If it would be too much hassle to be worth it, you can reject it, no problem.

**Comment by ekeeke** [comment]
https://github.com/ekeeke/Genesis-Plus-GX/commit/3ee094c0eaa147707f0e8372f2ba0f41db06be4e adds a core option in libretro port to select "per bios" (default) or "per game" BRM files for Sega CD games.
