### ISSUE TITLE
Copyright notices

### ISSUE THREAD

**Issue by twinaphex** [ekeeke/Genesis-Plus-GX#111]
Can you pull my latest changes made from the libretro repo?

At no point in time do I ever want to put Nostalgames or any other party close like it in a position where they can attempt to pull something similar to this again. Non-commercial means non-commercial, and I at least want my copyright now on all libretro files. I want there NEVER to be any possibility of somebody being able to 'SELL RIGHTS' for a project that has in its license header 'NON-COMMERCIAL'. Non-commercial has to mean non-commercial or else the license is not worth the txt file it's printed in. This is only fair and right.

I would feel personally offended and wronged if any license deal did went through, and that would be the end of our relationship as far as I'm concerned. I have to be brutally honest about this. I cannot stand 'exceptions' being made for key ideological tenets.

**Comment by ekeeke** [comment]
You can put whatever license you want on libretro files as long it is compatible with Genesis Plus GX license. However the few changes Toadking made are definitively not substantial enough to warrant a copyright change. I won't accept these changes anyway as they are not portable as discussed in that other thread and I would prefer finding a better solution to the alignment issue. Similarly, putting your copyright on osd.h which was barely modified is kinda ridiculous imo, if you want to prevent commercial licensing of Genesis Plus GX core within a retroarch ripoff, licensing libretro.c was enough (there is a mistake in your changed header by the way, it says config.c instead of libretro.c).

The reason we switched to non-commercial license was to oppose ourselves against people using our code and our hard work to promote and sell their own products without us getting anything in return, it has nothing to do with any ideology. We have every right to relicense our own code the way we want, to whoever we want. Sorry but I have enough of people just trying to profit of my work for their own project.

**Comment by twinaphex** [comment]
> The reason we switched to non-commercial license was to oppose ourselves against people using our code and our hard work to promote and sell their own products without us getting anything in return or without asking permission first, it has nothing to do with any ideology. 

I am ALL FOR THIS, HOWEVER, my issue becomes when basically, if the 'offer' or 'prize' is right, then you'll bite. Is that what is going on here? If so, then yeah, I can no longer follow you there. If it is NOT, then great, we are of the same opinion and I will continue having your back.

Is that the reason why Charles McDonald at a certain point told me to no longer go on a blitzkrieg with regards to all sorts of e-mails that were exchanged inbetween him and Hyperkin? You guys cut a deal?

> That includes free projects that only see us as a useful ressource or people trying to impose me how I should manage my own projects.

Umm, and at which point did you ever get the suspicion that this was what was going on with regards to you and me?

I have had your back since day one here dude. I cut off all ties with halsafar and got him to drop his payware version of Genesis Plus GX. You know I have had your back, so I dunno what this bullshit is about honestly.

**Comment by Kivutar** [comment]
Hi @ekeeke, I'm doing Lakka and your software is an important part of my project. I can understand that you don't feel happy about it. I can try to give something back by adding a link to your donation page, if you have one, on our website. And encourage my users to donate money or hardware directly to emu devs. For now that's the best I can do, tell me if you think it's a good idea. Or if you have another idea.

**Comment by twinaphex** [comment]
And yeah, we would ALWAYS be in support of this. We WANT to give back to the developers, I can understand you feeling slighted, I can understand you feeling frustrated.

What I don't think is the right response, though, is to go against your own noncommercial license if the 'prize is right' and then to basically go for it. That would make a mockery of your own license and then nobody has to respect it anymore.

There are better ways of getting funds and from more sincere and trustworthy guys than a couple of guys that just pulled some money together through a kickstarter under flimsy and shady pretenses (and they no longer have this money now anyway). We are TOTALLY WILLING to help and to prevent emulator authors from feeling even further being ripped off.

**Comment by ekeeke** [comment]
>Is that the reason why Charles McDonald at a certain point told me to no longer go on a blitzkrieg with regards to all sorts of e-mails that were exchanged inbetween him and Hyperkin? You guys cut a deal?

There is no deal that I know of and the discussions with them weren't really about getting one, but anyway, even if it was, that would be none of your business. That's probably what Charles meant and I agree with him.

>I want to simply get a clear-cut answer here, I don't like all these shenanigans and this wishy-washy stuff going on.

And I don't like your demanding tone and you acting as if we were accountable to you. We aren't, Genesis Plus GX is not part of Retroarch and there isn't any libretro copyrighted files involved as far as I know.

>Umm, and at which point did you ever get the suspicion that this was what was going on with regards to you and me?

No suspicion. The moment you come here with an agressive tone, telling me what I should do or not do with my own work and trying to claim part of ownership on the whole project through unsignificant core files modifications, yes, I think I have every rights to feel offended and react consequently. This also tells me you don't really have much consideration for our rights on our work or the value ot has for us and are more interested in using our license as a way to indirectly protect your own project against commercial use or defend some ideology that I don't necessarely have to share, which is convenient but kinda selfish as well in some way.

>What I don't think is the right response, though, is to go against your own noncommercial license if the 'prize is right' and then to basically go for it. That would make a mockery of your own license and then nobody has to respect it anymore. And the people who would offer you money to go against your own license to begin with are not sincere brokers, they are fly-by-night entrepreneurs. There are better ways of getting funds and from more sincere and trustworthy guys than a couple of guys that just pulled some money together through a kickstarter under flimsy and shady pretenses (and they no longer have this money now anyway). We are TOTALLY WILLING to help and to prevent emulator authors from feeling even further being ripped off and to set up a cohesive and sustainable way for emudevs to keep doing what they love without all this nonsense going on. But trying to get basically scraps from the table of a few college kids at some business school? Nah, you're only getting further ripped off then and taking advantage of.

And again, that would be us to decide what is good to us or not, not you, as it concerns only our work, not yours.

As I said, I have more than enough of people telling me how I should license my code, first people telling me that I should abandon non-commercial because it's not "free" to them or now people dictating me that we can not deal proprietary relicensing with our own work. Equally, I have had enough frustration seeing people having no respect for licenses (knowing obviously we don't really have financial means to backup what remain theoretical claims in a txt file) and making a successful business of our work when it seems Charles and I are the only ones who never got anything in return (including code contribution). So when someone is contacting us to make a proper licensing deal, I think this is fair compensation for the amount of work we put in this project without ever asking something in return and for that amount of frustration and dismotivation we already had. Honestly, I don't even need that money, I already have a quite decent job. I also don't think it will change anything regarding people not willing to respect licenses in the first place or those wanting to make a business of open source emulators but at least, it tells others that proper licensing with emulator authors and respect of the value of their work is possible.

@Kivutar: This was not directed at Retroarch or your project, and I am not demanding or needing anything. I am just asking to mind your own business and not assume that just because you are using our emulator in your projects, you have any right to dictate us how we have to deal with licensing for our code or how we should be defending our license. If you want to prevent commercial use of your projects then switch from GPL to a non-commercial license and go bother other core devs to do the same.

**Comment by Kivutar** [comment]
@ekeeke Well I would if I could. But I don't know if switching to a new license is legal.

Anyway, I found your donation link and will list it on our page.

**Comment by twinaphex** [comment]
@ekeeke Just wondering, when talking about these 'supposed license deals', are you also cutting the authors of Musashi 68K and the Z80 interpreter creator a cheque? Because it honestly is not just up to you in that case to be cutting license deals, your project in a great deal is dependent on code not having been written by either you or Charles to do most of its work.

Don't take this as combative, just pointing out that honestly, I can play this game too and claim that NO, it is NOT entirely 'up to you', you simply 'used' code yourself too which you did not yourself write yourself.

**Comment by twinaphex** [comment]
And BTW, I only made this above post BTW because I felt insulted by some of the stuff you had to say in return. If it hadn't been for that, I wouldn't have even mentioned all the stuff above. However, all the stuff I wrote above is basically all true, so meh.

**Comment by twinaphex** [comment]
Let's go even deeper than that in fact -

'Blip Buffer code ' - By Shay Green and licensed as GPL - GPL is not compatible with non-commercial

YM2413 code - Jarek Burczynski - no real license attached

SN76489 code - 'by Maxim in 2001 and 2002' - no real license attached

So in addition to the guys who wrote the interpreters, that's already a hell of a lot of 'copyright authors' we are talking about. So I think it's safe to conclude, any kind of 'licensing deal' is ultimately null and void since 1) there is mixing of GPL and noncommercial software code happening in here, 2) some of these authors can't even be contacted anymore, and 3) there are obviously multiple copyright holders here beyond just you and Charles MacDonald, and you can't just take out that code either without the emulator being rendered useless.

**Comment by ekeeke** [comment]
Are you done?  I already explained why we switched to non-commercial (this was a common decision btw) so I don't feel like rehashing it again with you (nice job though throwing some dev name out of nowhere and reinventing history with googlecode, very classy).

Now, regarding your "concerns" about Genesis Plus GX code, I have always made it clear to anyone contacting us for commercial licensing that I can only relicense my own code and that they would need to get authorization from every other copyright owners if their license does not permit commercial use.

MAME code license however switched to GPL recently (with some files being BSD licensed as well) so it wasn't really hard for them to get that authorization since those files are now dual licensed by their respective authors. That include 68000, Z80, SVP and YM cores, which means the only code still covered by a proprietary license in Genesis Plus GX is Charles' original code and mine. Blip Buffer and NTSC filters are under LGPL (not GPL), which is afaik compatible with proprietary licensing, libtremor is under BSD, while SN76489 and EQ code are public domain and not covered by any license.

Anyway, as I said before, there have been no deal so far, only discussions and those were about licensing of OUR code only, so once again, I will ask you to mind your own business.

**Comment by mednafen** [comment]
> I know specifically of Ryphecha who certainly doesn't hold it to be credible how you just relicensed from GPLv2 to this 'non-commercial license' like this, and I doubt that is the only one.

What?  If you're going to speak for someone to bolster your case, at least ensure you're not completely misrepresenting their position.

**Comment by twinaphex** [comment]
@mednafen What did you say again about the credibility of a license switch? Spare me all the tsundure nonsense for a minute now and just tell me the exact same thing you told me regarding ekeeke and Genesis Plus GX. 

Or is your memory really becoming that 'hazy'?

**Comment by twinaphex** [comment]
@ekeeke Dude, you do whatever  you want to do from this point on. If you think your 'future' consists of begging for pathetic handouts from some college kids at shady bizz schools when pushing 30, feel perfectly free to do that kind of bullshit. But don't ever talk some bullshit again about 'being wronged' when we had to find out the hard way that you were talking about 'licensing deals' unbeknownst to us. I have had to laugh at the patheticness of you even talking about 'business' within this concept, you were being played by a bunch of college kids who took your 'e-mail correspondences' as 'oh they're willing to go for this, gotta keep them on the hook for a while longer'. You were being played dude, and it seems you were too stupid to even figure that out.

Anyway, my goodwill with you is gone now. BTW, here is some more of Charles McDonald's 'Greatest Hits' during the Hyperkin situation. I sure am good 'only' when there is 'propaganda' and a' call to action' to be made huh, otherwise I need to 'mind my own business' eh? 

Let's drop that in here now shall we:

"Hi Squarepusher,

We've chatted on IRC a few times but I didn't have your e-mail address, so I'm trying this one.

I've been in contact with people from Retron/Hyperkin about Genesis Plus license violations, and have currently managed to do the following:

- Got Lawrence Lee, a project manager, to claim they'll remove Genesis Plus GX code from the project in their next software update.
- Presumably upset Steven Kwon Mar, the head of Hyperkin, because he discussed my private letter to him with Wayne Beckett, the lead software developer.
- Got Beckett to go from combative to extremely receptive after Steven presumably threatened him. I assume he said something along the lines of "This is your mess, you fix it".

Now if it helps, I'd be happy to share the e-mails and e-mail addresses in case you want to put any pressure on them. In fact I'd really like the other emulator authors who have been affected to do the same. I think they can see they are potentially in hot water and are looking for ways out, or at least Wayne is trying to save himself.

So if you have some time for this, please let me know what you think. And if you have contact information for the other emulator authors affected by Hyperkin I'd definitely be interested in that. So far I've only talked with Eke-Eke.

I've also debated putting these e-mails online, though I'm still not sure about proceeding with that. At this point I'd like to do whatever I can do to make sure people understand how scummy Hyperkin/Retron are.

Regards,

Charles"

**Comment by twinaphex** [comment]
Instead of wasting a long rant here, let's just say that you couldn't have disappointed me more with this 'new move' and that I have reconsidered showing a guy unending loyalty that doesn't appear to give a damn about me, and thinks he should be in a position of being able to make 'backhand' 'licensing deals' instead of having my back in being able to stop and prevent any possible 'kickstarter' retro gaming console from emerging again by some shady kids at shady business schools.

Thanks for your total lack of support. If you had been sincere, you would have put in the license headers 'under no circumstance will commercial rights be appropriated', like Snes9x did. You want to keep your 'options open' and you delusionally believe some people might give you a 'right offer' at some point. I find it to be pathetic that you'd rather side with shady kids at shady French schools rather than me, but that's the kind of lack of loyalty you see by most of these IT people everyday.

**Comment by twinaphex** [comment]
You two can do whatever you want, I'm not even going to bother having any long-winded rants about it since both of you don't care and are just selfish in the end. Sorry for caring I guess, and sorry for thinking that we could logically talk things over.

**Comment by twinaphex** [comment]
> Are you done?

I will tell you when we are done, and when I will feel satisfied with your 'responses'.

> So when someone is contacting us to make a proper licensing deal, I think this is fair compensation for the amount of work we put in this project without ever asking something in return and for that amount of frustration and dismotivation we already had. Honestly, I don't even need that money, I already have a quite decent job.

You were getting no money to begin with, they were two college kids (18/19 year olds) who have been going around sending tons of people the same e-mails, and as soon as you respond with anything less than 'HELL NO', they assume 'permission granted' and they go ahead with it, collecting $30K which they then decide to do whatever they want with it. That's the mistake you made to begin with, that they are sincere parties. At no point was there any intent to give you any money.

And this is the problem too where without a contract, ultimately, some business school kids can afford to play games with you, since they already have you by way of the greed bait. It's sad but you played into their game effortlessly, and it took us for you to look at the larger picture and how they had been working around the clock to pull the same con on pretty much all parties involved.

And 'greed' brought you there, not considering the larger picture and that the same 'baiting' tactics they were employing on you, they were employing on everybody. Next time, find some sincere 'business parties' other than college kids if you still insist on the (largely insignificant and pointless) 'license hustle', you embarrassed yourself by even engaging them in a conversation.

You let yourself get played around with as a grown man, possibly pushing 30, by a bunch of trifling college kids, not even graduated yet, with rather sharp MBA teeths. Not a good luck on ya, and honestly, you aren't getting your rep back from me after your responses to me where you are honestly counting your chickens before they hatch.

> and making a successful business of our work when it seems Charles and I are the only ones who never benefited out of it (including code contribution)

Oh boohooh, things were not fair to you. That is in no way a 'selfish' thought at all, something you deride me for previously (that I am supposedly denying you 'riches' or whatever).  So this is all about you and your chump change money.  At least more and more the real sentiments are coming to the surface.

You can do honestly what you want from this point on. You have been quite rude to me without reason in previous posts, go do what you want, but I won't be involved in your shenanigans. I hope the trifling few coins you will ever make out of this are worth the lost friendship (by a guy who unlike you, has had your back countless times, which you take rather for granted).

**Comment by ekeeke** [comment]
The thing is, I don't really care if you are not "satisfied" by my answers or got your feelings hurt by my reaction to you initially attempting to claim ownership on Genesis Plus GX code and then dictating me how I should behave regarding my personal work (or life), so you can keep going on with your monologues as if it was some blog of yours and keep disregarding that your own aggressiveness is part of the issue here, it won't change anything and actually, the more I read your rants filled with anger and people judging, the less I want to have a "relationship" with someone like you.

If by "having your back", you mean forcing your friends to always think like you and act as you want, then good luck with that. As already said, I have no problem supporting your rights on your code and I had no issue contacting kisskissbankbank to clarify the situation regarding nostalgames (which from what I was told had at least some influence on them closing the retropac crow-funding campaign) but I won't accept anyone trying to impose me his views when it comes to my own personal work.

**Comment by ekeeke** [comment]
Deleted comments

**Comment by ekeeke** [comment]
More deleted comments

**Comment by ekeeke** [comment]
One again

**Comment by ekeeke** [comment]
And a last one... not sure why they got deleted

**Comment by twinaphex** [comment]
You can keep posting deleted comments, I have nothing to hide and its all 100% true anyway. All you are doing posting those deleted comments is showing how both you guys (Charles and you) are not entirely sincere when you say I should keep my nose out of 'your business', since you guys have repeatedly dragged me in the past in your little feuds with certain companies but only WHEN it was convenient to you.

I dont care BTW that you dont care either, you not caring and wanting to hear me out is why i am perfectly OK with judging you until you portray a different attitude. I think you are doing a lot of soul searching here and basically jumping the shark and you want everyone to just go out of your way and let you do this stuff without saying something. Well, i am not that kind of dude, sorry.

Anyway, I am sick of this bullshit now. I said what I had wanted to say. I cant take words back that I firmly stand behind or else I would be lying to myself.

**Comment by p1pkin** [comment]
you're pissing off more and more emulator developers, so typical ))

**Comment by twinaphex** [comment]
@p1pkin Oh, there we have another serial troll coming out of the woodwork unprovoked. Ask me when I ever asked for your opinion, and STFU. Keep to your little 'closed source circle' with your closed source Dreamcast emulator that needs a supercomputer in order to run properly.

**Comment by p1pkin** [comment]
haha, silly try )) does anyone takes you seriously ?

**Comment by twinaphex** [comment]
@p1pkin Does anybody take seriously a loser from Ukraine who keeps his Dreamcast emulator source closed source? Answer me that.

A loser at that who expected the rest of Europe to confront Russia in World War 3 for his corrupt country at that. Nah thanks, you and the dirty oligarchs in your country created that mess, if you want a better quality of life, leave that place. Hell, maybe then you wouldn't have to keep your Dreamcast emulator sources closed source either and actually contribute to society at large instead of being a stain on it.

**Comment by ekeeke** [comment]
OK, I think this thread has run its course and is now turning into personal attacks . Feel free to continue this fascinating adult "discussion" elsewhere.
