### ISSUE TITLE
Genesis MultiTap - Wayne Gretzky Hockey Doesn't Work

### ISSUE THREAD

**Issue by newoski** [ekeeke/Genesis-Plus-GX#116]
I've got most other games tested and working at this point, but Wayne Gretzky and the NHLPA All-Stars does not seem to work with Multitap, despite being a multitap game. 

I've tried all P1 / P2 combinations of the available multitap controllers (4way, teamplayer) (3button, 6 button) and nothing works. 

The closest to working is:
P1: MD Joypad 6 Button
P2: MD Joypad 6 Button + TeamPlayer 6 Button

That will at least bring up the MultiTap message when the game is launched, however, the controls freak out

**Comment by ekeeke** [comment]
Works fine with TeamPlayer / 6 Button in Port 1 and either nothing or 3 Button/6 Button in Port 2.

Tested on standalone versions but there is no reason it should not work the same way in retroarch.

**Comment by newoski** [comment]
Just tested on RetroArch using the setting you described with no luck...

**Comment by ekeeke** [comment]
Just tested and it works fine in Retroach here (windows version) so I am not sure what the issue is on your end but the game detects teamplayer just fine and let you assign 4 player to each team as expected so there is no core issue here.

I noticed libretro repository was not exactly in sync with my own repository, in particular [this](https://github.com/ekeeke/Genesis-Plus-GX/commit/8b909e40350ffe7a85176912c60f869221f57510) commit . It should not affect multitap support but you never know.


![ra-1](https://cloud.githubusercontent.com/assets/717091/20864814/56533eb8-b9fe-11e6-9967-a64cf0013cb8.jpg)
![ra-2](https://cloud.githubusercontent.com/assets/717091/20864815/56534886-b9fe-11e6-8f5b-b3df44abf7a9.jpg)
![ra-3](https://cloud.githubusercontent.com/assets/717091/20864818/5659c7c4-b9fe-11e6-8b1a-1c66b36fabff.jpg)
![ra-4](https://cloud.githubusercontent.com/assets/717091/20864816/56572cd0-b9fe-11e6-84a3-dbc8e1dad377.jpg)
![ra-5](https://cloud.githubusercontent.com/assets/717091/20864817/5657c122-b9fe-11e6-8312-83f7946d0df7.jpg)

**Comment by newoski** [comment]
Hmmm. I see you're running 1.0.02. That's interesting to see that MultiTap is clearly recognized at the Title Screen. I have yet to see that message on 1.3.X (latest beta). I assume you're simply loading an Exhibition game? When I load the game, with the settings you highlight above in your screenshot, I end up at the same bottom image, but there are only 2 players available. Moreover, only the first player is controllable.

Outside of this game, I have 55 games working correctly with MultiTap. Below are the other games not working:

Wayne Gretzky and the NHLPA All-Stars
ATP Tour
College Slam
Dino Dini's Soccer
Ichidant-R
International Rugby
J.League Pro Striker 2,
J.League Pro Striker Perfect Edition
Pro Striker Final Stage
Micro Machines 2
Mortal Kombat 3
NBA Action 94
NCAA Final Four Basketball
Olympic Gold
Pepen ga Pengo
Ultimate Soccer
Wimbledon
World Cup USA 94
Worms

**Comment by ekeeke** [comment]
Multitap is correctly detected for these games (some of them do not have multitap support though, like International Rugby or Micro machines 2 where you need the non-jcart version which is afaik undumped)
so the issue is on your end I'm afraid

Teamplayer emulation is fine in the emulator and since support for this adapter was likely implemented in games using Sega official library, if it  works with one game there are major chances it works for all of them. Some games expect different configuration but it seems normal gamepad in port 1 and teamplayer in port 2 was the most  supported scheme. Some of them require special action to activate all controllers (in College Slam for example you need to press A on each controller in the team selection screen and in MK3, I think it is a secret multiplayer mode that needs to be activated somehow)

![collegeslam](https://cloud.githubusercontent.com/assets/717091/20866414/68e97856-ba2d-11e6-8ac9-b619a3d4aed3.jpg)

![retroarch-1204-085815](https://cloud.githubusercontent.com/assets/717091/20866421/76eba8d4-ba2d-11e6-92c7-2d12c0410e49.png)
![retroarch-1204-092710](https://cloud.githubusercontent.com/assets/717091/20866424/76ec6e40-ba2d-11e6-97c0-267fc0d4d23f.png)
![retroarch-1204-094057](https://cloud.githubusercontent.com/assets/717091/20866426/76ece56e-ba2d-11e6-80a5-ed303a109363.png)
![retroarch-1204-125855](https://cloud.githubusercontent.com/assets/717091/20866423/76ec6684-ba2d-11e6-82e8-60ce7760db7d.png)
![retroarch-1204-130503](https://cloud.githubusercontent.com/assets/717091/20866422/76ec53c4-ba2d-11e6-9101-8ef3a54fe519.png)
![retroarch-1204-134302](https://cloud.githubusercontent.com/assets/717091/20866425/76ec72e6-ba2d-11e6-8841-2237548d51bc.png)
![retroarch-1204-134719](https://cloud.githubusercontent.com/assets/717091/20866427/76fd589a-ba2d-11e6-9f6c-74d7cf0912c8.png)

**Comment by newoski** [comment]
Really appreciate the thorough responses. Unfortunately, that core you linked me to caused RetroArch to crash when I try to load it, however, based on your feedback, I have gotten Wayne Gretzky working as well as College Slam. Working on the rest now.

**Comment by newoski** [comment]
So now that I know about the need for Joypad Auto in some instances, I've gotten most games working. 

Here are the last few that I can't seem to figure out:

International Rugby 
Olympic God
Pepenga Pengo
Ultimate Soccer
World Cup USA 94 
Worms

If you could post the settings you're using to get these working, I'd really really appreciate it. From there, I'll put together a zip file with my per game overrides for all MultiTap games. 

Thanks again!

**Comment by newoski** [comment]
(To access Mortal Kombat 3 multiplayer, press A+C and then Start)

**Comment by ekeeke** [comment]
As already said, following games do NOT support multitap adapter despite often wrongly  listed that way (confirmed by the fact there is no code executed trying to detect teamplayer or 4-wayplay):
- International Rugby only supports up to 2 Player
http://segaretro.org/File:InternationalRugby_MD_EU_Box.jpg
- Olympic Gold and Worms support up to 4 players but not simultaneously,  there is no mention of multitap support in the manuals either 
http://segaretro.org/File:Olympic_Gold_MD_US_Manual.pdf
http://segaretro.org/File:Worms_MD_EU_Manual.pdf

-Pepenga Pengo
Requires a gamepad in port and teamplayer in port 2
Multiplayer only in battle mode
![pengo](https://cloud.githubusercontent.com/assets/717091/20867293/1c5c5012-ba41-11e6-8ebc-4d48448afacb.jpg)

-Ultimate Soccer
Support teamplayers on both ports for up to 8 players simultaneously 
All players in the same team tough and you have to select which one controls which team member in the formation setup (by default player 1 controls the whole team)
![ultimatesoccer](https://cloud.githubusercontent.com/assets/717091/20867312/ef1a8960-ba41-11e6-8351-426920701a93.jpg)

-World Cup USA 94
Supports up to 4 players simultaneously using either 4-WayPlay (connected to both ports) or teamplayer (port 1 or port 2). You can even have 2 teamplayer connected and choose players 5-8 to compose teams but still are limited to mas 4 players simultaneously.

![worldcup94](https://cloud.githubusercontent.com/assets/717091/20867897/ea2806dc-ba4e-11e6-917b-ab978f210d90.jpg)

**Comment by newoski** [comment]
Thanks so much! I'll test shortly

**Comment by newoski** [comment]
Hi ekeeke, 

My sincerest thanks for your help getting this setup. Thanks to your help, I've got all supported MultiTap games for Sega Gensis working via the Genesis Plus GX core. 

As a shortcut for anyone else that wants to setup all games, here is a link to my Per Game Config Overrides. Just enable Per Game Config Overrides and merge the attached folder structure with your own RetroArch folder. It contains no changes other than the MultiTap enabled settings. 

https://www.dropbox.com/s/kjjzo83dfb7laee/Sega%20Genesis%20MultiTap%20Per%20Game%20Config%20Overrides.zip?dl=0

Cheers and thanks again!

**Comment by newoski** [comment]
Is MultiTap supported for Sega CD and if so, could you post the correct mappings for:

Bill Walsh
Dungeon Explorer
ESPN National Hockey Night
FIFA International Soccer
NBA Jam
NHL 94

Thanks again ekeeke!

**Comment by ekeeke** [comment]
I don't have time for this I'm afraid, I'm sure it can easily figured by finding manuals online or trying different combinations.

EA games only support 4-wayplay usually, make sure to put it in both ports because that's the way it worked, there isn't any other possible configuration with that one.

**Comment by newoski** [comment]
OK, no problem. Based on your previous responses, it sounded like you might have access to the info easily. So far, no combos work. Thanks again for the Genesis help!

**Comment by newoski** [comment]
NBA Jam works with TeamPlayer (6 Button) for both P1 & P2. Haven't gotten any others working yet.

**Comment by ekeeke** [comment]
I don't have access to any special infos, I've just read game manuals and tested configurations.

Game manuals can easily be found on http://segaretro.org

Bill Walsh, FIFA International Soccer & NHL 94 are EA games which usually only work with 4-WayPlay and the manual mention they are not compatible with 6-buttons gamepad (need the MODE button trick) so they should work with WayPlay+3B in both Port 1 & Port2 (to be more precise, that multitap had two cables which must  be connected to both ports at the same time)

According to their manual, Dungeon Explorer & ESPN National Hockey Night are TeamPlayer compatible games and seem to only support 3-buttons gamepad configuration so I would try Teamplayer+3B on port 1 if I were you

**Comment by newoski** [comment]
Hmmm. No go with those combos or any others I've tried. Is it confirmed working by others?

**Comment by ekeeke** [comment]
I don't need others confirming it, I know it works because as already said, all games use the same code to handle those multitaps so if emulation wasn't fine, all games would fail detecting them.

Here you go anyway with aforementioned configurations (note that ESPN National Hockey Night seems compatible with TeamPlayer but also EA 4Way-Play)

![retroarch-1213-011936](https://cloud.githubusercontent.com/assets/717091/21122964/efd89cc6-c0d5-11e6-9f62-a30d84e6e71d.png)

![retroarch-1213-013421](https://cloud.githubusercontent.com/assets/717091/21122963/efd7bad6-c0d5-11e6-928e-4356bae748f1.png)

![retroarch-1213-013702](https://cloud.githubusercontent.com/assets/717091/21122966/efdb2a9a-c0d5-11e6-82fb-bfd348a51575.png)

![retroarch-1213-013948](https://cloud.githubusercontent.com/assets/717091/21122962/efd7afb4-c0d5-11e6-98d9-9f8deef0e66e.png)

![retroarch-1213-014059](https://cloud.githubusercontent.com/assets/717091/21122965/efdaa084-c0d5-11e6-9186-6242d15418b2.png)

**Comment by newoski** [comment]
so weird. ive tried like every combo. any chance you can upload per game overrides with the settings that work for you? happy to send some beer money. this is killing me

**Comment by ekeeke** [comment]
Nope , sorry, I don't know how to do that (I barely use retroarch myself except for tests like that) and I'm not even sure that old version I use supports per game settings.

You will have to manage it yourself like you did with other games (which also did not worked for you initially).

You are probably doing something wrong with input settings (although I admit this part is not very clear in Retroarch since what the emulator is referred as port 1 and port 2 (for emulated devices) is labelled as "player 1" and "player 2" in retroarch, which can be confusing.

Here are the settings I used:

4-Way Play:

![4wayplay-port1](https://cloud.githubusercontent.com/assets/717091/21123278/03f044c8-c0d8-11e6-9764-005727fa2e3b.jpg)
![4wayplay-port2](https://cloud.githubusercontent.com/assets/717091/21123279/03f157dc-c0d8-11e6-8719-734f8a7a2587.jpg)

Teamplayer

![team-port1](https://cloud.githubusercontent.com/assets/717091/21123362/75bb81b2-c0d8-11e6-9d63-29f7a94a25e1.jpg)
![team-port2](https://cloud.githubusercontent.com/assets/717091/21123363/75bc1262-c0d8-11e6-8e0c-ceeea80f54a3.jpg)

**Comment by newoski** [comment]
Wow, so this is interesting. NHL 94 seems to work, with those settings, but here's the problem... After pressing Start at the SEGA screen, the controller stops responding until after the intro video and credits which takes forever. If I wait until after the credits are done, then the 4 controllers work. This is so weird...

**Comment by ekeeke** [comment]
I don't know, I don't have this issue. 

Are you using the core dll provided by retroarch or one compiled from here? I noticed another commit which has not been backported by libretro into their Genesis Plus GX repository and might cause some issues with input descriptors.

https://github.com/ekeeke/Genesis-Plus-GX/commit/ff2cb27f486d61cf824bf1bd525b28ff2dfd65eb
