### ISSUE TITLE
[libretro] small code bug

### ISSUE THREAD

**Issue by lab313ru** [ekeeke/Genesis-Plus-GX#121]
https://github.com/ekeeke/Genesis-Plus-GX/blob/master/libretro/libretro.c#L719
*base = '\0'
should be:
*buf = '\0'
because of base will be const char *

**Comment by ekeeke** [comment]
Sorry but I see nothing wrong with that code and your "fix" actually breaks it so I'm not sure what you think it should do. 

FYI, "buf" is a "char *" copy of the full "path"  filename without full directory path. "base" is not a "const char *" but a "char *" pointing to last '.' character in "buf" string. The aim of this function is to get the base filename without it's extension. Afaik, it works as expected otherwise per-game SCD Bram saves would not work properly.

**Comment by lab313ru** [comment]
Compare wth extract_directory function. You're using temp buffer. But not in extract_name. How can you change char *base which was taken from const char *path? That's why you're using temp buffer.
