### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by claudiuslollarius** [ekeeke/Genesis-Plus-GX#122]
Would you consider moving to CMake as build system?

I am looking into adding support for UWP (which means building with Viusal Studio) to Genesis-Plus-GX and am wondering if it is something you'd be interested in. If so, the easiest way to keep cross compatibility with multiple build environments would be to use CMake.

I'm willing work with you to recreate the build scripts in CMake if you are interested, otherwise I'll just make my own fork and won't be able to contribute back upstream.

**Comment by ekeeke** [comment]
What do you mean by "moving to to CMake as build system" ? There isn't a single "build system" but different Makefiles for each platform supported by the emulator so it should be possible to add support for a new platform without breaking existing ones.

I am not familiar (or interested) enough with CMake though to know what it involves adding or changing in existing Makefile . What is sure is that I definitively won't drop support for existing build systems since it's what I'm using.

Since it seems to be platform-specific, you could always put this in a specific directory like libretro is doing (which already include MSVC building scripts by the way)

Proper way is to submit a pull request with anything you need to add support for UWP and I will review it.
