### ISSUE TITLE
Cross-platform netplay incompatibility

### ISSUE THREAD

**Issue by LordHDL** [ekeeke/Genesis-Plus-GX#123]
Probably not a priority, but figured I'd report at least.

Upon attempting Mac to Windows netplay via RetroArch, the GPGX core disconnects with the message "This core does not support inter-architecture netplay."  I reported that on their repository and was told that it's an issue within the core itself.  Specifically this:

> IIRC it is due to the core itself (e.g. the "long" type is 64-bit on one platform and 32-bit on another, due to LP64 vs LLP64, or some math always assumes big vs little endian)

Is support for this a possibility?

**Comment by ekeeke** [comment]
"long" type was removed from the core "long" time ago (especially for cross compatibility with 64-bit from what I recall, see version 1.7.0 in HISTORY.txt), it only remains used in 3rd party libraries required by Genesis Plus GX (libtremor, blip buffer and ntsc filters) but afaik this has zero impact on savestates (which is what Retroarch is using for netplay) so they should be cross compatible between 32-bit and 64-bit.

The only incompatibility would be between big endian and little endian systems (maybe it's the case here if your Mac is a PowerPC one) but I am afraid this cannot be easily changed since every saved data bigger than one byte in memory is impacted. And contrary to what that libretro dev told you, it's not that the emulator is always assuming big endian but that the emulator obviously assumes the endianness of loaded data is the same as the one of the platform it runs on. Forcing savestate data format to little endian would be unefficient since it would require converting format everytime you load or save state on big endian platform. 

That said, I doubt there are many emulators (if any) for which savestates are cross compatible between big endian and little endian platforms.

**Comment by ekeeke** [comment]
looking at commit history, the following one is the reason the core wrongly reports platform-dependent savestates

https://github.com/ekeeke/Genesis-Plus-GX/commit/02ec6fdf0ebabe2b01824b7f906c2b27e68fa7dd

It's probably just a matter of only reporting the right "quirk" i.e endian-dependent savestate
