### ISSUE TITLE
Compiling no longer works due to #120

### ISSUE THREAD

**Issue by nadavbh12** [ekeeke/Genesis-Plus-GX#125]
I used to be able to compile the repository simply by cloning and running `make`.
After #120, this no longer works.

This is crucial for me since [my repository relies on this](https://github.com/nadavbh12/Retro-Learning-Environment/blob/master/CMakeLists.txt#L134) behavior for its compilation.
This behavior is consistent with the other libRetro repositories I use.

**Comment by ekeeke** [comment]
This is probably because of [this](https://github.com/ekeeke/Genesis-Plus-GX/pull/120/commits/64ee605076b4f63e3a3a65316323cc61f210f030) commit which add pragma incompatible with MSVC compiler.

Coincidentally, a [pull request](https://github.com/ekeeke/Genesis-Plus-GX/commit/a809aa86d001a0853e0b81496f64f18efb156033) was made today in order to restore compatibility with MSVC so it seems like you are lucky.

**Comment by nadavbh12** [comment]
The problem is the lack of a default makefile.
[This](https://github.com/ekeeke/Genesis-Plus-GX/commit/641fb280bc03a26f642ed3bafbffded13b0fcf81) works well, while the [following](https://github.com/ekeeke/Genesis-Plus-GX/commit/25035ea8db95c0d4c3d72adc8265419312df5e8a), not surprisingly, doesn't work.
Now I understand that a better phrasing of my complaint is a lack of a default makefile as present in other libretro repos.

Why did you decide to remove it?

**Comment by ekeeke** [comment]
Because the default Makefile pointed to libretro Makefile and this is multi-platform project, not a libretro project. Just because a libretro port exists or it makes it easier to build for your specific project is not a valid reason to add platform specific stuff as default build behavior, sorry.

Really, it's only a matter of calling make -f Makefile.libretro instead of make, it's not that complicated.

**Comment by nadavbh12** [comment]
That makes sense. Just found it strange that it deviates from other LibRetro repos.
