### ISSUE TITLE
Reading from $A11004 crashes the core

### ISSUE THREAD

**Issue by lab313ru** [ekeeke/Genesis-Plus-GX#128]
So, problem is that when I'm reading from $A11004 at the first instruction, GX goes to the following code:
```
if ((address & 0xFE) == 0x04)
{
  unsigned int data = svp->ssp1601.gr[SSP_PM0].byte.h;
  svp->ssp1601.gr[SSP_PM0].byte.h &= ~1;
  return (address & 1) ? (data & 0xFF) : (data >> 8);
}
```
Visual Studio throws an exception about:
```
Exception thrown: write access violation.
svp was nullptr
```
at line `svp->ssp1601.gr[SSP_PM0].byte.h &= ~1;`

**Comment by lab313ru** [comment]
Addition:
Problem in this code:
```
  /**********************************************
          SVP CHIP 
  ***********************************************/
  svp = NULL;
  if (strstr(rominfo.international,"Virtua Racing"))
  {
    svp_init();
  }
```
But my rom doesn't have such string, and SVP still equals to NULL.

**Comment by lab313ru** [comment]
```
 MEMORY MODE

 

The MEGA DRIVE is able to generate internally

the REFRESH signal for the D-RAM development

cartridge.  When using the development cartridge

set to D-RAM MODE. In the case of a production

cartridge, set to ROM MODE.

 

 Only D8 of address $A11OO0 is effective and for WRITE ONLY.

 

           $A11OO0       D8 ( W)   O: ROM MODE

                                   1: D-RAM MODE

 

ACCESS to $A11OO0 can be based on BYTE.
```

**Comment by ekeeke** [comment]
It indeed was a bug in the code. Now fixed by https://github.com/ekeeke/Genesis-Plus-GX/commit/0fc6a09b1d373d63ab5d7d55f82c7ab4f793404f

**Comment by lab313ru** [comment]
But what will be, if I’ll read from A15004? Maybe it will be better to check against null pointer before reading?

**Comment by ekeeke** [comment]
Yes, but that would be a later fix and is unrelated to your issue. I have no idea why you want to read from A110xx since it does nothing on the emulator or real hardware, but at least it doesn't read from SVP anymore.
A150XX is reserved for SVP so there is no point in using that address range if you don't use SVP. And if want to use it, I would need to modify the emulator anyway to detect your game and initialize SVP for it.
Similarly, when someone will make a cartridge that use that range for something else, I'll eventually add support for it but for the time being, let's say it's a way to detect errors in homebrew code (and also a way to detect emulators or emulation devices illegaly using our code).


Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Lab 313 <notifications@github.com> Date : 15/04/2017  11:17  (GMT+01:00) À : ekeeke/Genesis-Plus-GX <Genesis-Plus-GX@noreply.github.com> Cc : ekeeke <ekeeke31@gmail.com>, State change <state_change@noreply.github.com> Objet : Re: [ekeeke/Genesis-Plus-GX] Reading from $A11004 crashes the core (#128) 
But what will be, if I’ll read from A15004? Maybe it will be better to check against null pointer before reading?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ekeeke/Genesis-Plus-GX","title":"ekeeke/Genesis-Plus-GX","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ekeeke/Genesis-Plus-GX"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lab313ru in #128: But what will be, if I’ll read from A15004? Maybe it will be better to check against null pointer before reading?"}],"action":{"name":"View Issue","url":"https://github.com/ekeeke/Genesis-Plus-GX/issues/128#issuecomment-294281973"}}}

**Comment by lab313ru** [comment]
I'm writing a debugger module, that uses your core. And it will support the IDA debugger. I've found this error, when I've eventually read from this address, when it was opened in IDA listing. So, user is possible to open any address and IDa will read from it, and it will follow to crash.

Sure, I can write a workaround for this situation, but it will be not good solution at all.

**Comment by ekeeke** [comment]
I see. But as I said, reading from this address (and many other addresses in illegal access range) will cause a lockup if SVP is not connected on real hardware (hard reset required) and therefore on emulator if I correct this. How would IDA behaves if the emulator is in locked state ? Is it able to detect it ?

**Comment by lab313ru** [comment]
I can add the detection code, no problem.

I'll explain more: There is a valid memory map for Sega Genesis. And it is possible that user will try to see the content of any available region.

**Comment by p1pkin** [comment]
@lab313ru accessing MMIO address space is known to be problem in emulator debuggers development.
in general case, even simple read (by debugger memory viewer) certain MMIO may affect virtual machine state like cancelling pending IRQs, increasing counters, or even starting some DMA, etc.
so in perfect case either emulator or debugger have to determine is it was read by emulated CPU or its just debugger memory viewer (or some helper), and in last case disable assess to areas which may change VM state, typically MMIO.
