### ISSUE TITLE
Sprite issue in Sonic 2

### ISSUE THREAD

**Issue by SuperrSonic** [ekeeke/Genesis-Plus-GX#133]
![s2_0502-194400](https://cloud.githubusercontent.com/assets/6880539/25643966/a7268a6a-2f57-11e7-9bd0-e3e001949f28.png)
The bridge graphic has some parts disappear when going through it. I am unsure if this happens on real hardware but I have tested the following:

Sonic Mega Coll
Sonic Gems Coll
Sonic Classic Coll
Wii VC
3D Sonic 2

None of which showed this issue.

**Comment by ekeeke** [comment]
This does not look like normal sprite masking should happen there. I've also never seen this happening in game from what I remember and can not reproduce it either.

What version of the emulator is this picture coming from ? What ROM version ? How do you reproduce this issue exactly ? Does it happen with all bridges in the first level ? only this one ? under some specific conditions ?

**Comment by SuperrSonic** [comment]
-1.7.4 RetroArch, and Wii port 1.7.5
-Tested 1051-00, 1051-01, and a byte different version of 01 from the VC.
-Play as you would until you reach that specific point.

I am unsure, I've only seen it in act 1. If you use a shield it becomes flickery instead of missing.
So far I have only seen it in the bridges from the screenshot; near the end of the act, right before the last waterfall.

**Comment by ekeeke** [comment]
Could you make a savestate using the latest Wii version (https://github.com/ekeeke/Genesis-Plus-GX/blob/master/builds/genplus_wii.dol) at the exact point where this happens then upload it there (also upload the png screenshot that is created with the state file)

**Comment by SuperrSonic** [comment]
[S2_state.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/975337/S2_state.zip)

**Comment by ekeeke** [comment]
Thanks, I see that spot now.
 I think this is normal, there are too much sprites on same lines (hardware limit is 20 sprites per line, including sprites horizontally outside the visible screen range): not even counting tail & sonic sprites, there are already 20 wood log sprites + 3 higher priority sprites used on each ends of the bridges on the same lines so the last three wood log sprites will always be masked. When you add both characters sprites, this will mask even more wood log pixels on some of the lines or give flickering depending how they are positioned and animated.

I will need to verify that this happen on real hardware but I'm pretty sure it does since this hardware limitation is quite well documented. The fact it is not emulated in commercial emulators is not really surprising.

**Comment by ekeeke** [comment]
Confirmed to happen on real hardware

![20170504_205015](https://cloud.githubusercontent.com/assets/717091/25720092/f3686a28-310b-11e7-92ff-dcd18378e516.jpg)
