### ISSUE TITLE
Screenshots being cut in the preview

### ISSUE THREAD

**Issue by SieKensou** [ekeeke/Genesis-Plus-GX#135]
This is not exactly an issue, more like a design problem. I noticed the screenshots are cut down and they are not correctly centered on the cartridge. It is more on the left part and the right part has more black. And the problem of being cut down could be fixed if the SEGA band would removed. If anyone wants to put it back, it can be added to the screenshot itself... I know you probably don't care about this, but I think it would look much better. 
Here is a picture:
![hqdefault](https://cloud.githubusercontent.com/assets/28622717/26099884/687c9180-3a2c-11e7-94f3-e112feac96a1.jpg)

The yellow part is the actual visible screenshot, part and the blue part is the aditional space that could be used for the screenshots to show them entirely.

Additionally, I noticed that sometimes, when you take a screenshot with genplus gx, it shows some garbage at the top of the screenshot.

**Comment by ekeeke** [comment]
Yes, this is a design choice and I'm personally fine with screenshot being partially hidden by the MD cartridge picture so I won't change it, sorry.

As for your 2nd remark, I noticed it myself as well, it seems like a race condition where the GPU HW rendering to memory got interrupted and end up partially corrupted. It's quite rare though and is easily fixed by making another screenshot.

**Comment by SieKensou** [comment]
Okay, Thanks for the reply. It's understandable.
Is not possible to at least centered it correctly horizontally?

**Comment by SieKensou** [comment]
Okay, thank you for the reply.
Yeah, as I said, it wasn't something important, just my thoughts about the design. But you are right, it's fine.
This is by far the best emulator for the Wii.
