### ISSUE TITLE
LOG_SVP broken

### ISSUE THREAD

**Issue by lab313ru** [ekeeke/Genesis-Plus-GX#157]
https://github.com/ekeeke/Genesis-Plus-GX/blob/master/core/cart_hw/svp/ssp16.h#L20

There is no such variable 'frame_count'.

**Comment by ekeeke** [comment]
As written in header file, this is a left-over from picodrive code where this file is originally coming from,  logging is enabled in this emulator because and not supposed to be enabled either.

If you want logging in your own application for whatever reason then you are free to print whatever information you want in log message and modify this to your own need.
