### ISSUE TITLE
Pause and Start button(genesis/megadrive) as separated buttons

### ISSUE THREAD

**Issue by FeRcHuLeS** [ekeeke/Genesis-Plus-GX#159]
A hack for using one genesis gamepad instead of 2 sms gamepads has just been released, while the pause button pauses the game and the start button accesses menu screen then both can happen, pause or screen menu randomly. The game in question is Cyborg Hunter for sms.

http://www.smspower.org/forums/16791-CyborgHunterMSMDPadHack#99398

**Comment by FeRcHuLeS** [comment]
An idea just occured to me maybe is possible to map screen button to A button, I'll ask the hacker.

**Comment by ekeeke** [comment]
Indeed, I do not see the purpose of mapping anything anymore to the pause button when the goal is actually to use genesis gamepad extra buttons. 

This would require too many changes in emulator code (especially the frontend part), it's just not worth it in my opinion.

**Comment by FeRcHuLeS** [comment]
I see your point, I think this emulator should offer more options please consider the following (A playstation controller as reference "select button"-"start button"-"R2 button"):

I think the MODE button is misplaced as "select button" this should be placed as one of the shoulder buttons ("R2 button" I propose to feel more like a genesis 6 buttons pad), then put in its place the SMS PAUSE button instead.
The PAUSE button should be "start button" as long as the Genesis 3/6 buttons gamepads are not selected, then when these gamepads are selected START button is "start button" and there is already a PAUSE button as "select button".

**Comment by ekeeke** [comment]
I am not responsible for libretro default mapping, sorry. I am sure any buttons can be remapped as you want in retroarch but I doubt you can have dynamic mapping based on emulated system. Retroarch, as a multi-emulator frontend, uses a generic virtual controller and it has some limitations.
-------- Message d'origine --------De : FeRcHuLeS <notifications@github.com> Date : 01/09/2017  19:14  (GMT+01:00) À : ekeeke/Genesis-Plus-GX <Genesis-Plus-GX@noreply.github.com> Cc : ekeeke <ekeeke31@gmail.com>, State change <state_change@noreply.github.com> Objet : Re: [ekeeke/Genesis-Plus-GX] Pause and Start button(genesis/megadrive) as separated buttons (#159) 
I see your point, I think this emulator should offer more options please consider the following (A playstation controller as reference "select button"-"start button"-"R2 button"):
I think the MODE button is misplaced as "select button" this should be placed as one of the shoulder buttons ("R2 button" I propose to feel more like a genesis 6 buttons pad), then put in its place the SMS PAUSE button instead.

The PAUSE button should be "start button" as long as the Genesis 3/6 buttons gamepads are not selected, then when these gamepads are selected START button is "start button" and there is already a PAUSE button as "select button".

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ekeeke/Genesis-Plus-GX","title":"ekeeke/Genesis-Plus-GX","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ekeeke/Genesis-Plus-GX"}},"updates":{"snippets":[{"icon":"PERSON","message":"@FeRcHuLeS in #159: I see your point, I think this emulator should offer more options please consider the following (A playstation controller as reference \"select button\"-\"start button\"-\"R2 button\"):\r\n\r\nI think the MODE button is misplaced as \"select button\" this should be placed as one of the shoulder buttons (\"R2 button\" I propose to feel more like a genesis 6 buttons pad), then put in its place the SMS PAUSE button instead.\r\nThe PAUSE button should be \"start button\" as long as the Genesis 3/6 buttons gamepads are not selected, then when these gamepads are selected START button is \"start button\" and there is already a PAUSE button as \"select button\". "}],"action":{"name":"View Issue","url":"https://github.com/ekeeke/Genesis-Plus-GX/issues/159#issuecomment-326635787"}}}
