### ISSUE TITLE
[libretro] Lightgun support problems

### ISSUE THREAD

**Issue by ensra** [ekeeke/Genesis-Plus-GX#166]
Hi ekeeke, thanks for the great work on this emulator. :)

I've managed to get the MD Mouse to work a few times, but I've honestly no idea how. Usually when I select the controller type then reset the core no input is recognized. I'm not sure if I'm doing something wrong here.

Using the standard emulated lightgun with a crosshair, the input tracking is quite a bit better than using an emulated mouse, but getting the lightgun to reload by pointing at the edge of the screen requires pixel-perfect precision. Eventually when taking the mouse outside of the rendering area it will re-position the crosshair to the dead centre. It'd be useful to be able to assign a button to reload to work around this.

I'm using the CD game Mad Dog McCree (USA) to test this.

**Comment by ekeeke** [comment]
Mouse works fine from what I tested. Most games will need it connected in port 2 though. Please note that the emulator will automatically enable lightguns for known lightgun games since they usually only work with that. If mouse is supported and you want to use that instead, you will need to force it in retroarch settings once the game is loaded then reset (not restart !) the core to force a soft-reset.

As for lightgun support, center repositionning is due to values returned by libretro input api when going outside screen limits, there is nothing I can do about it. Assigning a button to reload is not possible because of the way those games were programmed, you could eventually force lightgun x/y values when some predefined button is pressed but that would be very hacky and game specific and I don't want to do that. Most generally, I don't want to put much time and work on libretro port since I personally don't use it and prefer to focus on emulation code.

**Comment by ensra** [comment]
>Most games will need it connected in port 2 though.

That's exactly it - sorry about that... I was trying older revisions because I thought it was working months ago, but yeah, it's Port 2.

>As for lightgun support, center repositionning is due to values returned by libretro input api when going outside screen limits, there is nothing I can do about it. Assigning a button to reload is not possible because of the way those games were programmed

Fair enough. Thanks.

**Comment by Huntsman360** [comment]
alarixnia if you need it, i create a ahk script that remaps "mouse button 2"  to shot 6 times in cordinates 11,11. So if you are playing in 4:3 that area is black and offscreen so it reloads

I use this ahk when i launch retroarch with genesis plus gx core in hyperspin and with this my sinden lightgun reloads when i shot offscreen, because it send button 2 mouse and this is redirected to shot in 11,11 coordinates
