### ISSUE TITLE
[Wii] Error: File it's too Large (CHD)

### ISSUE THREAD

**Issue by LodanZark** [ekeeke/Genesis-Plus-GX#167]
On Wii by loading a CHD Sega CD File (256 MB) gives the error "file is too large, Press A to continue." followed by "Unable to load game,  Press A to continue.

I'm using the build uploaded  5 days ago.

**Comment by ekeeke** [comment]
Yes, for some reason that build got reversed when merging libretro changes (totally unrelated to CHD support) five days ago: https://github.com/ekeeke/Genesis-Plus-GX/commits/master/builds/genplus_wii.dol

The last build (with CHD support) is actually the one commited 16 days ago: https://github.com/ekeeke/Genesis-Plus-GX/blob/05dc8faa0419869438fc1a3c2b1741e87fea0178/builds/genplus_wii.dol

**Comment by redmagejoe** [comment]
I know this is an extremely old issue, however I'm encountering the exact same problems. I was initially using a build that was linked from WiiBrew that had apparently been uploaded 2015. I then followed your links to get the "16 days ago" commit that said it had CHD support. Finally, I'm now on the most recent boot.dol (for Wii) that I could find on this repo, and I get the exact same error message.

Is there something I'm neglecting, or did something happen to CHD support somewhere along the way?

**Comment by ekeeke** [comment]
The latest build is always available from here: https://github.com/ekeeke/Genesis-Plus-GX/tree/master/builds

All you have to do if you are using homebrew channelis to rename genplus_wii.dol into boot.dol and copy it on your sdcard in place of the existing one.

CHD file support works fine and nothing has changed with it since it was first implemented: if you get the "file is too large" error message, it means either the file is not recognized as a chd file (file extension is not exactly .chd or .CHD) or you still launch an older version of the emulator, before CHD support was implemented.

**Comment by redmagejoe** [comment]
I wish I understood what I was doing wrong. The CHDs are good, as they run in RetroArch with Genesis Plus GX core (1.7.4 was the core it grabbed automatically), using the same BIOS (albeit with different names as required by the two platforms), but not in Wii. Wii GPGX runs bin/cue, and I'm using the latest dol from the builds page. I really cannot for the life of me figure out why Wii GPGX won't run them.

Is there a setting I'm overlooking?

**Comment by ekeeke** [comment]
I have no idea how channel forwarders work, sorry, but 'forwarder' seems to imply it loads a dol stored somewhere else so maybe that dol can be updated somewhere on sdcard? If the dol is embedded with the channel, you will have to create a new one with an up-to-date dol and reinstall it.
