### ISSUE TITLE
Lunar The Silver Star: The voices are delayed

### ISSUE THREAD

**Issue by garytr** [ekeeke/Genesis-Plus-GX#197]
I think the voices in "Lunar The Silver Star (USA)" (CHD) are delayed.

Please play the mp4 file.
[Lunar - The Silver Star (USA) (Genesis Plus GX).zip](https://github.com/ekeeke/Genesis-Plus-GX/files/1424707/Lunar.-.The.Silver.Star.USA.Genesis.Plus.GX.zip)
The girl doesn't say anything at first two seconds.
She can't say "Please tell me what's wrong".

Original (?):
https://www.youtube.com/watch?v=WLjC4qyocMU#t=2m46s
She can say "Please tell me what's wrong".

**Comment by ekeeke** [comment]
I don't understand: it's delayed or it does not play the sentence she is supposed to say? 

Delayed audio (especially 2s since it's usually the pause between audio tracks) is generally a sign of bad game rip or bad cuesheet (CHD images are generally converted from cue/bin) so try with another image.

I will try that game when I get some time but I don't remember any sync issue with this one.

**Comment by garytr** [comment]
@ekeeke 
> generally a sign of bad game rip or bad cuesheet

Maybe you are right.
I think this game needs multiple bin files and mine is different.

> I don't understand: it's delayed or it does not play the sentence she is supposed to say?

It was delayed to start, so she couldn't finish saying.

(Original) 
> Good morning, Alex. (...) Please tell me what's wrong.

(Genesis-Plus-GX)
> (She didn't say anything for two seconds) Good morning, Alex. (...) Please tell me (stopped.)

@ekeeke 
> I don't remember any sync issue with this one.

Maybe Genesis-Plus-GX is almost perfect, and there are no major/easy-to-find bugs.
I close this issue.

**Comment by garytr** [comment]
I tested another image (it includes 52 tracks) and Genesis-Plus-GX works perfectly.
Sorry for the annoyance.
