### ISSUE TITLE
Problem with 448i mode and CRT Royale.

### ISSUE THREAD

**Issue by James-F2** [ekeeke/Genesis-Plus-GX#204]
GPGX reports to retroarch 1x=448p in 448i mode (double field), which results in wrong scaling with CRT-Royale shader.

Snes9x and Beetle-PSX continue to report 1x=240p/224p to retroarch in 480i/448i mode so CRT-Royale processes them correctly.

**Comment by James-F2** [comment]
Thread about this on libretro:
https://forums.libretro.com/t/crt-royale-448i-480i-scaling-on-1200p-monitor-problem/13967/8

**Comment by ekeeke** [comment]
GPGX outputs 448 lines buffer in 'double field' interlaced mode so there is no reason to report wrong height or this will break. The issue is obviously with your shader not being able to deal with double sized framebuffer, not an emulator issue. If you want the core to output 224 lines per field and report that height, set the core setting to 'single field'.

**Comment by James-F2** [comment]
Hi ekeeke.
Yes, I understand that GPGX reports the output resolution from the framebuffer, which strangely no other emulator in retroarch that switches between 240p and 480i modes does this.
Maybe we should at least try to go towards a solution?

**Comment by James-F2** [comment]
CRT Royale handles double sized framebuffer very well and is designed to do so; it is retroarch "integer-scaling" that is confused by the reported base resolution.  
The solution for other emulators is to have fixed base resolution but also keep the double sized framebuffer how it should.

**Comment by ekeeke** [comment]
I think the problem is that libretro definition of what 'base_width' and 'base_height' are can be quite confusing. I always wondered what was the use for these since core rendered image width/height are already reported on each frame through video callback but it seems like it is used to initialize video driver (screen resolution or windows size in particular) but also for scaling and aspect ratio calk

Again, the reported height is correct:
- in double field mode, the core does the interlacing itself and outputs a 320x448 pixels buffer every 'frame', so it is technically more like 448p since all 448 lines are rendered at once.
- in single field mode (default setting), the core reports and outputs 224 lines like real VDP hardware does and interlacing must be handled by the frontend.

Core reported aspect ratio is also correct so probably it's likely an issue with retroarch scaling when reported aspect ratio is ignored in favor of hard-coded integer scaling (which probably handle 320×448

Maybe there is a confusion what 'base height' is for libretro but GPGX has the ability to handle vertical resolution in-game switching (not just interlaced mode but also 224/240 lines modes for PAL systems or Mode4/Mode5 switching). 

Hacking the core to report an hardcoded base height regardless of the rendered height seems quite dirty ,

**Comment by James-F2** [comment]
> an intermediate solution could be to not double base_height value (and not adjust core aspect ratio either) when double field interlaced mode is enabled (but still leave the framebuffer height correctly set to 448 in video callback function) but I am not sure of the side effects with other shaders or when using different retroarch scaling settings so you will have to do it (and test it in various cases) yourself.

I believe this is exactly what is going on with most mode changing cores in retroarch.
Unfortunately I have no experience with programming so I could not do it myself.

**Comment by ekeeke** [comment]
What if you disable Integer Scaling and use Core Aspect Ratio ?

**Comment by James-F2** [comment]
The image will be stretched to the monitor vertical border while maintaining 4:3 aspect ratio.

> so this can not be hard coded to a fixed value like in other cores (this would result in stretching everything vertically to a multiple of that fixed size which would be incorrect for many games

Yes, this is what's going on for Snes9x and Beetle-PSX even with PAL games, the core reports 240 base vertical resolution.

**Comment by ekeeke** [comment]
>The image will be stretched to the monitor vertical border while maintaining 4:3 aspect ratio

Assuming by vertical borders you mean left/right side of the screen, isn't it actually what should be correctly expected?

**Comment by James-F2** [comment]
Sorry I meant top/bottom borders vertically.

The goal of having fixed reported base height is so that the "integer-scaling" option will not change the window size as understood.
I should mention that CRT-Royale shader uses the double-field interlaced 448i signal form the framebuffer and displays it correctly in a 224p while showing the even lines first then the odd lines, thus behaves like a CRT would.
So it is important to keep the reported base resolution from the core at 224p and not change it to 448p.

**Comment by ekeeke** [comment]
>I should mention that CRT-Royale shader uses the double-field interlaced 448i signal form the framebuffer and displays it correctly in a 224p while showing the even lines first then the odd lines, thus behaves like a CRT would.

Then there is no need to enable 'double field' setting, keep it at 'single field ' and the core will alternatively output odd and even fields while reporting 224 lines as base height.

Like I said, 'double field' makes the core output a FULL 448 lines image on each frame , thus being more 448p than 448i, hence why reported base height is 448 and not 224

**Comment by James-F2** [comment]
I think I over-simplified how the shader shows interlaced content, it doesn't look like the simple single-field method in GPGPX or as I described.
The shader actually uses the monitor full native resolution (1080p/1200p/2160p) to display the 448 lines how a CRT would with complex position calculations and filtering, etc..
The resulting output of that specific shader depends on using as much native monitor resolution as possible while still keeping correct vertical ratio, which in this case is corrupted by the reported base 448p.

It is not about fixing GPGX to support this particular shader, but more conforming to how other quality cores behave.

**Comment by James-F2** [comment]
To clarify a little;
The shader should receive a 448i from the framebuffer but retroarch should NOT change from the base 224p.
This way all shaders work correctly and the images does not change its size in Integer-Scaling mode.

**Comment by ekeeke** [comment]
I understand the proposed solution (which I initially exposed myself) but the problem is that there is no clear understanding on what should exactly be reported as base height in libretro and how this information is used by retroarch exhaustively. Your issue seems specific to this CRT shader (as it does not occurs when you use other shader or raw output, right?) and seems to be a problem with handling proper aspect ratio scaling of 320x448p content (as I assume this shader has no issue with 640x448p content, right?). That's why I am reluctant to hack the core to report an height different from the actually rendered height just because of some shader expectation (or limitation). The fact that other cores do it that way does not mean this is the correct way to handle this or that they are correct in regard to libretro API (again, as explained previously, fixing the base height to some arbitrary height will result in games to be incorrectly stretched if they use some other height modes).

Now, if someone wants to give this a go, it's a simple change, replace 'vheight' by ' bitmap.viewport.h + (bitmap.viewport.y * 2)' here:
https://github.com/ekeeke/Genesis-Plus-GX/blob/master/libretro/libretro.c#L1981

**Comment by James-F2** [comment]
> Now, if someone wants to give this a go, it's a simple change, replace 'vheight' by '**bitmap.viewport.h + (bitmap.viewport.y * 2)**' here:
https://github.com/ekeeke/Genesis-Plus-GX/blob/master/libretro/libretro.c#L1981

Compiled and Tested.
Yep, now all shaders and scalers work precisely as they should, this is ideal solution and matches other 240p/480i switching cores behavior.
Hopefully you don't overlook it ekeeke and make it part of GPGX.

> Your issue seems specific to this CRT shader (as it does not occur when you use other shader or raw output, right?)

No, the issue is not specific to the shader, it is about maximizing screen area while still using integer multiply scaling.

The reported vertical height is used by retroarch to adjust **final** output scaling parameters including the "Integer-Scaling" and "Aspect Ratio" options.
The reported horizontal resolution is much less important and is stretched with non-integer scaling to match the "Aspect Ratio" option which has its base from the reported vertical resolution.

224 and 240 integer scale perfectly on a 1200p or 1440p monitor with very little or none top/bottom black boarders, and these monitors are preferred for retro gaming.
448/480 on the other hand results in a much smaller window on a 1200p monitor but fits perfectly 1440p monitor.

**Comment by ekeeke** [comment]
>No, the issue is not specific to the shader, it is about maximizing screen area while still using integer multiply scaling.

>The reported vertical height is used by retroarch to adjust final output scaling parameters including the "Integer-Scaling" and "Aspect Ratio" options.
The reported horizontal resolution is much less important and is stretched with non-integer scaling to match the "Aspect Ratio" option which has its base from the reported vertical resolution.

>224 and 240 integer scale perfectly on a 1200p or 1440p monitor with very little or none top/bottom black boarders, and these monitors are preferred for retro gaming.
448/480 on the other hand results in a much smaller window on a 1200p monitor but fits perfectly 1440p monitor.

I understand but you have to realize it's not 'integer scaling' anymore since the 448-lines high image is upscaled to a multiple of 224, not 448. It's ok for 1440p output since both 224 and 448 multiply to identical factor ( 224 x 6 = 1344 = 448 x 3) but will result in every 3 lines being 'crunched' in case of 1200p output (224 x 5 = 1120 = 448 x 2.5).

>CRT shaders are the most used shaders for retro purposes and are very complex and accurately emulate a CRT, but Integer-Scaling is an absolutely must for properly aligned scanlines.
It only works fine with CRT shader because that particular shader only takes half of the 448-lines high image **in that particular case** and scales the 224-lines high resulting image but for any other shader that do no do de-interlacing or simpler hardware upscaling, this will result in misaligned scanlines as explained above (although probably not so visible thanks to hardware filtering).

>These shaders are more accurate with high resolution monitors and can even emulate a proper shadowmask/aperture grill.
Taking away the monitors real-estate by integer scaling a 448i image as 448p makes de-interlacing shaders (not CRT Royale in particular) less accurate and unnecessarily shrinks the image.

I agree but an ideal (and lot cleaner) solution would be for the core to report to Retroarch (andshaders by extension) when content should be interlaced or not, then use core single-field output to let shaders do the  interlacing themselves (i.e render the 224p core output on odd then even lines). Here the shader is using the fact that reported output buffer height and reported base height differs to detect interlaced content so it fan deinterlace it and reinterlace it itself (which is kind of unefficient) so the proposed solution (and solution used by other cores for similar case) is kinda a hack around the libretro API (since it was obviously not designed to deal with interlaced core output).

Also, again, if Retroarch scaling was properly dealing with 320x448 content by independently upscaling the width and the height (instead of using a common upscaling ratio for both) to match screen output resolution, it would maybe have been less 'accurate' (since interlacing is done by the core and not by a complex shader) but you would not have noticed that issue as it would have fit the screen both horizontally AND vertically.

**Comment by James-F2** [comment]
> Also, again, if Retroarch scaling was properly dealing with 320x448 content by independently upscaling the width and the height (instead of using a common upscaling ratio for both) to match screen output resolution,

It does handle H/V scaling independently.
There are a lot of final scaling options to choose from in retroarch including custom ratio.

> Here the shader is using the fact that reported output buffer height and reported base height differs to detect interlaced content

No, shaders don't receive the base at all, they only use the buffer.
The base is only for retroarch **final** scaling, and it doesn't know the frame buffer.

> you have to realize it's not 'integer scaling' anymore since the 448-lines high image is upscaled to a multiple of 224, not 448.

You are right, but the Genesis doesn't do 480p at all!
That is why we can always treat 480i signal as 240p, and this is why this "hack" method works for SNES, PS1 and Saturn cores because there is no 448/480 progressive resolutions in these cores.

Retroarch does not truncate the 448i content to 224p, and does not loose lines, this is a miss-understanding.
You can show high resolutions perfectly fine with 1x=224p, there is no loss of resolution.
As you said, the only side effect of this "hack" is misaligned/compressed scanlines even with Integer-Scaling with 448i content.

**Comment by ekeeke** [comment]
>It does handle H/V scaling independently.
There are a lot of final scaling options to choose from in retroarch including custom ratio.
I meant

I misunderstood then. I thought your initial issue was that it didn't scaled properly horizontally but it seems it was only a problem vertically.

>No, shaders don't receive the base at all, they only use the buffer.

Then how do they know they have to deinterlace the buffer content? By checking if the buffer height is above a specific value I guess ?

>The base is only for retroarch final scaling, and it doesn't know the frame buffer.
What does the shader output then? A 320x448 image ? Something else ? Again, if it's anything higher than 224 lines, then doing integer scaling with 224 as base height on this output would not be integer scaling.

>You are right, but the Genesis doesn't do 480p at all!
That is why we can always treat 480i signal as 240p, and this is why this "hack" method works for SNES, PS1 and Saturn cores because there is no 448/480 progressive resolutions in these cores.

Except that in that particular case (double field interlaced) the core actually outputs a 448p signal, made of 224 lines from current frame (field) and 224 lines from previous ones. Your issue is not the consequence of a misuse of interlacing by the core, it's a limitation of what resolutions can be achieved vertically with integer scaling : it's more or less like saying 224p do not fit enough of a 960p screen so the core should report 240 as base height although it only renders 224 lines.

>Retroarch does not truncate the 448i content to 224p, and does not loose lines, this is a miss-understanding.

Never said it was losing lines but you said earlier the de-interlacing shader was displaying first even lines then odd lines so obviously only 224 of those 448 lines are output on a given frame (at 60 fps) and the others are discarded (eventually displayed on next frame but then it means every two frames output by the core is lost). Or that's not what you meant? I would assume the CRT shader takes only odd or even lines then recreates the blanked lines in between, thus giving the illusion of interlaced display on a HD screen.

>As you said, the only side effect of this "hack" is misaligned/compressed scanlines even with Integer-Scaling with 448i content, but this is efficiently fixed by a simple shader that does x5+bilinear filtering.

It's a hack because it defeats the purpose of integer scaling, by allowing to use non-integer upscaling ratio.

**Comment by James-F2** [comment]
> Then how do they know they have to deinterlace the buffer content? By checking if the buffer height is above a specific value I guess ?

I assume retroarch detects it from the interlaced signal itself some way.
Even without shaders, the signal looks interlaced in horizontal motion.
So there IS a trigger/switch that tells retroarch the content is interlaced.
https://s13.postimg.org/urcz2c1zb/stock_gpgx_interlaced_no_shaders.png

> Your issue is not the consequence of a misuse of interlacing by the core, it's a limitation of what resolutions can be achieved vertically with integer scaling

Exactly.
I hope you don't see this as selfish act of trying to fix it for myself, but as a plea from you to conform GPGX to other cores.
There is a reason other cores behave as they do, they are not randomly behave the same.

> I would assume the CRT shader takes only odd or even lines then recreates the blanked lines in between

Absolutely not, it is not a simple line doubler.
It uses all the Odd and Even fields and displays them according to a specific algorithm that requires a high resolution screen for the final output.
The shader reads the **final windows/screen size** which created by retroarch using the **_base_ + _Aspect Ratio_ + _Integer Scaling_** and only then outputs the final image.
This means every time the window size changed the shader recalculates the output.

**Comment by ekeeke** [comment]
There is no way to tell explicitely retroarch the buffer is interlaced from the core it must be triggered using the buffer height. The image you posted looks wrongly interlaced to me.

Also, I did not say CRT shader was a simple line doubler, you were the one saying it would de-interlace the buffer content and alternativately display odd and even fields so I assumed it would pick apart odd and even lines from the core framebuffer and render them in two consecutive frames. Again, isn'it the case ? What would uou mean by de-interlacing either ? I am curious, do you know exactly what that shader does with framebuffer content and what it does ouput (as in number of pixels lines) ? By recreating the blanked lines, I meant recreating the gap which exist between lines on a given field for interlaced display.

**Comment by James-F2** [comment]
> so I assumed it would pick apart odd and even lines from the core framebuffer and render them in two consecutive frames. Again, isn'it the case ?

Yes, I think so.

> There is no way to tell explicitely retroarch the buffer is interlaced from the core it must be triggered using the buffer height.

Are you sure it is triggered by height?
The double-file output from GPGX is 448p signal, or 224 odd/even signal?

Do you not have Retroarch to test?
Please try CRT-Royale shader along with "240p Suite" for Genesis and pause (P button) to see the Blank lines (Scanlines).
"D:\RetroArch\shaders\shaders_cg\cgp\crt-royale-kurozumi.cgp"

With CRT-Royale shader:
In motion interlaced content looks complete without Scanlines (Blank lines), but when paused (or printscreen) it looks like regular 224p content with Scanlines.
https://s13.postimg.org/ysynlrtyf/CRT_Royale_Interlaced_content.png

**Comment by ekeeke** [comment]
As already explained in my previous posts, when emulated Genesis VDP is set to interlaced, GPGX double field output is 448p at 60hz, it contains both odd and even lines. In single field mode, it outputs only 224 lines at 60 Hz (like the original VDP does) and Retroarch sees it as normal 224p content, which cause screen shaking I think since consecutive frames (fields) are supposed to be interlaced by the frontend (my standalone Wii port for example handles this correctly and output an interlaced video signal just like original hardware).

My crappy old laptop does not support those shaders I think and I don't really use or test retroarch anyway but looking at your picture, I would guess that the image rendered by the shader has an height which is a multiple of 224 lines (at least 3x I would say, with the gap being one of these group of lines), which is the reason it only works fine for some resolutions with integer scalng and base height of 224.

**Comment by James-F2** [comment]
Anyway, I do not see a reason why not implement the following command: **info->geometry.base_height = bitmap.viewport.h + (bitmap.viewport.y * 2)** permanently in retroarch port only.
It fixes more than it breaks.

**Comment by ekeeke** [comment]
It is now done in https://github.com/ekeeke/Genesis-Plus-GX/commit/3463f2f724719d2976fa04340775927d0d8a49a9

I prefered yo be sure it had no impact on other things first but it seems we can assume base height/widrh refers to the TV display size and not necessary the core output size.

**Comment by James-F2** [comment]
> we can assume base height/widrh refers to the TV display size and not necessary the core output size.

Exactly.

Thank you and happy new year!
