### ISSUE TITLE
[libretro] window size reset every time you load ROM

### ISSUE THREAD

**Issue by eugene-s-nesdev** [ekeeke/Genesis-Plus-GX#205]
Bug description, example:

1) Open RetroArch in window mode (i.e 2x)
2) Load genesis_plus_gx core, then load NTSC ROM.

Window size will wrong until you force switch "Auto" to "NTSC PAR"
If you already had "NTSC PAR" in core options, you need switch it to PAL PAR and back.
Another solution is switch to fullscreen (F) and return back to window-mode.
Same issue with PAL PAR and PAL ROMs.

Window size reset every time you load ROM.
This issue appears only with genesis_plus_gx core

**Comment by ekeeke** [comment]
What do you mean exacyly by "wrong aspect ratio and window size" ?

**Comment by eugene-s-nesdev** [comment]
[winsize.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/1610164/winsize.zip)
step1.png = window size after you load ROM
step2.png = correct window size (after you recheck aspect ratio, or switch between win->fullscreen->win)
tested on NTSC PAR

**Comment by ekeeke** [comment]
Does not happen to me. Is this a new issue after you updated the core or retroarch ? It seems like RETRO_ENVIRONMENT_SET_GEOMETRY does not change window size as it should. Can you try an older version of retroarch as they might have changed something on that regard ?

**Comment by eugene-s-nesdev** [comment]
Core is lastest. RetroArch is 1.7.0 stable. It happens both on SDL2 and GDI video_driver, but i can test on GL too

**Comment by ekeeke** [comment]
That does not answer my questions: did it always happened to you and does it happen with older versions of retroarch ? This looks like a quite noticeable issue and it would be surpriding nobody had noticed it before. I know dynamic core video size change like this emulator does can be picky with Retroarch.

**Comment by eugene-s-nesdev** [comment]
I will test it on older versions. It always happened, but i use recent versions of RA.
Here is verbose log (start RA in window mode -> load ROM -> switch to fullscreen -> go back windowed)
[verbose.txt](https://github.com/ekeeke/Genesis-Plus-GX/files/1610185/verbose.txt)

**Comment by eugene-s-nesdev** [comment]
P.S. same issue appears on another physical desktop (i7-2600k /  IntelGMA HD3000 / Win7x64 / RetroArch 1.6.7 on SDL2, GDI, D3D and GL drivers).
RetroArch earlier than 1.6.7 is unavailable here (only apple, btw):
https://buildbot.libretro.com/stable/

**Comment by ekeeke** [comment]
Yes, looking at the log, windows remains stuck to 586x384 (which corresponds to twice the core-reported base height on core reset i.e 192 lines) but do not get updated when SET_GEOMETRY is used by the core to update the video base height (to 224 lines). You should ask retroarch devs if this is something that is expected or was changed and if there is a way to bypass that through retroarch settings because you are the first person reporting this to me and I personally never noticed such thing.

Also, the reason it does not occur with other cores is probably that they don't use dynamic video height change but since Mega Drive system could switch between several video heights during game execution (and all MD games switch from 192 lines output to 224 lines output on startup), we are forced to do so. See also this discussion refering to dynamic video height change in retroarch using libretro API: https://github.com/ekeeke/Genesis-Plus-GX/commit/693ce4d78fd832981eb1efb9207c532e9325d4de#diff-7aa14b06c2301aaaddb7e9983d2af13e

When switching between fullscreen and windowed mode or when changing video related core settings, video driver is reseted (by retroarch itself in first case or by the core calling libretro SET_SYSTEM_AV_INFO callback in second cas) which explain why the window size is correct in these cases.

**Comment by eugene-s-nesdev** [comment]
RetroWertz wrote:
>the way the core is layed-out, i think another call to
RETRO_ENVIRONMENT_SET_SYSTEM_AV_INFO or RETRO_ENVIRONMENT_SET_GEOMETRY is
what you need during the 1st loop of retro_run. in any case this issue
should be in the cores section as these adjustments are done in core rather
than in retroarch.

**Comment by ekeeke** [comment]
Yes, I actually re-checked with the Retroarch version I use and indeed the window size is locked by the first base width/height reported after loading content and is not updated by SET_GEOMETRY, not sure why I didn't noticed earlier (...and why nobody else reported this in 2 years).
Calling SET_SYSTEM_AV_INFO after the first frame might not be enough depending on when games actually switch to desired vertical resolution so a better solution might be to call it anytime video height is changed like it was initially done in commit linked above, and leave SET_GEOMETRY for video width changes (which will always scale to window width to respect desired display aspect ratio) .
Another alternative without changing code change is for end-users to leave top/bottom borders enabled in core settings as it will fix the video height to 240.
null

**Comment by eugene-s-nesdev** [comment]
So, can you confirm this issue is real?

BTW, Can you please add 4:3 aspect ratio to genesisplusgx core options?
There is some reasons fo it.
Many NES cores have internal aspect ratio selector (Auto, NTSC, PAL, 4:3) 
Retroarch itself can do 4:3 (Settings->Video->Aspect ratio), but best way to keep it "Core Provided" all the time.

For example you like 4:3 for genesis, but need to switch between GB, GBA and Genesis.
So, you're need switch everytime between "4:3" and "core provided".

**Comment by ekeeke** [comment]
>So, can you confirm this issue is real?

Yes, I was persuaded it wasn't the case but I had some time to test it again and windows height is indeed locked to a multiple of 192 after ROM load. I will  try to push a quick fix when I got some time unless someone else submit a pull request.

>Can you please add 4:3 aspect ratio to genesisplusgx core options?

 I could but I don't really like arbitrary made-up aspect ratio like 4:3 since they don't really originate from anything and are not related to real output display aspect ratio. Indeed, Retroarch will only use this to upscale the image pixel width in regard to image pixel height, but completely ignore the fact that emulated system and host platform has likely quite different PAR (pixel aspect ratio). 

Core-provided "NTSC" aspect ratio is therefore calculated using exact Genesis dot rate and active display size as inputs but it is also adjusted assuming NTSC standard square-pixel output (13.5 MHz * 10 / 11) for Retroarch to keep output DAR accurate. The core provided value is actually quite close to 4:3 for Genesis games (1.31 instead of 1.33) but if your output is not using square pixels but rather analog TV standard pixels (usually 13.5 MHz dot clock), this will indeed result in less accurate display aspect ratio (with the width being a little bit narrower than it should).

The correct aspect ratio value to provide in your case to match exactly Genesis TV output would theoretically be 1.31 * 11 / 10 = 1.44 though, not 1.33: I guess you could test it with your CRT TV if Retroarch let you configure custom aspect ratio value, that should normally result in video width being stretched to a multiple of 644 pixels in case of 240p/480i output (instead of only 598 pixels with 4:3 and 586 pixels with core-provided NTSC aspect ratio), which is the value I use in my standalone Wii port (and which provide very close result when comparing both Wii and Megadrive outputs on same CRT TV).

**Comment by eugene-s-nesdev** [comment]
TwinAphex answered too:
https://github.com/libretro/RetroArch/issues/6075
