### ISSUE TITLE
[libretro] Windows cursor in foreground when aspect ratio is not set to "auto"

### ISSUE THREAD

**Issue by lones710** [ekeeke/Genesis-Plus-GX#206]
When launching a game with the following option set:
genesis_plus_gx_aspect_ratio = "NTSC PAR"
or
genesis_plus_gx_aspect_ratio = "PAL PAR"
the windows cursor will be visible ontop of the emulator.
This behaviour does not occur when the aspect ratio is set to "auto".
The bug occurs with the video driver set to "gl". I could not test it with "vulkan" because of the [nvidia black screen vulkan bug](https://github.com/libretro/RetroArch/issues/5558) retroarch is having a hard time with right now.

Thank you for your amazing work on Genesis Plus GX, ekeeke. Used it for years on my Wii and now on my PC.

**Comment by ekeeke** [comment]
Aspect ratio setting only forces the aspect ratio value reported to retroarch independently of the game region but aspect ratio value reported with AUTO is either NTSC or PAL value so I don't see how only the two latter settings would cause an issue and not the former.

Anyway, window cursor is not controlled by the libretro core but the frontend (retroarch) so it's hardly an issue caused by the core (at least I don't see why it would).

**Comment by lones710** [comment]
How can I investigate this bug further? The "mesen" core has the same bug by the way. I will try to investigate log files etc. to determine if the core is the issue or retroarch itself. thank you for your time

**Comment by ekeeke** [comment]
I would suggest reporting that bug to retroarch with as many details as possible and explain it happens with at least two cores so it didn't get discarded too fast as a core issue and they can either identify this as a retroarch bug under specific condition or something those cores are not correctly doing. 
As for GPGX, this option does not nothing special but changing eventually the aspect ratio  reported by the core and has been like this since 2015.



null
