### ISSUE TITLE
Sonic cd freezing between levels again (Black Screen)

### ISSUE THREAD

**Issue by joepogo** [ekeeke/Genesis-Plus-GX#209]
Hey eke, looks like this problem is rearing it's head again. Most noticeably on the last level on act 3 and also on random stages ending on act 3. 

It just blackscreens. I am using the version 2.00 bios if it helps and the image is in bin/cue. If you would like my savestate please let me know. :) It could be, but i dont think it is something on my end. 

https://bitbucket.org/eke/genesis-plus-gx/issues/230/sonic-cd-sometime-freezes-when-loading

EDIT**

Currently about to start the third run. 

1st run = Black screen on next to last level trying to load the next after beating the metal sonic after the race

2nd run = No issues with black screens or savestates, odd. 

3rd run = currently testing. 

Can anyone else confirm the black screen issues?

**Comment by ekeeke** [comment]
What port / version are you using ?  What version was working fine for you ? There haven't been any changes to Sega CD emulation code for more than a year so it's strange nobody else has reported this issue yet. That old issue was caused by missing cd audio emulation and incorrect audio tracks length reporting from what I remember so verify your game is fine. Also try with different BIOS to see if that still happens and upload your cue file here for inspection.

**Comment by joepogo** [comment]
Hey eke, sorry for the late reply. Yes, i think i might have been mistaken. I tried it on the current wii version and tested the xbox port as well. On my second and third playthrough i had no issues at all. 

For now, ill close this as i think maybe it was a one time thing or something else weird. If it happens again, ill update accordingly.
