### ISSUE TITLE
Wii super famicom controller keeps pressing left. also emulator crashes when loading a game.

### ISSUE THREAD

**Issue by Errol24** [ekeeke/Genesis-Plus-GX#212]
I use a wii super famicom controller in my wii mote and now with the latest test version it somehow keeps pressing the dpad left the whole time like in the menu, but the wii classic controller pro just works fine. The last test version from december didnt got the problem with the controller. also when i load a game it crashes the emulator.

**Comment by ekeeke** [comment]
What test versions are you talking about exactly? There hasn't been any changes to Wii controller support since october (which only added wiiu control pad support) and I think people would have noticed if loading a game crashed the emulator. I don'tknow, try deleting the config.ini file in your SD card /genplus directory.

**Comment by Errol24** [comment]
For some reason the latest test version works now. I dont understand what happened before that caused the problems.
