### ISSUE TITLE
Mega CD Box Art Enhancement

### ISSUE THREAD

**Issue by DenverGamer** [ekeeke/Genesis-Plus-GX#214]
I have notice that in the "Mega CD" area to load games there is still a Mega Drive cart for the label image.  Would it be possible to remove the cart and be able to put box art scans there instead?  It looks like the dimensions would fit pretty good and look pretty slick.  For now I have been cropping box art to fit into the cart label graphic that is on that screen.  Here is an example of the box art:

![142896-snatcher-sega-cd-front-cover](https://user-images.githubusercontent.com/37034004/36942626-4bce7f4c-1f34-11e8-82c5-d24fb6f0eebc.jpg)

**Comment by ekeeke** [comment]
Already discussed here 

https://bitbucket.org/eke/genesis-plus-gx/issues/84/box-covers
https://bitbucket.org/eke/genesis-plus-gx/issues/344/sega-mega-cd-case-overlay

Yes it is possible but as always it's a matter of time and motivation for coding Wii stuff, which I kinda lack these days unfortunately. Source code is available so that other people with time and motivation can also contribute though.
