### ISSUE TITLE
(Question) difference between MAME YM3438

### ISSUE THREAD

**Issue by nikkoman** [ekeeke/Genesis-Plus-GX#216]
I don't know where else to contact you. I would like to know more about YM3438 sound emulation.

Currently there seem to be two MAME-based options for that chip: ASIC YM3438 and an "enhanced" YM3438 variation. I can't use nuked's versions since I'm using very low spec hardware (RPi).

I can't find any documentation about these new options. I'm also not sure if low-pass filter needs to be enabled for a sound closer to Model 1, since YM3438 supposedly featured a better DAC.

Any input would be greatly appreciated :)

**Comment by ekeeke** [comment]
ASIC version corresponds to the chip model used in later Model 1 consoles and most Model 2 consoles. It features the better (not discordes and less noisy) DAC output and full address decoding of status register (which causes slower music in Hellfire since it was developed for the discrete chip version) compared to discrete chip version.

Enhanced version has same "enhanced" features as ASIC version + full resolution DAC (14-bit instead of 9-bit in real hardware versions) + zero busy flag time (busy flag in CM status is only emulated for real hardware chip versions). It corresponds to an "idealized" version of the chip, like it is emulated in other Genesis emulators.

The low pass filter should be enable for accurate emulation of analog sound output (and disabled if you prefer the clear sound of pure digital emulation). Filtering ratio is configurable because it varies for each console models (also between model 1 consoles or between model 2 ones) so it's up to you to find a value that matches your own memory of accurate soins. Default value should correspond to Model 1 VA4 console.
''''
