### ISSUE TITLE
Wii version is broken

### ISSUE THREAD

**Issue by 47iscool** [ekeeke/Genesis-Plus-GX#218]
It doesnt matter what settings or MD rom I load the emulation crashes shortly after with white dots and lines on the screen. 

I'm using a normal Wii btw.

**Comment by ekeeke** [comment]
What version are you using ? What version were you using before it got "broken" ? There haven't been any change on Wii version since last december.

As usual, try to delete your config.ini file in /genplus directory to reset settings.

Also set render mode to "interlaced" instead of "original" before attempting to load a game with the broken version and post a screenshot of the crash screen.

**Comment by 47iscool** [comment]
I used the latest version. Also yes I use the original non-interlaced video mode. 

I will try the latest version with interlaced video. Though it might be a while before I can post a pic as internet use is limited for me.

**Comment by 47iscool** [comment]
I used the latest version. Also yes I use the original non-interlaced video mode. 

I will try the latest version with interlaced video. Though it might be a while before I can post a pic as internet use is limited for me.

**Comment by 47iscool** [comment]
Sorry, didn't mean to close the issue.

**Comment by 47iscool** [comment]
Screenshot here:
https://imgur.com/a/1AFnsrz

**Comment by ekeeke** [comment]
No idea what causes this but I can not reproduce it with latest build so it's likely an issue with your setup. Try to delete the config.ini file, format your SD Card or use another one.

**Comment by GB-CG** [comment]
@47iscool Are you using the .dol from https://github.com/ekeeke/Genesis-Plus-GX/commit/fee2bc8c28b66659ec3397f3582bf8128ce678a3? Just curious.

**Comment by vetzki** [comment]
I'm having the issue too with https://github.com/ekeeke/Genesis-Plus-GX/commit/fee2bc8c28b66659ec3397f3582bf8128ce678a3

tried video mode interlaced, original and progressive (only difference was original produced just a "black screen").
also removed config.ini

I'm using wii in 480p mode, dont know if this is causing the issue (deleted genesis-plus-gx after that. maybe test later if its help if I use 480i or 576i in wii settings)

**Comment by 47iscool** [comment]
I only use standard 480i NTSC. Don't have an HD TV.

**Comment by 47iscool** [comment]
@GB-CB As for your question, yes.
Same version.

**Comment by ekeeke** [comment]
You can still access and test previous builds through repository history

Previous build:
https://github.com/ekeeke/Genesis-Plus-GX/blob/902dc4c4c0fafaf520d5484505a7ed51ffe53624/builds/genplus_wii.dol

**Comment by ekeeke** [comment]
I recompiled the latest source from scratch since there indeed seems to be a problem with the latest dol file uploaded in this repository (I couldn't reproduce the reported issue but for some unknown reason this dol breaks SD access on my setup). 

Not sure what happened exactly but anyway, here is a clean build that should work

[genplus-gx-test-190618.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/2113297/genplus-gx-test-190618.zip)

Please report if this fixes your issue.

**Comment by GB-CG** [comment]
Yep that test .dol works for me. Thanks for checking it out.

**Comment by ekeeke** [comment]
Build updated in https://github.com/ekeeke/Genesis-Plus-GX/commit/326e30f3d8e706f360bffd6ceae476a491133d1c
