### ISSUE TITLE
Master System BIOS region error

### ISSUE THREAD

**Issue by BParks21** [ekeeke/Genesis-Plus-GX#219]
I have a real Japanese Master System bios tested and working in RetroArch and launched with the Genesis-Plus-GX core manually. It is also named correctly and placed in the system folder in RetoArch's directory. However, whenever i run a Japanese rom it selects my USA/E bios and causes an error preventing the game from playing. My other two region bios files are also confirmed working and named/placed in the correct manner. Here is a screenshot showing that the USA bios is loaded after launching a Japanese rom followed by the error screen. I've checked a dozen times and made sure each region bios file is named correctly and have launched each individually and directly. 
![screenshot 3](https://user-images.githubusercontent.com/12180630/40633918-767cfcbc-62c0-11e8-9f04-c306f6b5dd27.png)

**Comment by BParks21** [comment]
Here is proof each bios is functioning being launched directly with the bios files with the core.
![screenshot 1](https://user-images.githubusercontent.com/12180630/40633941-91616e78-62c0-11e8-8a94-aa01cd246baa.png)
![screenshot 2](https://user-images.githubusercontent.com/12180630/40633944-93e8ec0c-62c0-11e8-895e-bb38d07470dd.png)
![screenshot 4](https://user-images.githubusercontent.com/12180630/40633947-958f4b82-62c0-11e8-866a-e48c3063dca8.png)

**Comment by ekeeke** [comment]
1) For Master System games, the emulator uses a ROM database to determine (among other things) the game region but it is not complete as it more intended for games that only work under a specific configuration or need specific peripherals emulation. If the game is not in the database, the default region picked will be NTSC-U. You can see the full database here: https://github.com/ekeeke/Genesis-Plus-GX/blob/master/core/cart_hw/sms_cart.c#L79 to see if the Japanese game you are trying to load is listed here.

2) the console region (which determines the BIOS region) is set according to the "System region" core setting, it only matches detected game region when being set to "auto", otherwise it is forced to the selected region so make sure you did not set this setting to "ntsc-u". Alternatively, if you want to see the Japanese BIOS when lauching your games, you can force this option to "ntsc-j". It makes zero difference regarding the game compatibility.


If the game you are tryiong to load is not listed into the database, we could eventually add them and mark them as exclusive Japanese games. The reason the US BIOS hangs on error screen is that it checks the ROM header for a valid header with a valid region code but most Japanese games did not have any header at all (it is not a requirement for the Japanese BIOS). I guess another solution would also to detect the game region as Japanese if there is no valid ROM header or if the region code is not valid in ROM header.

**Comment by ekeeke** [comment]
BIOS_J.sms is loaded when the "system region" is forces to NTSC-J. I verified it and it works. Make sure BIOS_J.sms corresponds to the Japanese BIOS and not some other BIOS. Also note that the Japanese BIOS does not show anything when loaded with a game, it jumps straight to the game.
null

**Comment by BParks21** [comment]
Ok thank you for clarifying how everything is suppose to function.

**Comment by ekeeke** [comment]
Japanese game detection improved in https://github.com/ekeeke/Genesis-Plus-GX/commit/ae28f874021d92f0abd37113a56dcec89b570777

**Comment by BParks21** [comment]
Thanks!
