### ISSUE TITLE
Wii port - DSI Exception Ocurred when playing MD and loading a new Sega CD game

### ISSUE THREAD

**Issue by SieKensou** [ekeeke/Genesis-Plus-GX#223]
I noticed that if I play a MegaDrive game that is too much bigger than a normal one (like those hacks of Mortal Kombat) and then I load a Sega CD game, the emulator crashes with a DSI Exception Ocurred.
I think that can be happening because these kind of hacks uses some memory used for the Sega CD and it's not being cleared okay before change to Sega CD mode to load the game.

**Comment by ekeeke** [comment]
The RAM used to emulate Sega CD hardware is indeed shared with the cartridge ROM buffer area (which is limited to 8MB when Sega CD is emulated but can go up to 10 MB otherwise) but I normally take care of this when a CD game is loaded and Sega CD part is completely initialized.
Can you post a copy of the infos showed on that DSI screen (especially the linked address at the bottom) ?

null

**Comment by SieKensou** [comment]
Yes, sure, here is the picture of the error:
![genplusgx_bug1](https://user-images.githubusercontent.com/28622717/41728355-ee9e77a2-7576-11e8-92f9-1e8a276b2e35.jpg)

**Comment by ekeeke** [comment]
Looks like an issue when loading a CHD image file after a large ROM file. I indeed forgot to always clear CHD data before loading a new CD game so this is certainly the problem here.

Can you test the dol below and confirm it does not crash anymore under such situation ?

[genplus-gx-test-210618.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/2125541/genplus-gx-test-210618.zip)

**Comment by SieKensou** [comment]
Yes, after various tests I can confirm that it doesn't crash.
