### ISSUE TITLE
Wii port- Sonic CD issue

### ISSUE THREAD

**Issue by DudeNin64** [ekeeke/Genesis-Plus-GX#227]
Each 1 to 2 minutes, there's a loud buzz while playing Sonic CD, I tried different BIOS, ISOs and USB drives, but no solution. Am i doing something wrong?

**Comment by ekeeke** [comment]
See https://bitbucket.org/eke/genesis-plus-gx/src/master/wiki/Frequently%20Asked%20Questions.md

Those are probably random access issue to your USB drive since it is read continuously by the emulator. Try with a fast SD card or make sure your USB drive is in USB2 mode and IOS58 is launched by homebrew (you can see loaded IOS in the emulator quit menu).
