### ISSUE TITLE
backporting libretro to upstream

### ISSUE THREAD

**Issue by retrotalker** [ekeeke/Genesis-Plus-GX#242]
Hi, I did a diff compare between libretro-master and upstream-master
- majority of changes are updated files to 2018 libretro/libretro-common
- msvc-2017 changes
- libretro/libretro.c has some stuff modified downstream (fast savestates for runahead latency, RETRO_VFS_FILE system, some misc stuff I don't get)
- outdated core files

I prefer to use upstream since it's always maintained and you consistently provide up-to-date releases for end-users. But I wasn't sure if it was useful pushing any of the libretro specific diffs up here, and thought maybe you could take a peek first?

Really, thanks a lot for putting so much quality effort into this project

**Comment by ekeeke** [comment]
I don't think it's automatically mergeable, there were changes in libretro fork to core files when run-ahead feature was added which I unfortunately can not approve upstream because they are too libretro-specific and not well implemented. If you manage to make a pull request, it will still be interesting to have a complete view of what differs between the repositories, but I won't accept it for aforementioned reasons.

**Comment by ekeeke** [comment]
There were some discussions here 
https://github.com/libretro/Genesis-Plus-GX/pull/140
then
https://github.com/libretro/Genesis-Plus-GX/pull/145

with some propositions for improvement (and upstream merging) but it was put on hold because I couldn't get a clear answer from Dwedit about why the second core running instance and "audio hard disable" were necessary for run-ahead feature to work.

To summarize, I was pretty much ok with state loading speed optimization and saved state content improvement (necessary to fix audio issues in run-ahead specific use case ) and would like to implement it myself in a cleaner/better way (there are for example some other VDP state fixes that libretro implementation might have missed) but didn't like the way optional "audio hard disabled" was hacked in various parts of the core, so wanted to be sure if it really was necessary before thinking about it.

**Comment by retrotalker** [comment]
Audio hard disable was heavily discussed in the mainline snes9x area. Found it:


https://github.com/snes9xgit/snes9x/pull/352
- (#2) dwedit says it was (mostly) a bad idea altogether


- (later down) bearoso makes an official decision to not include it

"The "hard audio disable" option is not going in. Simply stopping the DSP like that is a bad idea. I'm surprised it works--and the reason is I suspect some aspect of the runahead code makes it moot."


The secondary core running is definitely not necessary for runahead to work. I never use it because it caused glitchy video/audio at some few random times. I think it was created mainly for getting fullspeed on low-power devices (snes classic, raspberry pi).


I'm going to try breaking apart some of the diffs and submit sometime this week. From what I've tracked across several libretro projects, many edits shouldn't affect compiling at all.

**Comment by ekeeke** [comment]
>I think it was created mainly for getting fullspeed on low-power devices (snes classic, raspberry pi).

I don't think so because having a 2nd instance of the core running (even with sound chips output disabled) will always be much slower than having just one core tuning. I think it was added as a hack in some cores to fix sound issues when using run-ahead feature which was caused by  existing savestates limitations (which can be fine for asynchronous state loading but not enough for continuous state forward/rewind like run-ahead is doing).

That's why I also think it's not needed but I wanted confirmation from Dwedit to be sure.

**Comment by retrotalker** [comment]
^ That does makes total sense to me now. Hopefully @Dwedit will drop by.

Thanks again!

**Comment by retrotalker** [comment]
I compiled the basic changes here:
https://github.com/retrotalker/Genesis-Plus-GX/tree/sync1


appveyor msvc2017 keeps giving me corrupted run-time builds with sync1 or master so I left it up there for now. :|

**Comment by ekeeke** [comment]
maybe it's related to this commit ?
https://github.com/ekeeke/Genesis-Plus-GX/commit/484e05f5b8e8ce03992ee2ef1c9f8b080b495e4b

It was merged  without any check since I don't use MSVC myself

**Comment by ekeeke** [comment]
>I guess that didn't happen unfortunately?
As stated above, the initial discussion (see aforementioned link) was put on hold since I coudn't get clear answer about these 'hard-audio disable' and '2nd core instance running' things and if they really were needed for run-ahead.

>just telling us we cannot have this is not a solution obviously, 
I never said such thing, as said above and in previous discussion link, I am fine with any savestate optimization and improvement needed to get run-ahead feature works properly (and I don't care about any modification you make to libretro-specific files), I am just trying to keep core files in a clean state and I am opposed to the audio_hard_disabled setting which got hacked in many core emulation source files (apparently, snes9x devs had similar position, as seen in above snes9x github link posted by retrotalker)

>the only condition I have is that performance with runahead in the libretro core should not suffer as a result.
Run-ahead performance is conditioned by savestate loading code optimization, which I am fine with (and should be able to optimize a bit more than Dwedit solution, with a less invasive solution as well).
Afaik, second core run instance with audio hard disabled does not improve performance, on the contrary, hence why I was questioning its usefulness.

That said, anything that optimize the core WITHOUT sacrificing accuracy is acceptable, but at some point,  people should accept to use another (less accurate / faster) emulator if they can not use run-ahead feature on their slow machine at playable speed (it should be made clear to users that this feature is quite beefy as it runs much more frames than normally needed and continuously load/save full emulator state)

**Comment by retrotalker** [comment]
master: used a different appveyor script using msbuild sln and it works now. So some conflict with appveyor using make directly creates some runtime crashes (tries to run SVP and other oddball things).

sync1: going to examine modifying upstream sln for new libretro changes or try pushing downstream one.

**Comment by ekeeke** [comment]
> would it be fine to use the current libretro core then for that purpose and have a second upstream friendly Genesis Plus GX core?
I don't think it would be good idea, as it will become hard to distinguish between legit core issues and issues caused by hacks added by someone else and I surely don't want to deal with issue reports on something I don't maintain myself.

**Comment by retrotalker** [comment]
https://github.com/ekeeke/Genesis-Plus-GX/pull/243
- This should have all the safe, agreed changes. Compiles with appveyor msvc 2017 (x86, x64) and binaries tested.

https://github.com/retrotalker/Genesis-Plus-GX/pull/9
- This is what the remaining libretro edits look like, minus libflac.

**Comment by retrotalker** [comment]
Found this info about secondary core:
https://retropie.org.uk/forum/topic/17438/new-emulation-method-to-eliminate-input-lag

"After experimenting with this a little bit more in lr-fceumm, I found I was able to successfully set the run-ahead frames as high as '5' without affecting performance. Previously I saw stuttering issues past '2' on some titles, but after reading more about the feature, it was indicated that audio stuttering can occur without setting a second instance of RetroArch. It's been assumed that the Pi couldn't handle this, but once enabled, the stuttering went away completely and allowed for a much higher run-ahead frame count. Granted, most titles don't need anything more than a setting of '2' and giving those games a setting higher than they need results in some interesting character behavior, but it shows that a run-ahead of 1-5 frames is not out of the question when needed for this core at the very least."


But I was also wondering. Since secondary core can be unstable sometimes for whatever reason
https://github.com/libretro/snes9x/issues/171

and Genesis Plus GX supports different frontends without runahead (Bizhawk / OpenEmu + NGC / Wii)

would it make more sense for the wizard (ekeeke) to "re-invent" runahead for GPGX - having a new latency core option?

Then you would have complete freedom to do it via your unique talented ways, ignoring libretro communication. And your other base users will benefit from this helpful feature (ngc, wii).

**Comment by ekeeke** [comment]
I don't know what is the point of speculating or arguing about this since it does not make any sense anyway: run-ahead mechanism is entirely handled by the frontend (only things the core does is providing a way to accurately save/load state and to render frames with video - and eventually audio - emulation skipped). Let me make it clear if it wasn't already, all I care about is the core and I don't have any intention to work on anything else or re-implement retroarch features (where ? in a new frontend that does not exist ?), this does not interest me.

**Comment by retrotalker** [comment]
Sorry sorry! Didn't want to stir any trouble or make someone madder.

*shuts up and runs away *

**Comment by twinaphex** [comment]
No problem, there is no issue as far as I am concerned.  I was not arguing either.

Guess I will leave this up to @Dwedit and @ekeeke to sort out if there is any interest.

**Comment by retrotalker** [comment]
Dropping some comments from the snes9x project.


A bug was posted that runahead breaks a game.
- second instance off = uses fast savestates. boot bsod.
- second instance on = game works because this doesn't use savestates.


Some average benchmarks of Kirby's Dream Land 3 run an old core2 with latest master
- runahead off = 187-190
- secondary off = 109
- secondary on = 121


And there's some fork called Bright by @kps501, which runs its own version of runahead in the libretro.cpp file and seems to avoid hacking the core.
- runahead off = 181
- secondary off = 98
- secondary on = 112
- internal = 116

(So I'm guessing the libretro api overhead of savestates makes it slower. But doing it internally without relying on the frontend posts a tiny gain I guess)

*goes back into hiding*

**Comment by ekeeke** [comment]
Yes, like I said, second core instance was likely added to fix potential issues in core savestates (which again might be good enough when  you load a state to go backward and start over but cause issues when you start saving/loading them continuously every N frames and expect emulated audio/video to be perfectly uninterrupted).

If that is indeed the case for Genesis Plus GX, I prefer fixing those savestate issues rather than modifying the core to be able to run a second instance with audio emulation disabled.
