### ISSUE TITLE
(Request) Standalone version

### ISSUE THREAD

**Issue by RinMaru** [ekeeke/Genesis-Plus-GX#246]
I really like this emu but find it a bit odd its only on retroarch and I cant stand the using Retroarch will there be a standalone version at one point?

**Comment by ekeeke** [comment]
There is no standalone windows version because this emulator started as a Wii/GameCube port of Genesis Plus then became an improved port with compatibility/accuracy/features enhancement. There is a basic sdl port to run on windows but I have no plan to make anything else at this point since my time to work on this emulator is very limited by now. The source is available for anyone to do it though.
