### ISSUE TITLE
Gauntlet IV MultiTap Not Working

### ISSUE THREAD

**Issue by newoski** [ekeeke/Genesis-Plus-GX#255]
I'm on the latest core and I'm using the same config settings I've previously used:

input_libretro_device_p1 = "1793"
input_libretro_device_p1 = "1793"

P1, P2, P3 all work, but P4 doesn't respond.

**Comment by newoski** [comment]
(I've tested a bunch of other games that use the same combo of 1793/1793 and they all work. Unless I have the combo wrong, there's a bug here)

**Comment by ekeeke** [comment]
No idea what these settings mean but this is not something used by the core.

Anyway, multitap works fine with Gauntlet 4 and there is nothing wrong with the emulator, it's just that if you the game detects a Teamplayer multitap in port 1 but also a gamepad in port 2, the game will use the gamepad in port 2 to control player 4, not the 4th controller of the Teamplayer. I don't know why but that's the way the game was designed (surely they did not thought people would connect 5 controllers to their console).

So you have to either leave port 2 device type set to "Joypad None" or bind your 4th controller to player 5 in retroarch (note that it does not help that retroarch interface actually confuses emulated console physical ports with "players" so port 2 device type is actually player 2 device type and any device types set to player 3,4,etc is ignored by the core).

Another solution is to use 4-way play adapter in port 1 ("player 1" in retroarch ) instead since that game supports both types of multitaps and then retroarch P4 binded controller with normally be used as 4th player in the game (on the console, 4-wayplay adapter connects to both ports so only 4 controllers can be seen by the console)

**Comment by newoski** [comment]
Thank you!! Your knowledge of this stuff remains truly humbling
