### ISSUE TITLE
Video frequently/randomly freezes on Cool Spot

### ISSUE THREAD

**Issue by foahchon** [ekeeke/Genesis-Plus-GX#261]
In RetroArch, on latest build (updated via core uploader today), video on Cool Spot frequently freezes temporarily. Audio doesn't seem to be affected, and inputs seem to be processed while image is frozen. Haven't identified any other games where this happens. Doesn't happen on PicoDrive. Thanks.

**Update**

Problem seems to be caused by RetroArch's RunAhead feature. Specifically, if I disable using a second instance, the problem goes away.

**Comment by ekeeke** [comment]
This is a retroarch or libretto specific issue then, not a core issue, I can not help you.

**Comment by Azurfel** [comment]
This appears to effect games made by the Shiny Entertainment crew in general (Global Gladiators, Aladdin, Earthworm Jim, etc.).

I've noticed that it most frequently seems to occur when left or right + the jump button are held, with the screen unfreezing when one of those inputs is released.

I suspect this may be related to the non-determistic savestate issues @SergioMartin86 noted [https://github.com/ekeeke/Genesis-Plus-GX/pull/549](here) and elsewhere, given that savestates need to be deterministic for runahead to work perfectly.

`gamepad` not being included in the state may be the specific culprit in this instance, since, by it's nature, runahead requires loading states mid gameplay while inputs are active.
