### ISSUE TITLE
Request: Option for auto region detection to use rom name

### ISSUE THREAD

**Issue by retrorepair** [ekeeke/Genesis-Plus-GX#262]
I was wondering how trivial it'd be to add an option to override header region detection to use the (region) tag in the rom file name?

A lot of roms are either (world) or (usa, europe) and auto detection will always default to ntsc in these cases.

I have all my roms in region folders and use CRT switching and it's a bit of a pain that the majority of games default to ntsc.

I imagine I wouldn't be the only one in this situation?

**Comment by ekeeke** [comment]
> I was wondering how trivial it'd be to add an option to override header region detection to use the (region) tag in the rom file name?

That wouldn't be a good idea because there is no standard about this for ROM file names and forcing a standard for file naming in the emulator is not good either. What would be the correct tag for PAL ? "(europe)" ? "(e)" ? "(pal)" ?

> A lot of roms are either (world) or (usa, europe) and auto detection will always default to ntsc in these cases.

ROMs like this generally have "(World)" or "(usa,europe)" in their filename (at least in no-intro or goodgen sets) so I don't see how it would solve your issue ?

> I have all my roms in region folders and use CRT switching and it's a bit of a pain that the majority of games default to ntsc.

Why would you put worldwide game version in a specific region anyway ? This looks like a pain you created yourself for no other reason than wanting to play games in PAL mode by default. A much better solution in this case would be to either use retroarch game-specific configuration feature (to force region for games based on where you "classified" them) or to add an option in the emulator to let the user select default region for auto when multiple regions are supported, like what is done in Kega Fusion I think for example :"AUTO (E->U->J)", "AUTO (U->J->E)", etc

>I imagine I wouldn't be the only one in this situation?
Honestly, I don't know why would anyone want to play games that were designed to be played at 60Hz at the slower PAL speed, with crunched aspect ratio, etc... but I guess some people are really deep in the nostalgia thing and want games to run as they remember on their original PAL console. I personally don't, even if I grew up in PAL world.

**Comment by retrorepair** [comment]
I meant the rom name and yes, I would have imagined (e), (europe) and (pal) to be the tags it would pay attention to. I've already renamed my roms as I thought this was potentially how region was chosen.

I was proposing this as an option not the default but ok. Guess I have a thousand or so configs to create 😖

I do like playing games in their original (at least what the limitations of the pal standard forced) format. It is a lot to do with nostalgia but I feel like it's a lot to do with preservation too. I know it's an unpopular opinion but I'm sure a lot of people have already forgotten what it was like to run these games in 50hz.

It's not just PAL games, it will default to NTSC USA so none of the roms will load in japanese by default either.

**Comment by ekeeke** [comment]
>I meant the rom name and yes, I would have imagined (e), (europe) and (pal) to be the tags it would pay attention to. I've already renamed my roms as I thought this was potentially how region was chosen.

When AUTO is selected, region is chosen according to the tags in ROM header.

> I was proposing this as an option not the default but ok. Guess I have a thousand or so configs to create 😖
Well, you already renamed(manually ?) a thousand of ROM files without knowing if this would have any effect on emulators so...
I'm sure the process of creating game-specific core config files can be automated

>I do like playing games in their original (at least what the limitations of the pal standard forced) format. It is a lot to do with nostalgia but I feel like it's a lot to do with preservation too. I know it's an unpopular opinion but I'm sure a lot of people have already forgotten what it was like to run these games in 50hz.

The thing is, the original format for those games was 60hz, not 50hz. They were developed to be played worldwide and were meant to be played at 60Hz, not 50hz. The fact they are running slower on PAL consoles is a side effect of the console speed.

It's true that some PAL exclusive games were designed to play at 50hz but this is correctly handled by the emulator through the AUTO region setting. If you want to play UE or UJE versions at PAL speed, you can force the region to PAL in core settings, it's not complicated.

>It's not just PAL games, it will default to NTSC USA so none of the roms will load in japanese by default either.
Again, that's only the case for games that were released worldwide. It would be incorrect to rename these files as "japan" or "pal" exclusives as this is not what they are. If you want to emulate a NTSC-J or PAL console, you can force the console region in core settings but by default, the emulator will be emulated a NTSC-U console if a game with no region restriction is loaded.

**Comment by retrorepair** [comment]
I know what your saying, but pal consoles played these games at 50hz and I think that should be preserved, which it is.

I managed to get my .opt files together, was quite easy in the end with a copy and rename batch script.
