### ISSUE TITLE
The spaceship in Phantasy Star I sounds choppy (Retroarch core)

### ISSUE THREAD

**Issue by FeRcHuLeS** [ekeeke/Genesis-Plus-GX#263]
It sounds choppy got the travel from Palma to Motavia (first travel in game) the configuration is:
Master System FM YM2413  auto
Mega Drive/Genesis FM        nuked (ym3438)
Sound Output                       stereo
Audio Filter                            low-pass
Low-pass filter%                    40

**Comment by ekeeke** [comment]
I don't know what 'choppy' means. Can you provide a video / audio capture?

Also make sure you don't have retroarch options like runahead or rewind activated.

Lastly, try with YM2413 set to OFF or ON to see if it changes anything

**Comment by FeRcHuLeS** [comment]
I meant the sound of spaceship's engine is not continuous how is supposed to be, it seems to sound fine with FM activated, besides the music in the dungeons sounds a bit strange (as some of the channels were off with FM set to auto), so try yourself, here it is a save the third slot (just in the spaceport).

**Comment by FeRcHuLeS** [comment]
The link (Edit post is not possible):
https://drive.google.com/open?id=1fKfzxKUGtpv8Yzt02xcSn5kr7-Pvgc5J

**Comment by ekeeke** [comment]
>I meant the sound of spaceship's engine is not continuous 
This is not a bug, this is just how the spaceship sounds in the Japanese version when FM unit is not  found and PSG sound is used instead. You can try the same ROM in Fusion emulator with YM2413 disabled in emulator options and it sounds just the same.

>how is supposed to be
It sounds differently in the Western version of the game, which is what you probably are used to (you can rename your srm file and use it with one of the non-Japanese ROM version and you will hear the difference).

>it seems to sound fine with FM activated,
Off course, it sounds different when YM2413 FM is forced ON, well, because it's using FM sound instead of PSG then, which are completely different sound chips producing different music. 

>(as some of the channels were off with FM set to auto),
Setting YM2413 FM to AUTO will act the same as setting it to OFF for this particular ROM and will force the game to use only PSG because it's an unofficial ROM which is not recognized in the emulator datacase (it's actually the latest SMS power translation patch applied to the Japanese ROM).
