### ISSUE TITLE
Hardball 95 SRAM issue

### ISSUE THREAD

**Issue by Dexter2341** [ekeeke/Genesis-Plus-GX#266]
I'm currently using the latest version of the emulator and when loading Hardball 95 a red screen appears and says Cartridge error message: SRAM failure press RESET to restart. Pressing reset just loads the same screen.

**Comment by ekeeke** [comment]
Indeed, this was a stupid bug introduced in this commit: https://github.com/ekeeke/Genesis-Plus-GX/commit/32079418a9c86caa7eb3ca62278df08bf9c0de69

This is now fixed by using the correct ROM size when checking SRAM start address, see https://github.com/ekeeke/Genesis-Plus-GX/commit/5f8156ef7239ba7358795db5bda32ee182e8ab2a
