### ISSUE TITLE
audio-related segfault on lakka-switch

### ISSUE THREAD

**Issue by plaidman** [ekeeke/Genesis-Plus-GX#275]
Hi,

I'm trying to get this core working with lakka-switch retroarch. Immediately after starting a game, I get a segfault. I've captured the gdb output here: [gdb log](https://pastebin.com/y9GD0WVi).

I'm using the standard make target with some externally defined compiler options. In case it has something to do with those compiler options, I've captured the compile log here: [compile log](https://pastebin.com/qXvx3Eut). As you can see it successfully compiles but again it fails when processing some audio data.

Please advise if there you have any suggestions on getting this to run. Thanks!

**Comment by ekeeke** [comment]
Try with run-ahead feature disabled or runahead with second core instance disabled.
The log seems to indicate a crash when writing resampled audio data to output soundbuffer so it might be a buffer overflow caused by that 'audio hard disable' feature hacked in the core forked by libretro (see https://github.com/libretro/Genesis-Plus-GX/blob/master/core/sound/blip_buf.c#L320).

Either ways, you will have to ask libretro devs about that as I am not responsible of this modified version and don't know anything about that lakka-switch retroarch port or what would make it special.

**Comment by plaidman** [comment]
Thank you for taking a second look at these logs. I will try to adjust these values to see if they can fix the issue. If not I'll escalate it to the libretro guys.

**Comment by ekeeke** [comment]
I noticed there are a few suspicious warnings in your build log when compiling blip_buffer.c so I suspect this is rather a compilation toolchain issue or a problem with compilation options used. Try removing  -Wno-psabi gcc option to see if more warnings are exposed regarding integer sizes .

**Comment by plaidman** [comment]
compiling without the -W option doesn't show any additional warnings for any of the files.

**Comment by plaidman** [comment]
We have confirmation that the core does work if compiled correctly. Someone using switch-ubuntu (same kernel as switch-lakka) apt-get'd retroarch, and sent me the .so file. I was able to load a game successfully in lakka using this .so file. I think I need to look into what compiler options are being used by apt to build this for switch-ubuntu. But I'm not sure if it'd help since it woudln't be cross-compiling at that point (which we do for lakka).

**Comment by plaidman** [comment]
I also confirmed that ALIGN_SND is not being set with our toolchain.

**Comment by plaidman** [comment]
further confirmed that we are getting into this branch of the if-else: https://github.com/libretro/Genesis-Plus-GX/blob/master/core/sound/blip_buf.c#L38. Does this confirm your theory number 2 above?

**Comment by ekeeke** [comment]
Indeed, yes, this confirms ULONG_MAX is a 64-bit value (this can also be verified by looking at  limits.h include file in your compilation environment).

Now you should verify the size of 'unsigned long' or 'fixed_t' variables (using a debugger or adding a retroarch log which prints the return of sizeof function). It should normally be set to 64-bit (8  bytes) by the compiler when -mabi=lp64 option is used (if it is still 32-bit as suspected this would indicate either a compiler bug or maybe another compiler option is required)

**Comment by plaidman** [comment]
`sizeof(fixed_t)` and `sizeof(unsigned long)` are both `8`

**Comment by ekeeke** [comment]
hmm, that's weird... maybe there is some incompatibility in blip buffer library when using 64-bit library :-/

can you build with -DBLIP_ASSERT compilation flag and see if there are any error assertion in blip functions during execution ?

The sample count value passed as parameter to blip_read_samples directly comes from the value returned by blip_samples_avail function after having called blip_end_frame function with a t value corresponding to clocks count per frame (to retrieve samples count per frame).
Since you verified that m->offset is 64-bit as expected, the other possibility for blip_samples_avail to return 0 is if m->factor is for some reason miscalculated.
The calculation is done here: https://github.com/libretro/Genesis-Plus-GX/blob/master/core/sound/blip_buf.c#L195
It corresponds to the number of samples per clock in fixed-point format (52 bits of precision when using 64-bit integers).

**Comment by plaidman** [comment]
I will try that. I also have a few other define flags to try suggested by some other switch devs: align_long, align_word and arm

**Comment by plaidman** [comment]
I tried with -DBLIP_ASSERT and the game played without sound.

As for the other define flags, none of them worked in any combination.

**Comment by plaidman** [comment]
BTW I'm more than happy to test with some code changes if you have any ideas to throw at me.

**Comment by ekeeke** [comment]
yes, blip_read_samples is safer (but slower) with -DBLIP_ASSERT and will check the value of count parameter, hence why you get not crash (but no sound since no samples are returned).

to better understanw why the number of available samples is 0, I would add the following function call in blip_buffer.c to output various internal parameters values then check retroarch log on execution: 
1) error("samplerate=%f,clock=%f,factor=%llu (%f), time_unit=%llu\n",sample_rate,clock_rate,m->factor,factor,time_unit) at the end of blip_set_rates function
2) error("offset=%llu, factor=%llu, time=%d\n",m->offset,m->factor,t) at the start of blip_end_frame function
3) error("offset=%llu, shift=%d\n",m->offset, time_bits) at the start of blip_samples_avail function

**Comment by plaidman** [comment]
1. `[libretro ERROR] samplerate=0.000000, clock=53693175.000000, factor=0 (0.000000), time_unit=4503599627370496`
2. `[libretro ERROR] offset=0, factor=0, time=896040`
3. `[libretro ERROR] offset=0, shift=52, avail=0`

**Comment by ekeeke** [comment]
Thanks. So the problem is not related to integer size but simply that the sample rate value passed as parameter is invalid. That's very weird, this value is normally passed by audio_init function which is called in libretro.c (https://github.com/libretro/Genesis-Plus-GX/blob/master/libretro/libretro.c#L2386) using a constant value equal to 44100 in libretro.c (https://github.com/libretro/Genesis-Plus-GX/blob/master/libretro/libretro.c#L181)

Can you add the following log in system.c and see what is reported:
 error("samplerate=%d (%f)\n", samplerate,samplerate) at the start of audio_set_rate function

**Comment by plaidman** [comment]
`[libretro ERROR] audio_set_rate samplerate=44100 (0.000000)` that's interesting.

**Comment by plaidman** [comment]
seems if I change the 2nd `samplerate` param to `samplerate * 1.0` it outputs probably what you're expecting to see `audio_set_rate samplerate=44100 (44100.000000)`

**Comment by plaidman** [comment]
but the int to float conversion producing 0 is weird. is that something that can be affected by toolchain?

**Comment by plaidman** [comment]
well I added `*1.0` to the samplerate param when calling blip_set_rates but I'm still getting segfaulted.
`[libretro ERROR] blip_set_rates samplerate=0.000000, clock=53693175.000000, factor=0 (0.000000), time_unit=4503599627370496`

**Comment by ekeeke** [comment]
> but the int to float conversion producing 0 is weird. is that something that can be affected by toolchain?

Either that or is a compiler option issue, this does not occur with any other ports AFAIK , including retroarch libnx port so this is definitively not an hardware or software issue.

Maybe try passing `(double)samplerate` as parameter ?

**Comment by funbars** [comment]
https://github.com/libretro/Genesis-Plus-GX/blob/master/core/sound/blip_buf.c#L195
```double factor = (double) time_unit * sample_rate / clock_rate;```

also??

**Comment by plaidman** [comment]
Well it turns out `-O2` was the culprit. I tried it with `-O0` and it works with sound. At least genesis does. I haven't tested other systems.

**Comment by ekeeke** [comment]
That's a compiler issue then, and I would strongly suggest fixing it (or at least reporting it): assembly code optimization is definitively useful for emulators (even on a relatively powerful system as the Switch) and  should not produce buggy code.

**Comment by dankcushions** [comment]
Was this issue ever logged with the compiler (GCC?). I had the same problem with aarch64 on raspberry pi 3, and the same -O0 change fixed it.

Compiled with gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1)
Happy to log this with gcc but I don't know how to word the report.

**Comment by plaidman** [comment]
I didn't report it.
