### ISSUE TITLE
How to build this?

### ISSUE THREAD

**Issue by xlar54** [ekeeke/Genesis-Plus-GX#276]
Make complains "no target specified and no makefiles"

**Comment by ekeeke** [comment]
how to build what ? for which platform exactly ?

**Comment by xlar54** [comment]
Windows pls.  Maybe Im misunderstanding this project as it was mentioned in
some other sites, but isnt this a Sega Genesis emulator?

**Comment by ekeeke** [comment]
Yes it is but only the Wii/Gamecube standalone port is maintained here (it was originally made for these platforms but since the emuation core sourcecode is very portable, it is used in other projects).

There is a very basic SDL port for windows but I don't think this is what uou are looking for as there is no user interface and it's mainly used by me to debug emulation core issues or as an example for people to make their own ports. If you want to use this emulator on Windows, you need to install Retroarch (https://www.libretro.com) which comes with a precompiled version of this emulator core (among many others as this is a multi-emulator frontend)

**Comment by xlar54** [comment]
Ok thank you.

Sent from Mail for Windows 10
