### ISSUE TITLE
Odd behavior with controller detection notification - exclusive to this core

### ISSUE THREAD

**Issue by klepp0906** [ekeeke/Genesis-Plus-GX#279]
So... weiiiird behavior ive spent an inordinate amount of time trying to track down.   Ive ultimately come to the conclusion, that its on your end not mine :P 

If i start a game directly through a shortcut on steam big picture mode, I get double popups for the controller.  Literally two at once, both saying the same thing.  (xinput player 0 detected or some such)

I figured it might be related to steam, so i moved to the pc, and started a game directly through RA - same result.   Double popups. 

I assumed it could be vpn related.  Closed, no bueno.  I figured it might be RA related, so i tried a different core.  Win! No double pop ups.  And another core, Win again!.   I figured perhaps it was content/system related, so instead of a genesis game, i started a game gear game.   Same thing, double pop up.

I did some digging and someone mentioned the auto detection causing issues, so i changed to the standard 3 button - unfortunately the result was the same.

Now this MAY be purely an aesthetic double popup, but I have noticed at times my controller will spam input.  Often when Im trying to change something in the menu it'll zoom up or down instead of clicking an entry at a time (as if it were spam pressed or held down).  Could be a completely separate issue, thats above my paygrade.

As a final measure, i tried with a steam controller, an xbox controller, and a ps controller.

all with the same result, only with the genesisplusgsx core.

**Comment by ekeeke** [comment]
>Double popups
Sorry but I have no idea what 'popups' you are talking about or what they are used for so I can not help you. The core is not responsible for this anyway, it has no way to open popups by itself and does not send that kind of message or has any idea about what 'xinput' is. Thid comes from the frontend (retroarch or whatever you are using) so you should rather first ask retroarch/libretro devs what cause these popups (from the message you get, it seems like an issue with the input drivers you are using).

>vpn related
Again, no idea what that means and how his would be related to emulation core. All the core does is implementing libretro API and sending emulated audio/video framebuffers to the frontend.

>someone mentioned the auto detection causing issues, 
Issues about what ? That again does not make any sense, auto-detection of controller type to emulate has no impact on anything but the core. Setting that option to auto only tells the core to look at ROM file extension and ROM header to choose between 2-buttons, 3-buttons or 6-buttons gamepad emulation instead of using a forced model.

>my controller will spam input. 
what does that mean? the core only reads the uniformised input state that the frontend send him through libretro API, if there is a problem with your controller inputs, this is an input driver issue, not a core issue

>. Often when Im trying to change something in the menu it'll zoom up or down instead of clicking an entry at a time (as if it were spam pressed or held down).

libretro cores have no control on frontend menu keys so it looks like a key mapping issue on the frontend side. Go seek some support on libretro/retroarch side for this.

>As a final measure, i tried with a steam controller, an xbox controller, and a ps controller
The controller you are using is transparent to the core, it is abstracted by the frontend input driver into a virtual 'retropad' so the core has no idea what real controller is being used.

>only with the genesisplusgsx core.
Afaik, this core implements the libretro API just fine and this is all that should be required from a libretro core. It also works fine without this kind of issue for many people on many different platforms so it looks more like some incompatibility of your platform drivers with some libretro feature used specifically by that core.
