### ISSUE TITLE
[Wii] Club Nintendo Snes controller issue

### ISSUE THREAD

**Issue by baco81** [ekeeke/Genesis-Plus-GX#280]
Hello Eke-eke
I have been using genpluxgx 1.7.5 RC1 for a long time and it works great. Today I have tried your last build and it doesn't work with the club Nintendo Snes controller for Wii. It works fine on the menu but once I enter a game it becomes crazy as I was holding the down direction down all the time.

Other Wii emulators suffered from the same issue lately and it was solved through these commits:
https://github.com/dborth/snes9xgx/commit/dc4d93d00653e7d129cf642e5277e05900192158
https://github.com/dborth/fceugx/commit/997e3bc4035ed66885136d868e514765bb415de0
https://github.com/dborth/vbagx/commit/da80d9c8e869660927698b6343621dca7df920db
https://github.com/SuperrSonic/RA-SS/issues/12

Please help!
Thank you.

**Comment by ekeeke** [comment]
Indeed, this is probably due to when I reverted to libogc for WiiU controller support instead of using my own wrappers. There was also some fix in this wrapper for 3rd party classic controllers with invalid calibration reported values  (min/max/center values) that I forgot to backport in the emulator. The fix from Tantric works fine but the real issue is when center value is inferior or equal to min value / superior or equal to max value as it produces unexpected (infinite or negative) values when calculating the position ratio.

**Comment by ekeeke** [comment]
Could you please test attached build and tell me if it fixes your issue ?
[genplus_wii_06092019.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/3269756/genplus_wii_06092019.zip)

**Comment by baco81** [comment]
Hi Eke-Eke,
First of all, thank for your detailed explanation :-)
I have just tested the build attached and it's working nicely.
Thank you! Very much appreciated.

**Comment by ekeeke** [comment]
Fixed in https://github.com/ekeeke/Genesis-Plus-GX/commit/5b1271e4770412f47a6170b8f925905a9f46e5ef

**Comment by baco81** [comment]
Thank you for the fix, Eke-Eke.

We are lucky to have a talented developer like you on the Wii scene.

Cheers!
