### ISSUE TITLE
Time Soldiers has graphics corruption

### ISSUE THREAD

**Issue by FeRcHuLeS** [ekeeke/Genesis-Plus-GX#284]
The graphics are corrupted after beating a normal boss then entering the time machine at the beginning next stage or after continuing the same stage, as in this vid, check 08:14, 11:50 (https://drive.google.com/open?id=10imjx8fE0hzQ6iz4fluwqgrLzr5s1ydG). It is maybe related to the game maybe not.

**Comment by ekeeke** [comment]
It looks like a weird VRAM corruption of some (only one each time ?) particular sprite data and it does not really look like a common emulation bug (it also never was reported before e although SMS VDP emulation code hasn't been changed for years). 

What port of the emulator are you using ? Retroarch ? On what platform ? If you are using some Retroarch specific emulation hacks like run-ahead or sprites-limit removal, try with these options disabled as they can cause emulation bugs. Also check you don't have any cheat codes enabled that could have corrupted the ROM or that the ROM is a verified dump (it seems it was recognized as a known dump since FM music was apparently automatically enabled but maybe you forced that ON in emulator settings, I don't know).

**Comment by FeRcHuLeS** [comment]
Hi, It's Retroarch, Windows, latest build from here is what I'm using, runahead off, remove sprites limit on, cheats off (never on), the dump seems to be a good dump since the database show info and thumbnails for the game, FM is set to auto, 

I've played again and the blue car boss re-appeared again at the same place just like in the vid at 11:50 again displaying helicopter graphics corrupted, now with remove sprite limit off, set system to PAL, borders off (borders on and the display is too small),

**Comment by ekeeke** [comment]
Can you try also with 'system' core setting set to 'master system 2' ? with FM forced off ?
Is it always happening at the two same spots (8:18 and 12:04 precisely in your video) with the same sprite (looks like one big sprite being corrupted by other visible sprite) or is iit random ?

**Comment by FeRcHuLeS** [comment]
Tried system to master system II and FM off, and is still the same graphics corruption, I noticed as you can watch in 8:14 I skipped the boss by going the upmost part then going right (thanks to speed up item) It can be called a glitch, at 11:50 I find a way to reproduce it by going to the leftmost part at the beginining of the stage, so by going to the rightmost part there are no graphics corruption this can be called a glitch too, if I had the chance to test on real hardware but sadly I can't. 

About the graphics seem to be different graphics in both cases: 
-1st case bazooka soldier and ¿something weird?
-2nd case seems a combination of time machine, blue car and helicopter in blue

**Comment by ekeeke** [comment]
Sorry but I can't reproduce your glitches (either first or second one). I think it's caused by you skipping the mini-boss fight at 8:14, which somehow mess the sprites after that because you are not supposed to go to the next part yet and you are supposed to first beat the jeep mini-boss. Notice how those glitches both appear at the same spot (if you go to that place normally, there are helicopter sprites flying around). The first time it messes up  the helicopter sprite with some of the previous soldier sprites (most likely because the helicopter sprite load event did not occured yet) and the second time (when you go back to world wars) the game immediately jumps to the mini-boss fight that you skipped the first time , which is not normal gameflow and mixes the jeep sprite with the helicopter sprites flying around.

**Comment by FeRcHuLeS** [comment]
It seems so, not a big deal but both cases are indepent themselves, to reproduce the 1st case just go upwards to race vs vertical scrolling be sure you are the rightmost part near the end avoiding to reach the limit of the background scrolling then go right to the next part to the stage skipping the mini-boss.

The 2nd case just try to be at the leftmost part just at the begining of the stage so don't go upwards until the leftmost part is reached. Fair enough, and thank you.
