### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by rdanbrook** [ekeeke/Genesis-Plus-GX#286]
After combing through the history a bit I came across this commit:
https://github.com/ekeeke/Genesis-Plus-GX/commit/62f1204476c788e51d09e62d168fad14fd39e075

I'm curious as to what happened here in regards to licensing. It seems like it was simply changed from GPLv2 to a custom MAME-inspired license. Were you given permission to relicense by the original copyright holders? Was this to deal with any license incompatibilities that were already problems in the codebase? As I always like to respect the terms of licenses, I am looking for some clarity here before I make any moves regarding my own use of this codebase.

**Comment by p1pkin** [comment]
latest 1.3 version original Genesis Plus emulator uses "old MAME"-style strict non-commercial license (earlier versions was GPLv2).
it seems was relicensed by author of this emulator - Charles MacDonald, to be license-compatible with MAME and use some components from it.

**Comment by rdanbrook** [comment]
@p1pkin Interesting. I can't seem to find any releases of the Genesis Plus 1.3 sources. Is there an archive of source releases somewhere that I'm not seeing?

**Comment by p1pkin** [comment]
https://segaretro.org/Genesis_Plus
you may find there non-commercial 1.3 sources, as well as >15yr old GPL-licensed versions.

**Comment by ekeeke** [comment]
>Were you given permission to relicense by the original copyright holders?
What an odd question. Off course I was. Relicensing was actually done initially by original Genesis Plus author, Charles MacDonald (v1.3 was simply relicensing of v1.2a) and I applied same relicensing on Genesis Plus GX code modules which originally come from Genesis Plus (for which we are now both copyright owners) + all the code modules I wrote myself (emulation of extra input peripherals, cartridge hardware, mega cd hardware, etc) for which I am the sole copyright owner. All other modules (external libraries like libtremor, NTSC filter / Blip Buffer from Shai Green, CPU and FM cores from MAME team, etc) were obviously kept under their original license (BSD for libtremor, LGPL for NTSC filter / Blup Buffer and non-commercial for the others).

> Was this to deal with any license incompatibilities that were already problems in the codebase?
Not really, it was more a reaction to some people using GPL license to make money ofn our back by selling emulators based on Genesis Plus (GX) code and us (Charles and I) feeling bad about this and wanting to retain control on our hard work. That's said, this also fixed license incompatibility within Genesis Plus between original GPL code and MAME non-commercial code (not that he bothered anybody back then, maybe because Charles was kinda a MAME dev and nobody cared much about licensing or selling emulators in these 'old' times).

>As I always like to respect the terms of licenses, I am looking for some clarity here before I make any moves regarding my own use of this codebase

The terms of the license are perfectly clear and legit so I am not sure why exactly you would need clarification unless you are trying to find a justification for ignoring the non-commercial clause. If you want more 'free' licensing terms for your own use, your only solution is to use the old GPL codebase.

**Comment by rdanbrook** [comment]
It's really not an odd question. It's not clear from the commit history what happened.

No need to be so defensive, I'm just asking for clarity, and now I have it. I'm just a hobbyist open source developer like yourself, and I like to be absolutely sure I'm respecting the licensing terms, so if there are any "licensing minefields" I prefer to be fully aware of that situation.

**Comment by ekeeke** [comment]
From the first modified file in linked commit:
`* updated to new Genesis Plus license (see http://cgfm2.emuviews.com/)`

Yes, I found the question odd because answering the contrary would be implying the current license has zero value and that I literally screwed original copyright owner 8 years ago. Sorry for being defensive but I have seen so many time Free Software 'knights' coming here or elsewhere to argue about 'not free' licensing choice that I've become suspicious.

**Comment by rdanbrook** [comment]
Sorry, looks like I didn't see that line. For a change that big it might have been better to place it in the title of the commit itself, but it was 8 years ago so no point in revisiting that now.

I get it, lots of people want to cash in on our hobby. In my own case, I maintain an open source emulator (Nestopia UE, GPLv2) and also have a fork of Charles MacDonald's smsplus of my own for experimentation, where I did all of my research on the licensing to ensure I wasn't falling afoul. I will be releasing something in the future that makes use of Genesis Plus GX as well, so the licensing situation is something I really needed to be clear on before I move forward on that. I suppose for my part, I could have worded my original issue less robotically :).
