### ISSUE TITLE
Remute - Technoptimistic refuses to run due to inaccuracy

### ISSUE THREAD

**Issue by Pat86** [ekeeke/Genesis-Plus-GX#295]
I just got Remutes music cartridge, did a dump for myself and tried it via the latest Genesis Plus GX core + Nukes FM. Still it doesnt work.

https://remute.bandcamp.com/album/technoptimistic

![Technoptimistic(mus0000-191128-162942](https://user-images.githubusercontent.com/20128108/69818656-842a8a80-11fd-11ea-9021-9404a7c2dbb7.png)

**Comment by ekeeke** [comment]
Yes, this one does not rely on cycle-accurate YM2612 emulation (I don't know any game or demo that does actually) so using nuked or mame core would make no difference.


It relies z80/68k cpus latency (wait-states) when z80 accesses 68k bus, which happens on real hardware and slowdown cpus a bit but is not emulated here, because again, no games rely on such precise timings either and this is afaik only needed for two demos (this one which intentionally locks itself if measured timings are off and Titan's Overdrive 2 demo which relies on this latency for proper audio/video syncronization).

I have a fixed version locally which emulates that latency more or less accurately and runs that demo just fine, the only reason I still haven't commited it is that I am not sure of the impact on other timings-sensitive games.

**Comment by ekeeke** [comment]
Hmm, I actually mixed with Remute Red Eyes demo, which appears to show the same error screen in Genesis Plus GX (and other emulators).

I don't own the ROM you mentionned and have no plan to buy this cartridge so I cannot verify if my current fix also solve the issue with Technoptimistic.

Could you please test this win32/sdl build and tell me if your ROM works with it (you only need to drag and drop the ROM file into gen_sdl.exe and make sure SDL.dll is in the same directory as the exe) ?

Thanks
[genplus-gx-sdl-040420.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/4431332/genplus-gx-sdl-040420.zip)

**Comment by Pat86** [comment]
Its working. Passed the test. :)

![Anmerkung 2020-04-04 174356](https://user-images.githubusercontent.com/20128108/78455026-38e92280-769c-11ea-93ab-306bbd58622c.png)

**Comment by ekeeke** [comment]
Great. Here is the commit fixing this issue: https://github.com/ekeeke/Genesis-Plus-GX/commit/7b52165dd5d84f134fe2a2d22b6cc95be5361d9a
