### ISSUE TITLE
[libretro] No input on second player.

### ISSUE THREAD

**Issue by demodanza** [ekeeke/Genesis-Plus-GX#300]
As the title says, using two Xbox 360 wireless controllers, first player registers input just fine (walking, jumping), second player doesn't. Both gamepads work fine, both in menus and any other core, and are configured as normal.

**Comment by ekeeke** [comment]
You need to set port #2 or player #2 (whatever it is labelled in retroarch) device type to "Joypad Auto" instead of "Joypad Port Empty".

In any cases, this is not really a core (genesis plus gx) issue (the core supports 2 players and more just fine) but rather a frontend (retroarch) issue/misconfiguration so you are better asking help to retroarch devs or on libretro forums as I don't use much retroarch myself and can't help you with its configuration.
