### ISSUE TITLE
[libretro] PAL games bad aspect ratio in fullscreen

### ISSUE THREAD

**Issue by ner00** [ekeeke/Genesis-Plus-GX#302]
I've tried finding an existing issue that deals with this matter. I've come across a few where the intricacies of scaling are discussed at length, but didn't recognize the issue that I'm experiencing in any of them, in any case I apologize in advance if I'm creating a redundant issue and/or making someone repeat something already mentioned before elsewhere.

The issue I'm facing seems to have more to do with RetroArch than with the core itself, but for the sake of the argument I'll begin by addressing the issue towards the core dev.

Essentially, in 1080p fullscreen, all PAL games are stretched wider than they should be when using the default core-provided ratio. In fact, in my case, NTSC games are being scaled closer to PAL resolutions and PAL games are just being stretched way wider than they should ever be.

I've gathered a few examples using Super Street Fighter II (USA/NTSC and EU/PAL):

**Native resolutions:**
* NTSC: 320 x 224
*    PAL: 320 x 240
*6.8% divergence between resolutions*

**Example of correct ratio (ie: BizHawk/Genesis Plus GX)**
* NTSC: 320 x 224 -> 1542 x 1080 (W +482%)
*    PAL: 320 x 240 -> 1440 x 1080 (W +450%)
*6.8% divergence between resolutions*

**Ratio in RetroArch/Genesis Plus GX (auto core-provided ratio)**
* NTSC: 320 x 224 -> 1411 x 1080 (W +440%)
*    PAL: 320 x 240 -> 1711 x 1080 (W +535%)
*19.2% divergence between resolutions*

**Ratio in RetroArch/Genesis Plus GX (global 4:3 enforced)**
* NTSC: 320 x 224 -> 1440 x 1080 (W +450%)
*    PAL: 320 x 240 -> 1440 x 1080 (W +450%)
*No divergence between resolutions*

**Ratio in RetroArch/Genesis Plus GX (manual NTSC PAR ratio)**
* NTSC: 320 x 224 -> 1411 x 1080 (W +440%)
*    PAL: 320 x 240 -> 1424 x 1080 (W +445%)
*0.9% divergence between resolutions*

**Ratio in RetroArch/Genesis Plus GX (manual PAL PAR ratio)**
* NTSC: 320 x 224 -> 1695 x 1080 (W +529%)
*    PAL: 320 x 240 -> 1711 x 1080 (W +535%)
*0.9% divergence between resolutions*

Apparently only 4:3 and NTSC come close to delivering a ratio close to the original, but PAL ratio does not seem to be taken into account at all, being stretched horizontally far more than it should. The most problematic thing though is that the core-provided ratio when detecting PAL delivers this bad resolution, this seems incorrect and does look incorrect.

Thanks.

NOTE: This issue is concurrent with the one created here: https://github.com/libretro/Genesis-Plus-GX/issues/204

**Comment by ekeeke** [comment]
The provided aspect ratio is actually correct and accurate to real hardware. You have to realize that PAL (well, more exactly 50hz tv signal) outputs more lines per frame than 60hz (625 lines for 50hz vs 525 lines for 60hz) so, for a given TV screen size, 50hz lines are actually much thinner than 60hz lines.

This is the reason 320x224 resolution gives you close to 4:3 full screen on NTSC (or PAL 60hz modded) consoles but crunched screen (vertically) on PAL 50hz consoles. A few games are PAL-optimized and use extended 320x240 resolution mode (i only know Story of Thor and Street of Rage 3 that use 320x240, not sure about SSF2) but 240 PAL lines are still not enough to fill 4:3 TV screen vertically so resulting screen is still squished on 50hz consoles compared to 60hz consoles.

Apparently, Retroarch fixes the output vertical resolution (to a multiple of emulated screen height) and adjust output width to deal with provided aspect ratio, hence the results you are observing.

**Comment by ner00** [comment]
Thanks for the explanation.

I mentioned that using BizHawk with this core didn't show the same issue, although BizHawk seems to force the same resolution (NTSC) regardless of the game region, something that can also be accomplished in RetroArch by changing the default core ratio to NTSC PAR. I was already leaning towards it being RetroArch rather than the core, I just wanted to get some clarity.

It is slightly confusing when you say that the aspect ratio is correct and accurate because I have mentioned a few different results which vary wildly, and I doubt they would all be considered accurate regardless of PAL not having enough lines to fill the screen vertically. Assuming the output vertical resolution of max screen height (1080p), the horizontal resolution would be something around 1440p or so, I don't understand what justifies it to stretch all the way up to 1711p wide, the math doesn't seem right and the end result less so. 

I understand PAL games look squished in comparison to NTSC, but the exaggerated "squishiness" by the core ratio output from RetroArch isn't simply something derived from ratio adjustment making it more obvious, it is rather stretched excessively beyond what the ratio would or should be.

**Comment by ner00** [comment]
I did some more comparisons and I have to completely backtrack on my previous statements, this is definitely the result of the squishiness being more noticeable due to a higher resolution. I used another emulator and compared the PAL outputs from both, the ratio seems right.

Comparison: https://media.giphy.com/media/W5sI0G17YO2Rz1RD7U/giphy.gif

Screengrabs used for comparison:
PAL1: https://i.imgur.com/OKbwUIe.png
PAL2: https://i.imgur.com/zSpn6a9.png

Thanks again and sorry for the hassle.

**Comment by ner00** [comment]
Another comparison which makes me believe RetroArch is exaggerating the horizontal resolution:

![](https://media.giphy.com/media/duWueJ7ypjkK2phYww/giphy.gif)

**Screengrabs used for comparison**

![](https://i.imgur.com/FU9nrfD.png)

![](https://i.imgur.com/4osOLIN.png)

![](https://i.imgur.com/hbcBaOL.png)

**Comment by ekeeke** [comment]
The problem with your logic is:
1) that game is SF2 CE and I know it does not use 320x240 extended resolution mode but 320x224 (or rather 256x224 but that makes no difference horizontally since pixels are just wider in this mode) normal resolution.
2) kega fusion does not enforces PAL resolution, it always enforces 4:3 resolution, with or without borders (in your shot, it's just the 320x224 megadrive screen with 8 lines on top/bottom borders to fill 320x240 screen, PAL aspect ratio would have much higher borders and shrinked height).

**Comment by ekeeke** [comment]
Also, about that:

> It is slightly confusing when you say that the aspect ratio is correct and accurate because I have mentioned a few different results which vary wildly

They all actually match (except the resolution returned by Bizhawk which is plain wrong as it assumes 320x240 is 4:3 in both ntsc or pal modes and so incorrectly stretches 320x224 screen in ntsc mode, when it should actually be close to 4:3):
- NTSC output resolution with core-provided AUTO or Forced NTSC aspect ratio both match
- PAL output resolution with core-provided AUTO or Forced PAl aspect ratio both match
- the difference between NTSC and PAL output resolutions when either forced NTSC or forced PAL aspect ratio is used is due to the 0.9% difference between PAL and NTSC consoles master clock, which makes pixel clock 0.9% slower on PAL consoles and active screen therefore 0.9% wider.
- the difference between NTSC output resolutions in Forced 4:3 and Auto (or Forced NTSC) aspect ratio is because the real 60hz aspect ratio for 320x224 screen on NTSC consoles is not exactly 4:3 (1.333) but closer to 1.30, again because of the pixel clock, which derives from console master clock.

**Comment by ner00** [comment]
Once again, thanks for elaborating on a subject which you have probably repeated a hundred times. Unfortunately I don't have enough knowledge to dissect this information or come to these conclusions myself, but I trust you know for the both of us.

I was just used to seeing different upscales in other emulations, proportionality is what I mean, I assumed that my eyes were correct in telling me this couldn't be accurate because it looked too stretched horizontally.

Okay, this is the last one... I did a few more tests, potentially worth nothing of substance.
I used the 240p Test Suite ROM in Retroarch, alternating between NTSC and PAL regions for linearity test sets. 256x224 PAL is the only one which looks pretty bad, but it may well be the result of upscaling an already crunched aspect ratio like you said. Just tell me if you think these results are to be expected given all that you have mentioned before:

**NTSC 256x224**
Big circle (inner): 1069x1071
Small circles (inner): 259x260
![](https://i.imgur.com/z26HUG2.png)

**PAL 256x224**
Big circle (inner): 1083x1060
Small circles (inner): 281x236
![](https://i.imgur.com/OLDrGA8.png)

**NTSC 320x224**
Big circle (inner): 1067x1065
Small circles (inner): 256x250
![](https://i.imgur.com/dB6hd0o.png)

**PAL 320x224**
Big circle (inner): 1060x1075
Small circles (inner): 278x274
![](https://i.imgur.com/uEphC0d.png)

**Comment by ekeeke** [comment]
The aspect ratio reported by the core is the exact same in H32 (256 pixels width) or H40 (320 pixels width) modes (as explained previously, pixels in H32 mode are 10:8 wider than in H40 mode because of slower pixel clock so the active width displayed on TV is the same in both resolution modes), so I would rather suspect a bug in 240p test suite when handling aspect corrections of tiles map in PAL H32 VDP mode in PAL (you can see it does correction in PAL H40 mode to compensate for the shrinked screen height, and it does too in NTSC H32 mode to compensate for the stretched screen width, but somehow the aspect ratio compensation is incorrect in PAL H32 mode).

Looking at 240p test suite sourcecode on github, it looks like the aspect correction for linearity test in PAL H40 mode was fixed 6 years ago by changing the tilemap and reducing the number of tiles in PAL mode to compensate for the shrinked display aspect ratio, then 2 years later, a similar test was added in H32 mode (for both PAL and NTSC VDP modes) but it seems to me the number of tiles for PAL H32 is wrong (it should logically be smaller than the NTSC H32 one, like PAL H40 one is smaller than NTSC H40 one).

Off course I might be wrong and misunderstanding the sourcecode, but I guess it should be easy to confirm this theory by running the test on a PAL megadrive.

**Comment by bryc** [comment]
I think this issue may be a core one, and deserves a bit more attention, considering there is disagreement on aspect ratio between the Mega Drive RA cores.

**PicoDrive** has three aspect ratio options: PAR, 4/3 and CRT.   PicoDrive's 4/3 mode is wider than GenPlusGX's NTSC PAR mode, but its CRT mode is thinner.

**BlastEm** has no core options, but its aspect ratio exactly identical to PicoDrive's PAR. I found that interesting. There seems to be no difference in aspect between PAL and NTSC games. I'm left wondering if that is a bad thing or a good thing?

**GenPlusGX** has two options: PAL PAR and NTSC PAR.  PAL PAR is heavily stretched horizontally (or squished vertically, whichever you prefer). NTSC PAR seems to be in between PicoDrive's 4/3 and CRT ratios.

----

So, PicoDrive and BlastEm seem to agree on the "PAR" aspect ratio, which I assume is PAL because its noticeably wider than 4:3 or GenPlusGX's NTSC mode. GenPlusGX doesn't use this aspect ratio for its PAL mode, and instead uses something much more stretched and exaggerated. And it's really jarring.

Personally I would rather use the "PAR" aspect ratio on either all games, or only PAL games, and ditch this heavily stretched mode that is applied to PAL games exclusively.

Questions:

- Why would GenPlusGX's PAL ratio differ when PicoDrive and BlastEm both agree on their PAL ratio? Wouldn't that be the correct one?
- Why is GenPlusGX's NTSC ratio different from both PicoDrive's 4/3 and CRT ratio? You'd think at least one would match it.

**Comment by ekeeke** [comment]
>Why would GenPlusGX's PAL ratio differ when PicoDrive and BlastEm both agree on their PAL ratio? Wouldn't that be the correct one?

**Comment by bryc** [comment]
Thanks for those answers. 

This is a good video on this topic (comparing NTSC/PAL aspect ratios): https://www.youtube.com/watch?v=iPhESbeKFIE

I think I get it now. On real PAL hardware, the overscan would end up visible on the CRT.

If I set borders to "full", it sort of zooms out and no longer feels as stretched. Which is weird because it's the same aspect ratio, just with the overscan shown.

**Comment by ekeeke** [comment]
>If I set borders to "full", it sort of zooms out and no longer feels as stretched. Which is weird because it's the same aspect ratio, just with the overscan shown.

This is because of how Retroarch deals with aspect ratio scaling (at least in windowed mode I think): the height of the provided screen is upscaled to an integer ratio within the output resolution then the width is stretched accorfing to the gicen aspect ratio. When top/bottom borders are emulated, the rendered screen height is much larger (288 lines corresponding to 224 active lines + 32 blank lines on top/bottom instead of just 224 lines) so the width is much less upscaled.
