### ISSUE TITLE
How to compile older version

### ISSUE THREAD

**Issue by krystofurr** [ekeeke/Genesis-Plus-GX#303]
Hi there,

 I was wondering if it's possible to get an older compiled version of the emulator for Linux.  If not how could I do so?  I have the following setup:

Raspberry PI 3 w/ Retropie
Core is currently 1.7.5. ( I'm looking for 1.7.4 )

Thanks!
Chris

**Comment by ekeeke** [comment]
You need to get the sourcecode using github, rebase to a specific tagged version in history and compile libretro core for rpi platform. 

However, be aware that 1.7.4 version is very very old and probably not the version you are looking for: I never officially tagged 1.7.5 version (only the savestate version was eventually changed in advance to 1.7.5 in some commit to indicate savestate format was changed and was incompatible with savestates made previously) and there have been many many changes and fixes since 1.7.4 release.

Out of curiosity, why do you want to revert to older version ? It might be easier for you to ask libretro if it is possible to get older versions from their build bot and pick one from the date you want.

**Comment by krystofurr** [comment]
I want an older version because I have save states that are only usable it seems with that particular version it seems.  When version 1.7.5 came out ( which it the latest I believe ) it says that prior save states are not compatible.  So I can either find a way to get an older core for my Retropie. Or get a newer core for Retroarch in Windows ( Also I can't seem to get it updated to 1.7.5 in Windows 10 ).  I will try with libretro though to see.  Thanks for the help!
