### ISSUE TITLE
Sega CD bootlogo not rotating

### ISSUE THREAD

**Issue by Pat86** [ekeeke/Genesis-Plus-GX#307]
I'm currently trying out byuu's mega cd emulation and while doing an comparison clip i found out, that the sega cd bootlogo isn't rotating with genesis plus gx, while with byuu it does (occasionally).

byuu
https://streamable.com/gunxg

genesis plus gx (latest RA core)
https://streamable.com/3rcgx

**Comment by ekeeke** [comment]
The Model 2 BOOT ROM only starts rotating & scaling logos after a while, which only happens if there is no CD game inserted. Indeed, if a Sega CD game is detected, it will automatically be started after a few seconds before the logo effects could be started. You can see rotation/scaling effects by directly loading the Sega CD 2.00 BOOT ROM in Genesis Plus GX or loading an audio CD image file.

Seems like byuu emulator have timing issues and either is running the boot intro too fast or is waiting too long before auto-booting loaded CD game.
