### ISSUE TITLE
Bitbucket downloads page no longer working

### ISSUE THREAD

**Issue by icup321** [ekeeke/Genesis-Plus-GX#308]
The bitbucket links for the latest compiled Genesis Plus GX builds are no longer working, when I click the link, it leads me to a non-existent page, as if it's been removed.

**Comment by ekeeke** [comment]
Seems like my bitbucket account has been suspended, not sure when this happened or why...

Here is the message I get when trying to log in:
"Your account has been disabled.
We're sorry. Your account has been flagged by our automated system for possible violation of our Cloud Terms of Service."

Not sure if I can get it reactivated (I hope so since the issue tracker and download page hold valuable stuff to me) but in the mean time, you can download the last (quite old) official version from https://segaretro.org/Genesis_Plus_GX#Downloads or get the newest builds from https://github.com/ekeeke/Genesis-Plus-GX/tree/master/builds

**Comment by ekeeke** [comment]
Bitbucket account should now be working again.
