### ISSUE TITLE
Possible typo in sound.c

### ISSUE THREAD

**Issue by fedex81** [ekeeke/Genesis-Plus-GX#309]
Hello,
I suspect that in sound.c line 490,
#ifdef HAVE_YM3438_CORE
should be
#ifdef HAVE_OPLL_CORE
?

**Comment by ekeeke** [comment]
Hi,This is indeed an error in the latest pull request, thanks for the report.
-------- Message d'origine --------De : Federico Berti <notifications@github.com> Date : 03/04/2020  18:17  (GMT+01:00) À : ekeeke/Genesis-Plus-GX <Genesis-Plus-GX@noreply.github.com> Cc : Subscribed <subscribed@noreply.github.com> Objet : [ekeeke/Genesis-Plus-GX] Possible typo in sound.c (#309) 
Hello,
I suspect that in sound.c line 490,
#ifdef HAVE_YM3438_CORE
should be
#ifdef HAVE_OPLL_CORE
?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ekeeke/Genesis-Plus-GX/issues/309",
"url": "https://github.com/ekeeke/Genesis-Plus-GX/issues/309",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ekeeke** [comment]
Fixed by https://github.com/ekeeke/Genesis-Plus-GX/commit/bd7875b3982de45a1118844b3c28277d3a705834
