### ISSUE TITLE
"Illegal Instruction" when starting game on Powerbook G4 (Linux)

### ISSUE THREAD

**Issue by wyatt8740** [ekeeke/Genesis-Plus-GX#312]
EDIT:
The illegal instruction seems to be sourced from Retroarch rather than your library. I'm trying to figure out if there's actually something wrong with your library now because the games still aren't working. I'll be back once I have the SDL version built. Note that you use `-march=native` in your SDL1 makefile, which isn't valid on PPC GCC.

Trying my old  build of retroarch from July 2018 is not crashing, but **is** yielding a black screen with no audio. Snes9x is working in that build. So I'm still not sure what's up.

> I tried running Phantasy Star IV in Retroarch using Genesis Plus GX's core (built from git master). However, all that happens is the screen turning blue for a frame or two and then Retroarch crashes with `Illegal instruction` printed to the console.

> I recompiled it with `-O0 -mcpu=G4` in my CFLAGS and nothing changed.

> I'm not sure what more technical information I can give, or how to really debug this. I'd be happy to poke around and try to find out if you can tell me what information you need. Is there some other changes I need to make to the Makefile for it to build correctly for PowerPC? Or is the PowerPC code making lots of assumptions of a PPC750 like the Wii/GC uses?

> My OS is Debian Sid.
> /proc/cpuinfo:
> ```
> processor       : 0
> cpu             : 7447A, altivec supported
> clock           : 666.666000MHz
> revision        : 1.1 (pvr 8003 0101)
> bogomips        : 36.86
> 
> timebase        : 18432000
> platform        : PowerMac
> model           : PowerBook5,4
> machine         : PowerBook5,4
> motherboard     : PowerBook5,4 MacRISC3 Power Macintosh 
> detected as     : 287 (PowerBook G4 15")
> pmac flags      : 0000001a
> L2 cache        : 512K unified
> pmac-generation : NewWorld
> Memory          : 2048 MB
> ```
> uname -a:
> ```
> Linux wyatt-PowerBookG4-Debian 4.16.0-2-powerpc #1 Debian 4.16.16-2 (2018-06-22) ppc GNU/Linux
> ```

**Comment by wyatt8740** [comment]
closing this issue; will open a new one when I have an actual issue to report for sure.

**Comment by ekeeke** [comment]
There is no "PowerPC code": the emulator code is entirely written in portable C and do not rely on any host platform or CPU specific feature.

The "Illegal Instruction" is likely caused by unrecognized 68k opcode processing because of incorrect endianness configuration in Makefile.

The emulator supports both little-endian and big-endian host platforms through the definition of LSB_FIRST macro.

The SDL port was originally meant only for Windows machine, so it is configured by default for little-endian platform. Since PPC is big endian, you will need to remove -DLSB_FIRST define from your Makefile.

**Comment by wyatt8740** [comment]
Confirming, it is indeed not an issue with this core but with my build of Retroarch.
