### ISSUE TITLE
SDL: main.c: should use AUDIO_S16SYS instead of AUDIO_S16LSB

### ISSUE THREAD

**Issue by wyatt8740** [ekeeke/Genesis-Plus-GX#314]
The SDL 1 and 2 frontends for Genesis Plus GX give staticy, noisy sound on big-endian platforms. This is due to forcing SDL to use little-endian audio.

This is rectified when `AUDIO_S16SYS` or `AUDIO_S16MSB` is used as the value of `as_desired.format` (at least on Debian PowerPC using `SDL_AUDIODRIVER=alsa`).

Apart from that, the makefile should also set your architecture and define endian-ness related variables appropriately, but that's a Makefile thing that people can probably figure out easily enough.

**Comment by ekeeke** [comment]
Thanks for the correction, it is fixed in https://github.com/ekeeke/Genesis-Plus-GX/commit/9630e59552fd7729e35925c145fb5acbd6bd09dc

Yes, initially SDL port was only for meant for Windows. Some people have submitted changes to make it multi-platform but makefiles still assume little-endian platform. Feel free to submit pull requests to improve portability as I don't really maintain the SDL port.
