### ISSUE TITLE
8-bits Systems sound too low

### ISSUE THREAD

**Issue by FeRcHuLeS** [ekeeke/Genesis-Plus-GX#318]
The mentioned systems sound half lower than the 16-bits systems to my appreciation: 
-no libretro audio filters are on 
-low pass filter is off
-nuked (ym3438) is selected

I noticed there are 2 core versions, yours and libretro which is not up to date but add amplifiers for PSG and FM, those don't help that much though, is there a way to add a **auto volume regulator** and why yours lacks those amplifiers?

**Comment by ekeeke** [comment]
ym3438 is for megadrive, not master system... or do you mean ym2413 (opll) ?

I did not tested nuked opll core yet but if the issue is it sounds lower than mame core, it should be possible to amplify its output to match mame ym2413 core. As for PSG sound, I don't feel master system or game gear games sound being 'too low' personally but that's indeed a thing you can change via the emulation settings (psg volume).



As for the reason why those settings are not exposed in my repository, it's because I don't maintain the libretro port myself and it only get updated if people push changes made in libretro repository back in my own repository, which has not happened for a while. I will likely try to synchronize with the libretro repo at some point but that's not really a priority to me for the moment. Anybody is welcomed to submit code update through pull request though.

If the setting exposed in libretro version is not suitable to you (not enough range or not enough granularity), you will have to ask to libretro devs though.

**Comment by FeRcHuLeS** [comment]
It is the Genesis FM is tested (the nuked (ym3438)) I was talking about , I've just figured out it is related to most of the 8-bits games such as: Time Soldiers (SMS), GG Shinobi (SGG), Dragon Wang (SG1000), Rygar (SMS) have audio too low that's the way these game were programmed on the other hand R-Type (SMS) sounds fine.

While in libretro is adjustable the volume gain in db, I can request an Auto Volume Regulator that would be a great feature to the core in order not to worry of volume adjustments between games, in theory at least.

**Comment by ekeeke** [comment]
Again, Master System games can not use YM3438/YM2612 (OPN2) chip, and emulation of Megadrive FM chip is disabled in 8-bit mode so it's definitively NOT ym3438 audio you are hearing in these games.

Master System games can only use YM2413 (OPLL) chip and not all of them are programmed to support that FM chip as it was only available in Japanese consoles.

Also no GG or SG-1000 games support FM unit so I have no idea what you are talking about or what you think you are suppoqed to hear...

**Comment by FeRcHuLeS** [comment]
The Genesis/Megadrive FM is linked with the PSG in some way since I've noticed tone changed by  selecting another chip like mame's for example in GG Shinobi (J).gg CRC32: 83926BD1
,that's the misunderstanding then this is a bug.

Again no matter PSG or FM unit is on, the audio is low that is maybe the motivation of libretro's to add amplifiers to both the PSG and FM units. 

I discovered the aforementioned systems have low audio when I repaired the speakers I'm using, my configurations:
-(HARDWARE) Volume to 25%
-(SOFTWARE)) Main volume  50%
-(RETROARCH) Volume gain (db ) 0.0

Most of the cores sound fine but most of the games for the systems aforementioned, even most of the videos on youtube to 100% volume for example don't need an adjustment. My point is people is used to adjust the volume frequently since there is no a clear standard for the audio part, on the other hand people is not used to adjust bright, contrast of video part, and the Auto Volume Regulator (AVR) helped a lot to TVs long time ago since the CRTs to HDTVs, so I find an AVR a pretty good idea to me.

**Comment by ekeeke** [comment]
>The Genesis/Megadrive FM is linked with the PSG in some way since I've noticed tone changed by selecting another chip like mame's for example in GG Shinobi (J).gg CRC32: 83926BD1
,that's the misunderstanding then this is a bug.

No, I can assure you that you are wrong since I know the code and how the emulator work: there is absolutely NO link between megadrive FM sound and PSG sound when playing 8-bit (SG, MS or GG) games, megadrive FM is inactive and not playing.

It's possible that changing megadrive FM core while playing a game (8bit or 16bit) will reset the sound emulation even if FM wascnot being used, thus reseting PSG and potentially breaking the playing game sound but this has nothing to do with overall volume. Resetting the game will fix the PSG sound.
