### ISSUE TITLE
Audio Problems: Ecco - The Tides of Time (USA) (Sega CD)

### ISSUE THREAD

**Issue by carmiker** [ekeeke/Genesis-Plus-GX#323]
I have noticed that this game in specific seems to have what sounds like buffer underruns. However, I cannot discern the source of the problem. I have tested with the libretro build from this repository, as well as the libretro build maintained by the libretro organization, and also my own unreleased port of the emulator, and the issue is observable in all three builds. Therefore, I assume this is something happening at the core level. My own audio output and resampling buffers show no signs of underruns, but I have not looked deeper to see what is going on with the emulator's internal resampler yet. I have not observed the issue in any other games.

**Comment by ekeeke** [comment]
You will need to give more details if you want me to have a look at this: where and when does it happen exactly ? with what kind of sound (FM sound , CD audio, etc) ? what is precisely the observed behavior ? what is the expected behavior ? 

Providing records from real hardware (or another emulator that you think behaves correctly) and from the version of the emulator you are running so we can hear the differences is also helpful.

**Comment by carmiker** [comment]
It most certainly sounds like CD audio. However, I have just tested in Fusion 3.64, and the problem is also exhibited there, suggesting it may be the game, since two well known and respected emulators are showing it. I tried different BIOS revisions, as well. I am sure I have never heard these audio glitches on real hardware, but currently do not have real hardware available to test. I'll leave this for now and follow up again once I have tested real hardware and can perhaps make a recording.
