### ISSUE TITLE
"Retroarch" Shooting doesn't work with mouse as lightgun (Ms Light Phaser)

### ISSUE THREAD

**Issue by marcelosofth** [ekeeke/Genesis-Plus-GX#325]
hello friends, I have tested all the options and only the crosshairs work using the mouse but it is not possible to shoot with the mouse button and no other key, I am using the version of Genesis Plus GX 1.7.4 in Retroarch "Batocera", several people have also tried without success, is that a problem?

**Comment by ekeeke** [comment]
I'm not sure what Retroarch "Batocera" exactly is, what platform you are using for Retroarch (Windows, Linux, etc) and what kind of controller you are using to simulate lightgun (mouse, etc) but I just gave it a try and managed to get it work on Windows using Safari Hunt, with the mouse.

It was not straightforward because Retroarch input layer is not very intuitive and requires you to set some stuff manually but it worked fine in the end.

Here are the steps I've done:
1- load the game
2- go to core options and enable the "show crosshair" option
3- go to retroarch "inputs" settings (not "quick menu" control settings) and enter "port 1 bind"
4- change "Device Type" to "MS Light Phaser"
5-scroll down the page and bind "Gun Trigger" to any mouse button
6-reset the game

Genesis Plus GX core normally set automatically emulated device type to lightphaser when it detects a game that supported that device but unfortunately, libretro API does not permit the core to change the device so it will remain stuck to whatever you had set in Retroarch input settings.

If you already had done all these steps and it still doesn't work for you, then I'm afraid I cannot help as it would be more an issue on Retroarch side, like a driver issue with the Retroarch port you are using that is missing lightgun support.

Genesis Plus GX libretro port requires RETRO_DEVICE_LIGHTGUN device and RETRO_DEVICE_ID_LIGHTGUN_TRIGGER key to be implemented for lightgun support so you want to make sure the input driver you use support those.

![retroarch-1](https://user-images.githubusercontent.com/717091/85105543-f222b780-b20a-11ea-8c0e-05836d3e07de.png)
![retroarch-2](https://user-images.githubusercontent.com/717091/85105546-f2bb4e00-b20a-11ea-9524-e9e7553ac8e9.png)
![Hang On   Safari Hunt-200619-084909](https://user-images.githubusercontent.com/717091/85105577-fc44b600-b20a-11ea-899f-dcab7dd5e60d.png)
![Hang On   Safari Hunt-200619-024420](https://user-images.githubusercontent.com/717091/85105578-fcdd4c80-b20a-11ea-96eb-0b2cce169e3f.png)
![Hang On   Safari Hunt-200619-024458](https://user-images.githubusercontent.com/717091/85105582-fd75e300-b20a-11ea-985b-3454f80b1a8f.png)
