### ISSUE TITLE
FX Unit Yuki doesn't work anymore

### ISSUE THREAD

**Issue by litaniast** [ekeeke/Genesis-Plus-GX#332]
I built lr-genesis-plus-gx core from this github, but FX Unit Yuki (unlicensed platform game) doesn't work anymore.

It works well on other emulator(PicoDrive)

**Comment by ekeeke** [comment]
There was a typo introduced in https://github.com/ekeeke/Genesis-Plus-GX/commit/1758bbe0e4d359451ddccaaca728241392e6f2a5 which forced loaded ROM size to 4MB and therefore broke games larger than 4MB that require linear ROM mapping (FX Unit Yuki but also Ultimate MK 3 hack).

This is now fixed in https://github.com/ekeeke/Genesis-Plus-GX/commit/aef031a6d24bfaf33a3c159e554c5e96a7d840db

**Comment by litaniast** [comment]
It works again. Thanks.
