### ISSUE TITLE
Off-brand Wii Classic Controller Pro analogs stuck down/left + 'Exception (DSI) ocurred!' while configuring input

### ISSUE THREAD

**Issue by arthurfreitas96** [ekeeke/Genesis-Plus-GX#334]
Hello,
I'm experiencing wrong analog stick calibration in a 3rd party Wii Classic Controller Pro in the current version of Genesis-Plus-GX (in wii games and gc games the controller works fine). The analog sticks are recognized by the emulator as being stuck down/left when they are really centered. Also, trying to configure the input using the UI gives me 'Exception (DSI) ocurred!' and I need to restart my Wii.

I tested older versions of the emulator but the only one that solved my problem was the mod mentioned in this post: https://gbatemp.net/threads/latest-emulator-and-libogc-with-3rd-party-classic-controller.217245/. Using this mod, the analog sticks are not recognized, but everything works as expected, including configuring the controller, and the 'Exception (DSI) ocurred!' error was gone.

However, matguitarist made his mod using Genesis-Plus-GX version 1.7.3 and I wanted to use my controller in the current version (1.7.5). I tried to compile 1.7.5 with matguitarists modded libogc, but had no success.

Can this issue be fixed? Thank you in advance.

**Comment by ekeeke** [comment]
I don't have 3rd party controllers to test (and haven't booted the Wii version for years) but this was supposed to be fixed in current build one year ago (by fixing both emulator sourcecode and using fixed libogc).

What build are you using (downloaded from where) ? Latest build can always be found from here : https://github.com/ekeeke/Genesis-Plus-GX/tree/master/builds

**Comment by arthurfreitas96** [comment]
I tested the build provided in your link and, indeed, it was my mistake. Initially I was using a build of the version 1.7.4. Using the latest build solved the analog calibration problem. However, now I am facing the same problem I described in this issue I opened in snes9xgx page: https://github.com/dborth/snes9xgx/issues/947. The controller outputs very laggy commands.

**Comment by ekeeke** [comment]
I am not sure but it looks like you are missing some build rules in your Wii development setup to build the png files into object files. It could also be some incompatibility of my Makefile with latest devkitPPC, I don't know. To be honest, I stopped updating my devkitPPC setup some times ago because they were continuously changing stuff with each release and breaking compatibility with old source code so I got fed up to play mouse 'n cat game ;-)

I am curious about the DSI exception you get with my latest build though: could you provide a screenshot of the exception dump or copypaste the infos you get on screen (in particular the callback stack dump giving the last called functions addresses) ?

**Comment by arthurfreitas96** [comment]
Here is the DSI exception, sorry about the image quality, I am running the emulator on a real Wii and all I could do was taking a photo of my tv.
![ExcDSI at 17 54 46](https://user-images.githubusercontent.com/42586099/93392081-8fab7880-f846-11ea-8716-7a0a30baaea6.jpeg)

**Comment by arthurfreitas96** [comment]
What devkitPPC setup are you using? Would it be possible to apply in the current version of Genesis-Plus-GX the same changes mentioned in the snes9xgx issue I sent?

**Comment by ekeeke** [comment]
>Here is the DSI exception, sorry about the image quality, I am running the emulator on a real Wii and all I could do was taking a photo of my tv.
Thanks, it's fine. Unfortunately, it doesn't give me much info about what could possibly have caused the crash. Could you take a picture of the screen immediately before it occurs to show exactly what action is causing it ?

>Would it be possible to apply in the current version of Genesis-Plus-GX the same changes mentioned in the snes9xgx issue I sent?
The changes mentioned in the snes9xgx issue are only libogc changes since the issue is caused by libogc code, not emulators code, so the only way to fix it is to recompile current Genesis Plus GX sourcecode with a fixed libogc build.

I have pushed 2 commits (https://github.com/ekeeke/Genesis-Plus-GX/commit/a8d15733fbcedc680d2c0724f98e3e124ef6f911 and https://github.com/ekeeke/Genesis-Plus-GX/commit/54b946cd550d4a02d6741dc52444af08547bde09) that should fix build issues you are having with latest devkitPPC (there was indeed some incompatibility introduced by gcc compiler version update and build tools refactoring in r37 and later). Please let me know if you still have issues when compiling the code as I still don't have updated my devkitPPC setup (I'm personnally using r34)

**Comment by arthurfreitas96** [comment]
![ExcDSI2 at 21 10 52](https://user-images.githubusercontent.com/42586099/93540564-70861700-f92a-11ea-8909-1e84efb73f3e.jpeg)

This is what's causing the exception.

**Comment by arthurfreitas96** [comment]
Just compiled and tested it on my Wii. Worked like a charm. The lag and the DSI Exception are gone. Thank you very much. Here's the build.
[genplus_wii.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/5243115/genplus_wii.zip)

**Comment by ekeeke** [comment]
Great, thanks for the report.
The crash was likely caused by some stack overflow in the key config message box thread because of libogc looping forever when trying to get controller status.
