### ISSUE TITLE
(Wii) Official 6 Button USB SEGA Genesis controller support (Retrobit)

### ISSUE THREAD

**Issue by Nashismo** [ekeeke/Genesis-Plus-GX#340]
So I have been trying for days to make my official 6 Button USB SEGA Genesis controller, by Retrobit, work on the Wii, but I cannot make it work no even using the Retroarch version of this emulator (using HID).

Could this be added to this amazing emulator? To me the Wii is just perfect because your emu gets real 240p support using it, on a real CRT.

If you need any testers here is me, I can test all you want. And to me this is also is the ultimate SEGA Genesis replica (even has mode button) and is perfect also because is USB, much less lag.

The ID product and vendor reported by windows is: HID\VID_0079&PID_0011&REV_0105

I will be happy to hear from you! My best regards!

Nashismo

![RB-SGA-035](https://user-images.githubusercontent.com/13341361/97925693-9af82c00-1d40-11eb-82fb-0c7abfb3cba0.jpg)

**Comment by ekeeke** [comment]
The problem is that there is no high-level library for using USB controllers in Wii homebrew (like libWiiuse for wii controllers or libogc for gc controllers) so support has to be built from scratch using low-level USB functions provided by libogc, which I have unfortunately no experience with.

Maybe if there was USB controller support in other GX emulators, this could be eventually copied into this one but still, my time is very limited these days for coding and I adding new features for the Wii/GC version is not high priority for me.

I left this as a generic feature request opened in #321 as it still is an interesting one and I have hope some other dev might contribute code for it someday.
