### ISSUE TITLE
add xbrz support

### ISSUE THREAD

**Issue by ghost** [ekeeke/Genesis-Plus-GX#343]
Hi, we don't have any native linux solution for genesis emulation with xbrz support. I would love if this being added on the long term. thanks!

**Comment by ekeeke** [comment]
Software filter or shaders are out of the scope of this emulation project and need to be handled by the frontend. Since there are no planned linux standalone version of this emulator (see https://github.com/ekeeke/Genesis-Plus-GX/issues/342), you should better asking support for this in another emulator with linux support (like Blastem) or use Retroarch linux port which I think have XBRZ shaders.
