### ISSUE TITLE
blue bar on the left side when playing Master System Games

### ISSUE THREAD

**Issue by Cibomatto2002** [ekeeke/Genesis-Plus-GX#348]
Some games when playing Master System Games have a blue bar on the side is there a way to remove it if not could someone add a way to remove it please. I'm using Retroarch 1.9.0 on the Pc and Lakka on the pie 4
![1](https://user-images.githubusercontent.com/21169038/103135719-ced83980-467f-11eb-8936-9bae85b2cd13.jpg)

The name of this game is Zillion (Europe, Brazil) (Rev 2)

**Comment by ekeeke** [comment]
The bar can actually be any color and is controlled by the game, it's a VDP feature used by some games to hide left-most column when horizontal scrolling is used because left-most column will display graphic artefacts in this case (this was a limitation of Master System hardware).

This is therefore accurate and expected behavior and I have no plan to change it. This could however be hacked in the frontend interface (by reducing the viewport width when detecting this VDP feature is enabled by the game), see https://github.com/libretro/Genesis-Plus-GX/issues/218. The downside with such hack is that the display aspect ratio becomes slightly when the left column is hidden because the screen is slightly too much stretched to compensate the missing 8 pixels.

**Comment by Cibomatto2002** [comment]
Thanks for your time and this great Emulator :)

**Comment by SimpleTease** [comment]
What about a libretro.cpp option that does 8px display cropping on both sides to simulate overscan? Core internals won't need to be changed at all, just some framebuffer ptr moving when sent to frontend. I've seen this in NES and A2600 cores.

**Comment by ekeeke** [comment]
FYI, optional left-most + right-most columns cropping has been added in libretro port through pull request https://github.com/ekeeke/Genesis-Plus-GX/pull/351

**Comment by Cibomatto2002** [comment]
Thank you.
