### ISSUE TITLE
Weird FM at Japanese Master System Bios. 

### ISSUE THREAD

**Issue by TesterNes** [ekeeke/Genesis-Plus-GX#352]
Running the Japanese master system bios (FM Space Harrier theme) results in some strange changes in sound sample rates or so it seems by hearing. 
You will notice it within seconds of starting the song.
Retroarch and core are updated under Windows 10 64 bits.

**Comment by ekeeke** [comment]
Indeed, it seems one note is played at the wrong pitch for some reason, most likely some inaccuracy in MAME YM2413 implementation but I never noticed it before (probably because I'm not much familiar with that song).

This is fixed if you switch "Master System FM (YM2413) core" setting to "nuked" instead of "mame".

**Comment by TesterNes** [comment]
Oh, I didn't see that option cause it is not implemented in the 64 bits version of the core.

**Comment by ekeeke** [comment]
It might be because the nuked core addition has not yet been backported by libretro. You should be able to find up-to-date 64-bit build (not compiled by me) here: https://mega.nz/folder/rgEVzAZK#uo-JSeS_abL94eE9xaNc6w

**Comment by TesterNes** [comment]
thanks for the link and thank you very much for the work of all these years.

**Comment by ekeeke** [comment]
This one took me some time to debug but I finally found where the problem was in MAME YM2413 core.
This should be now fixed by https://github.com/ekeeke/Genesis-Plus-GX/commit/305f89489e712210271b2984af86d91c38eba750
