### ISSUE TITLE
Snatcher (Sega CD) - FM audio is weird when using Nuked cores

### ISSUE THREAD

**Issue by ColonelShults** [ekeeke/Genesis-Plus-GX#355]
https://youtu.be/e2hf6XBRIk0
Doesn't matter which one of the nuked cores, starts with Konami logo and obvious in-game.
Sounds fine with MAME cores.

Tested in Retroarch win x64 and android versions.

**Comment by TesterNes** [comment]
Do you have the cpu speed beyond 100%?

**Comment by ekeeke** [comment]
I just tested with latest 32-bit build on my repository and the Konami logo sounds fine with nuked ym2612 core so there is no emulation issue with this core.

Your issue is likely caused by some experimental feature you activated in retroarch (like runahead or rewind) / in the core (like cpu overclock).

**Comment by ColonelShults** [comment]
Yes, that was Cpu overclock, sorry I thought I was running on default settings, thank you!
