### ISSUE TITLE
Something doesn't work well (Lord of the Sword)

### ISSUE THREAD

**Issue by AlanRibas** [ekeeke/Genesis-Plus-GX#361]
Hey guys.
There is a game I like a lot. his name is : "Lord of the Sword" (Master System).

I tried to finish this game my whole childhood. But the game is difficult, there was no map and I was a very bad player !!! Hahahaha

I decided to play it! I searched among the cores of the retroarch which would be ideal for the Master System.
The result was that I chose the "Genesis-Plus-GX" core.

However I started to play the game but something was not right. I started to pay a little more attention and realized that the sound was quite different.
Another detail that made me stop playing the game is the moment when you kill an enemy in the game. In the Master System video game I had, when hitting the opponent he blinked on the screen quickly, indicating that he was hit and then disappeared.
Using the "Genesis-Plus-GX" emulator this does not happen, in addition to the sound being different, enemies when hit are instantly disappeared. Which makes the whole experience bad, because the impression of a downed opponent does not exist like that. Something is missing. Whoever played the original video game knows what I'm talking about.
In view of this I started to question the emulation of "Genesis-Plus-GX" for all those games that I had not yet known. I may be missing out on much of the experience that the game has to offer me.

Out of curiosity I downloaded the Mednaffen emulator. And I was very happy when the game ran exactly the way I had experienced it in my childhood.

I searched but I couldn't find any nucleus that has the Mednaffen emulator running the Master System.
At least I didn't find it.
Do you recommend another core to me?

For if you are curious to play the game for 2 minutes in both "Genesis-Plus-GX" and "Mednaffen" emulators you will see what I am talking about. The game at the core of "Genesis-Plus-GX" falls short in a point that discouraged me from playing the game.

But as I configured all my emulators on the retroarch I would like to know if there is a alternative core. Or if there is really a mednaffen core that wants to run the master system and I don't know?
<img width="800" alt="A" src="https://user-images.githubusercontent.com/16063712/114802259-c9f4de00-9d73-11eb-973c-d4af9e9b8d1d.png">

I tried the following cores:

PicoDrive = The game has a bug that is impossible to play.
smsplus_libretro = The same thing as the Genesis Plus GX.
GearSystem = The sound is exactly the same as the original video game but the transition of the enemies when they are slaughtered is also the same as the Genesis Plus GX.

**Comment by ekeeke** [comment]
If this happens in every Retroarch Master System cores, this looks more like an issue with Retroarch than an issue with a specific core. I am not affiliated to Retroarch / Libretro so I cannot really help you with your Retroarch 'experience' or answer your questions about an alternate core since I'm only maintaining Genesis Plus GX emulator, which is used outside the Retroarch project.

Too me, it looks like some frames are skipped, which results in the blinking effect not being visible. Do you have runahead enabled in Retroarch ? Maybe try to disable it as this hacks the way original games checked for pressed buttons and might introduce such bug.

As for the different sound, this is likely due to the fact this game supports YM2413 FM chip and emulation of this sound chip is automatically activated for this game. You can force it to disabled in the libretro core settings if you prefer the original but simpler PSG sound.

**Comment by ekeeke** [comment]
Tried quickly my standalone SDL port as well as the latest Genesis Plus GX libretro core in Retroarch 1.8.5 (w32) and there is no issue, enemy sprites are blinking when being hit. See attached video dump (with Master System FM option set to OFF to get the original music): 

This confirms what  you are experiencing is caused by the Retroarch settings you are using and is not a core issue (could be the runahead feature as explained above or video sync settings but I'm no Retroarch dev so you should seek support from Retroarch team).


https://user-images.githubusercontent.com/717091/114869458-48df2a80-9df7-11eb-8fdb-06d74a9dc70f.mov

**Comment by AlanRibas** [comment]
Thank you so much for your help ekeeke !!
I disabled the sound chip in the menu and it is now exactly the same as what I heard on my video game.
I don't know about you ... but the the sound of the sword, the jump and the sound of the arrow like that for me is "more real". But it may just be nostalgia talking. I do not know. Hahahaha..

The "runahead" option is turned off in my options. So it must be something else that is causing it. Here the enemy disappears instantly.

A doubt. If I turn on the "runahead" option but set the number of frames to "0", will there be any difference in relation to the latency of the controls?

**Comment by ekeeke** [comment]
No idea. As I said, you should seek support for Retroarch from Retroarch developers, this place is only for issues relative to Genesis Plus GX emulator.

**Comment by AlanRibas** [comment]
I understand. Thank you very much for your help!!!!!!!! :-)

Em sex, 16 de abr de 2021 03:01, ekeeke ***@***.***> escreveu:

**Comment by AlanRibas** [comment]
Good afternoon ekeeke.
I was making some more purchases between the emulation of "Genesis Plus GX" in RetroArch and the emulator alone called "mednafen".
And I realized the following.

Using "Genesis Plus GX":
When we walk with the character, the scene that passes by moves in a locked way. I can see the picture of the scene walking in a non-fluid way.

Using Mednafen:
The background scenario moves smoothly. The only thing I noticed was that the vegetation that we found right when we left the first city, it becomes a darker color during the character's movement and returns to normal color when the scenery stops walking.

Could you test it out there and tell me if you find the same phenomenon?

**Comment by AlanRibas** [comment]
Good afternoon ekeeke.
I was making some more purchases between the emulation of "Genesis Plus GX" in RetroArch and the emulator alone called "mednafen".
And I realized the following.

Using "Genesis Plus GX":
When we walk with the character, the scene that passes by moves in a locked way. I can see the picture of the scene walking in a non-fluid way.

Using Mednafen:
The background scenario moves smoothly. The only thing I noticed was that the vegetation that we found right when we left the first city, it becomes a darker color during the character's movement and returns to normal color when the scenery stops walking.

Could you test it out there and tell me if you find the same phenomenon?

**Comment by ekeeke** [comment]
I am not going to test anything again, I already did and even uploaded a video capture showing there were no issues with the emulator core and your issue was likely with your Retroarch setup.

Again, this is not the place for Retroarch/Libretro support and you should ask the people who develop/maintain the program you are having issues with, not me, but non-smooth animation or scrolling is generally a sign of vsync issues in the frontend (i.e Retroarch in your case), which would also explain your original issue, as stated in previous posts.
