### ISSUE TITLE
SEGA Channel except for the prototype is broken in Genesis Plus GX

### ISSUE THREAD

**Issue by getCursorsExe** [ekeeke/Genesis-Plus-GX#374]
The unusual ROM, SEGA Channel, is broken in Genesis Plus GX. What's even weirder is that it is listed in game databases (both in RetroArch and BizHawk), and if you use a RAM debugger tool, then you will see at the end of the RAM bytes 2608 003C 0000 copying up all the way to the beginning of the RAM. 

The prototype release of SEGA Channel works, unlike the final.

![image](https://user-images.githubusercontent.com/39802077/125852379-68b565db-b072-4c4f-bc49-85a8e729bfbd.png)

Now, BlastEM, more accurate core, also has the exact same problem.

**Comment by ekeeke** [comment]
>What's even weirder is that it is listed in game databases 

The game being listed in a frontend database is not a guarantee that it was tested in emulators.

Sega Channel official ROM dumps needs Sega Channel hardware to be emulated obviously, which no emulators is able to emulate afaik, due to the lack of technical information but also the fact that the service is not available anymore so, even if the hardware itself was reverse-engineered, it is useless without the data stream coming from Sega servers.

>The prototype release of SEGA Channel works, unlike the final.

Those prototype ROM dumps are actually demo programs that do not require the Sega Channel.

**Comment by getCursorsExe** [comment]
Something about it is that in reality, bytes 2608 003C 0000 are actually _copying up_ every second all the way to the beginning of the RAM, which is not intended for any ROM to work that way. PicoDrive is the only libretro core that can properly boot up ROMs like this without any issues, but you will get a message saying that the signal cannot be processed.

**Comment by getCursorsExe** [comment]
Maybe if someone could script an extension to the core that allows SEGA Channel to function... I don't know.
