### ISSUE TITLE
LCD Ghosting Filter Effect is reset by savestates rather than being saved. (libretro)

### ISSUE THREAD

**Issue by getCursorsExe** [ekeeke/Genesis-Plus-GX#377]
The LCD Ghosting Filter, available in Libretro, is reset when a savestate is loaded. I don't know why.

**Comment by ekeeke** [comment]
Yes, that is expected as the LCD ghosting filter relies on the previously rendered frame pixels data but, since this would make savestate way too huge (one frame can be up to 720x480x4bytes if using 32-bit pixel output), the previous frame data is not saved when saving state (and is reset to 0 when loading state).

It should not really matter as the effect will work normally starting from the next frame so this should barely be noticeable and not be really an annoyance.

Frontend is free to save/load previous frame data (bitmap.data) around the core save/load function if they want but I won't do this in the core save/load functions for aforementionned reasons.
