### ISSUE TITLE
[Request] TMS9918a Color Palette Correction optional

### ISSUE THREAD

**Issue by FeRcHuLeS** [ekeeke/Genesis-Plus-GX#379]
The systems beyond the SG1000 convert the TMS9918a colors into approximate equivalents resulting in darker colors sometimes they fit sometimes are weird, so I make a request to have the TMS9918a lighter palette as backward compatible of the SG1000 and for the MSX, Colecovision conversions as optional.

There are hardware modifications + patches on the Game Gear to acomplish this, the Everdrive GG X7 can play SG1000 games while this core shows them blackscreen but sound on, not sure if that flashcart can have the TMS9918a color palette as I don't own it.

**Comment by ekeeke** [comment]
TMS9918 color palette is already used by default if you emulate SG-1000 hardware, that is if you load a .sg file and have config.system set to 0 (AUTO) or SYSTEM_SG so I am not sure to understand what you are requesting ?

The Master System (all models) indeed uses a different hard-wired color palette when vdp modes 0-3 (which are the TMS9918 compatibility modes) are used (so SG-1000 games look a bit differently than on original hardware) while the Game Gear requires you to initialize your own palette in color RAM (so SG-1000 games will be displayed as black by default unless you use a modified boot rom that initializes color ram first).

The Mega Drive hardware does not support TM9918-compatible video modes and will not display any SG-1000 game or Master System game that uses VDP modes 0-3 (I only know one Master System game that does that).

**Comment by FeRcHuLeS** [comment]
What I meant is that TMS9918a palette to be available as optional when system is set to another system (Mark III, Master System,...) compatible with those video modes beyond SG1000 so conversions from MSX or Colecovision or even backward compatibility with the SG1000, as example set system to Master System and have the lighter palette (the original color palette for those games/conversions) instead of the approximate equivalents colors that are darker making hard to play because of the dark colors nature.

**Comment by ekeeke** [comment]
I see, so this is only for MSX conversions that need Master System extra RAM (Colecovision conversions should work on SG-1000 II hardware with 2KB RAM and SG-1000 games don't need that, as explained above) and what you are requesting is emulating some kind of mixed hardware that uses Master System memory map with MSX legacy video hardware (TMS9918).

Sorry but at this point, if you want these games to look closer to MSX originals in emulators, you should as well play them in a MSX emulator. Iunderstand these could be interesting for those with flashcarts who play on real Master System hardware but I don't see the need to add emulation of such 'hybrid' hardware in a Master System emulator when accurate MSX emulators already exist and I would prefer not hacking the existing emulation code for this.

**Comment by FeRcHuLeS** [comment]
The nature of this request was to redeem the VDP in some way as the choice to desing it that way for the Mark III was not faithful to what the SG1000 palette offered, this is about how the SG1000 backward compatibility should have been, the Colecovsion, MSX conversions came afterwards, this is not about creating by emulation a kind of hybrid system but just make the SG1000 palette optional and available to another systems, so if  System is set to another but the SG1000/II then keep those light colors, in fact there are filters doing something similar as NTSC filters like the monochrome one.

Color palettes choices are common among cores for NES, GB even GBC and GBA in the latter is named Color Correction that should be the way I had named this issue, looking at the aforementioned filters this request could be simulated at least as a filter maybe.

**Comment by ekeeke** [comment]
Again:
- if you want SG-1000 games or Colecovision conversion to display original colors, you can do it on SG-1000 II hardware, which is already accurately emulated by this emulator
- if you want MSX conversion to display original colors, it is not possible with real Master System hardware and I won't add this option in this emulator as it's more practical to play these games in  a MSX emulator to get accurate comors and sound at this point

Selectable color palette in NES emulators is a different thing, which is because NES PPU afaik did not output RGB so the colors depended a lot on the vidro signal quality, TV quality, etc.... this is not the case with Master System hardware: TMS modes palette is fixed in hardware and there is no way to output original TMS colors unless you add a TMS9918 chip and therefore make some kind of hybrid system.

**Comment by ekeeke** [comment]
Note that it should be possible to somehow play these MSX conversions with more accurate colors in Game Gear MS compatibility mode (which Genesis Plus GX automatically emulates in full screen mode when system hardware is forced to Game Gear and you load a .sms or .sg ROM file) or in Game Gear mode with extended display option enabled (ROM files would need to be renamed as .gg though) if either these hacks are modified to first initialize CRAM with a color palette closer to original (easier in Game Gear mode which allows 12-bit RGB colors) or if someone makes a Game Gear boot ROM that does the same and you enable system bootrom in emulator settings.

**Comment by FeRcHuLeS** [comment]
All that explanation is valuable, and handy please let me ask you since the VDP can't do it, is there the chance a filter can?, a rudimentary way to solve this is by adjusting the TV by decreasing the Color and increasing the Brightness the results are fairly acceptable colors for almost the 16 colors but the dark yellow, maybe a combination of hue, gamma, digital vibrance, brightness, contrast, color and saturation can result in acceptable colors requiring a custom configuration of the TV set just for this. 

So could you consider an approximate colors filter for this? beyond the fact patched Game Gear games or MSX cores can do it. Not being an expert in colors I don't know if such a thing is posible to be made within this core.

**Comment by ekeeke** [comment]
No, fixing color palette is not doable with a filter.

An alternate solution could be to run these MSX conversion games on SG-1000 hardware with the existing SG-1000 II 
 cart adapter that extends internal RAM to 8KB, which makes the RAM capacity and mapping identical to Master System hardware (and is already emulated by Genesis Plus GX as it is required by some "official" MSX to SG-1000 conversions).

The emulator would only need to be modified to add the possibility (though existing lock-on option for example) to force use of such RAM extension adapter when SG-1000 hardware is emulated (currently this is only enabled automatically when the few known SG-1000 games that rely on it are detected).

This solution is preferred because it is something that is theoretically possible with real hardware (providing you have the RAM extension adapter and a SG-1000 flashcart) and does not require hacking the emulator codebase or major modifications to emulator design.

**Comment by FeRcHuLeS** [comment]
It is fairly possible a filter simulating the colors of the TMS9918a since available filters to this core do something similar reliying on color parameters not related to emulated hardware accuracy to simulate effects, therefore It would result in an approximate to what the TMS9918a offers thus not perfect, but acceptable at least.

The monochrome one for example is like the Color value is set to zero while the TMS9918a effect would basically be by decreasing the Color and increasing the Brightness both a fraction, being the dark yellow and dark gray of the palette difficult to adjust by just these tweaks of Color and Brightness, all the solutions posted are useful but unrelated to the nature of this request then how can a filter simulating the TMS9918a impact the core accuracy in the end.

**Comment by ekeeke** [comment]
I won't implement a TV filter to adjust color brightness (you can just use your TV or monitor settings for that) and again, no, you won't be able to correct the Master System hard-wired palette for TMS modes to better match originalTMS9918 colors with a simple filter, what you are saying makes absolutely no sense, sorry.

**Comment by SuperMarioFan2007** [comment]
TMS9918 Is Already On SG-1000 Emulation

Game Gear & Genesis Uses Black Display On SG-1000 Games
