### ISSUE TITLE
CHD Support fot SEGA CD MD+

### ISSUE THREAD

**Issue by bebess** [ekeeke/Genesis-Plus-GX#394]
as mentionned in https://github.com/ekeeke/Genesis-Plus-GX/issues/393

support the ..CHD format when loading a SEGA CD MD+

it don't automatically load associated chd file when loading a ROM file
https://github.com/ekeeke/Genesis-Plus-GX/issues/393#issuecomment-931606399

**Comment by ekeeke** [comment]
Added in https://github.com/ekeeke/Genesis-Plus-GX/commit/83a225cd324312fb4fd045776590019a059920a6

This affects both MSU-MD (CD Mode 1) and MD+ (MegaSD) games.

For MD+, as the MegaSD specific loop command in CUE files are obviously not in CHD files anymore, the only limitations are that:
- you have to set "CD add-on" setting (in core options if you use libretro core) to MEGASD instead of AUTO to enable MegaSD CD hardware overlay emulation
- audio track loops might not work as intended when playing the game

**Comment by bebess** [comment]
@ekeeke hmm i test with the e852fc2 release and it doesn(t work for me

i do all you say :
cd addon in option is in megasd mode
game.zip (contain the rom)
game.chd (contain the compressed cue+bin)

with cue+bin it work but not with chd

**Comment by ekeeke** [comment]
The latest changes from my repository have not yet been merged to libretto repository.

You will have to wait that the core changes are merged by libretro/retroarch dev team.

**Comment by ekeeke** [comment]
Yes
