### ISSUE TITLE
Some cutscenes in Aladdin aren't shown

### ISSUE THREAD

**Issue by Tasosgemah** [ekeeke/Genesis-Plus-GX#400]
I'm at Jaffar's Palace (i think the last level) and made a save state before it. Before the level starts there's a cutscene that appears for a fraction of a second and then goes away as if i'm skipping it, though i'm not doing such thing.

Here's the save state file (the bonus level before the cutscene)

[Aladdin (USA).zip](https://github.com/ekeeke/Genesis-Plus-GX/files/7576691/Aladdin.USA.zip)

I'm not sure if this happens with other cutscenes though.

**Comment by ekeeke** [comment]
I jumped to this level using cheat code (I cannot use your state file as I guess it is for the 64-bit version of Retroarch) with latest libretro core in Retroarch and the cutscene runs as expected (see attached recording).

Your issue is very likely caused by some Retroarch misconfiguration on your side or you using some Retroarch specific hack like CPU overclock or Run-Ahead that mess with the game inputs processing and acts as if emulated controller was pressed.

https://user-images.githubusercontent.com/717091/143094535-70dd77fb-25f9-40fb-9080-88ccd146c7a1.mp4

**Comment by Tasosgemah** [comment]
Weird. I have none of these RA options enabled. And my core settings are the defaults...
