### ISSUE TITLE
Wrong colors in Dr. Hello (SMS)

### ISSUE THREAD

**Issue by vaguerant** [ekeeke/Genesis-Plus-GX#406]
`Dr. Hello (Korea) (Unl).sms` (No-Intro naming) has bad colors in Genesis Plus GX:

![Dr  Hello (Korea) (Unl)-220120-023510](https://user-images.githubusercontent.com/5259025/150163907-edad5ae1-88b7-4765-b908-c6e5df684606.png)
![Dr  Hello (Korea) (Unl)-220120-023530](https://user-images.githubusercontent.com/5259025/150163914-fbc0577b-c27f-4a2c-aa01-d9c1009b966b.png)

Compare to the screenshots on SMSPower:

![SMSPowerDH-Title](https://www.smspower.org/uploads/Screenshots/DrHello-SMS-KR-TitleScreen.png)
![SMSPowerDH-Gameplay](https://www.smspower.org/uploads/Screenshots/DrHello-SMS-KR-4.png)

Running the game in SG-1000 mode seems to fix the colors but the game crashes before you can even start playing. I don't know enough about the SG-1000 and SMS to speculate what that means.

Tested on libretro/Genesis-Plus-GX@c1c605e.

**Comment by vaguerant** [comment]
Never mind, apparently this is accurate to what the game looks like on real hardware. It uses the legacy SG-1000 video mode on the SMS, which just looks broken like that. However, it presumably also needs the extra RAM of the SMS, so it can't be played in true SG-1000 mode.

Perhaps an (inaccurate) enhanced legacy palette for SG-1000 video mode on SMS could be added to GPGX? Where games use the real SG-1000 palette instead of the SMS's legacy palette?

**Comment by ekeeke** [comment]
Indeed, that screenshot was taken from an emulator (Kega Fusion probably) which does not emulate the specific TMS mode colors of the Master System VDP. And this game is actually a Master System game so yes, it is not compatible with SG-1000 hardware because of the limited RAM.

Having an option to force TMS9918 color palette in Master System VDP was already proposed I think (for playing those MSX2SMS hacks from what I remember) but I don't really like this idea as it is kinda inaccurate and emulates a system that does not exist (and can not be achieved by modding Master System hardware).

A much better solution in my opinion would be to use existing options  (either System Hardware or Lock-On) to let user enable the SG-1000 RAM cartridgewhen emulating SG-1000 hardware: it is a cartridge adapter that was required by some SG-1000 games (mostly MSX conversions) to extend SG-1000 hardware RAM up to 8KB (same as Master System hardware) and is already supported by this emulator (but only activated for the few games that require it atm).

**Comment by SuperMarioFan2007** [comment]
Sega SG-1000 Mode Uses Light Color (Z80 TMS9918)
Sega Master System / Game Gear Uses Dark Color (Z80A)
Sega Genesis Uses Black Screen With Audio On SG-1000 Games (Z80B)
