### ISSUE TITLE
(Genesis Plus GX 1.7.6) Request:

### ISSUE THREAD

**Issue by ghost** [ekeeke/Genesis-Plus-GX#416]
Fix Bug On Super Boy I., Super Boy II., Super Boy III. On SG-1000, SG-1000 II Emulation.
![Screenshot_20220304-214226~2](https://user-images.githubusercontent.com/99989661/156840091-ae84839e-089f-474c-a453-f24df0ba0239.jpg)
![Screenshot_20220304-214248~2](https://user-images.githubusercontent.com/99989661/156840105-b869a04f-74a2-4486-a377-ed362dc25dd3.jpg)
![Screenshot_20220304-214348~2](https://user-images.githubusercontent.com/99989661/156840122-647f9344-1a5c-4852-b25b-75d8b2ce365e.jpg)
![Screenshot_20220304-214442~2](https://user-images.githubusercontent.com/99989661/156840129-4a87bf25-63b8-4a0f-8b05-fe7f59d46cd1.jpg)
![Screenshot_20220304-214520~2](https://user-images.githubusercontent.com/99989661/156840133-ec7822c4-e0f4-4c82-b3a3-33396583dcd3.jpg)
![Screenshot_20220304-214550~2](https://user-images.githubusercontent.com/99989661/156840140-560f34d4-bcb1-46e3-aadf-395b2e4400d9.jpg)

**Comment by ekeeke** [comment]
Those are Master System games, they need the 8KB RAM present in Master System and therefore can not work in SG-1000 or SG-1000 II hardware

**Comment by DVDVIDE** [comment]
@SopTheSop2022 It Can Work On SG-1000 On Some Emulator Cores: KEGA Fusion, PicoDrive, Gearsystem, SMS Plus GX.
KEGA Fusion Is Most Accurate Emulator Core.

**Comment by ekeeke** [comment]
Those are Master System games (with .sms file extension). They don't work on SG-1000 hardware because SG-1000 hardware normally has only 1KB or 2KB of internal RAM, while these games use 8KB of RAM,  hence why they  freeze if you try to force the emulated system to SG-1000 (afaik, only this emulator lets you do this, the emulators you quoted automatically select the emulated system based on file extension).

They work on Master System hardware but they use a legacy video mode that is similar to the one  in  SG-1000 video hardware. The Master System video hardware is back compayible with this legacy video mode (called TMS mode) but use a darker color palette than the SG-1000 video hardware.

This is accurately emulated in this emulator but not in Kega Fusion for example, which always use the TMS legacy color palette afaik. Some emulators might have an option to switch between the two palettes but it's not really accurate and more some kind of hack.

A more accurate alternative to have a TMS color palette in these Master System games that use legacy video mode would be to extend the lock-on option to allow the use of 8KB RAM extension cart adapter (which is required by some SG-1000 games and already emulated automatically when those are played). With 8KB RAM extension adapter, these Master System games wouldbe playable on SG-1000 hardware as they don't seem to use any other Master System specific feature.

**Comment by DVDVIDE** [comment]
@ekeeke @SopTheSop2022 It Can Work On SG-1000 On SMS Plus GX Emulator Core, NOT On Genesis Plus GX. SG-1000 Has 1KB or 2KB Of Internal, games uses 8KB RAM.
KEGA Fusion Uses SG-1000 TMS COLOR On SG-1000, Master System, Game Gear, Genesis / Megadrive Emulation On SG-1000 Games

**Comment by SuperMarioFan2007** [comment]
@DVDVIDE Yes
