### ISSUE TITLE
Fix bugs on Korean MSX Conversion To SMS games On SG-1000 Mode Emulation

### ISSUE THREAD

**Issue by MrKrabs07** [ekeeke/Genesis-Plus-GX#431]
Bug:
![168426478-19e640b6-d2c5-4bb4-b307-1c736fc22aaa](https://user-images.githubusercontent.com/105190447/168464399-a712258c-27ab-4230-9cfd-a425e3252b97.jpg)
![168426489-68094b63-dd8a-43fa-bba7-8ce8b76f53b7](https://user-images.githubusercontent.com/105190447/168464402-b21a1f4e-5013-4526-ae4f-c45072d19a2d.jpg)
![168426499-11534212-7e93-4128-a7c9-23d97efa1a3a](https://user-images.githubusercontent.com/105190447/168464407-4a030fe4-b785-449b-9b7d-0ff4eee98047.jpg)

Fixed:
![168426558-d89354ff-b41b-470a-8076-a6583ab8abbf](https://user-images.githubusercontent.com/105190447/168464418-2abdea3a-abe9-4700-bc41-fcbfb7e0cbb8.jpg)
![168426585-5842bd13-4c39-42fa-8679-186101233835](https://user-images.githubusercontent.com/105190447/168464420-c8611e39-898a-4a8a-ba9a-63c89240f793.jpg)
![168426617-aba13656-ac8f-49e8-b58a-c2198fffe84f](https://user-images.githubusercontent.com/105190447/168464422-5f70b7be-9000-4903-a68a-3b00d021a256.jpg)

You must add Feature of RAM

SG-1000/SG-1000 II RAM:

> 1KB

> 2KB

> 4KB

> 8KB

> 16KB

> 32KB

> 64KB

> 128KB

> 256KB

> 512KB

> 1MB

> 2MB

> 4MB

> 8MB

> 16MB

> 32MB

> 64MB

Master System/Mark III/Master System II RAM:

> 1KB

> 2KB

> 4KB

> 8KB

> 16KB

> 32KB

> 64KB

> 128KB

> 256KB

> 512KB

> 1MB

> 2MB

> 4MB

> 8MB

> 16MB

> 32MB

> 64MB

Game Gear RAM:

> 1KB

> 2KB

> 4KB

> 8KB

> 16KB

> 32KB

> 64KB

> 128KB

> 256KB

> 512KB

> 1MB

> 2MB

> 4MB

> 8MB

> 16MB

> 32MB

> 64MB

Genesis / Mega Drive / CD RAM:

> 1KB

> 2KB

> 4KB

> 8KB

> 16KB

> 32KB

> 64KB

> 128KB

> 256KB

> 512KB

> 1MB

> 2MB

> 4MB

> 8MB

> 16MB

> 32MB

> 64MB

**Comment by AlbertoDiazC** [comment]
Reported. Don't you get tired of this? If you want support for a corner case, fork the code and do it yourself.
If the main developer abandons this great project, it will be because of you. You're boring stones.

**Comment by ekeeke** [comment]
I am considering closing the issue reports for good, too bad for other people but this constant trolling (or maybe it is just some foem of autism, I don't know... and don't care) is too annoying.

He has been reported at least twice to github but still comes back after a while. He is also apparently doing the same in other emulators repisitory, looking at the user history.

**Comment by KMFDManic** [comment]
@ekeeke for the record, I am autistic.  But, I would never go out of my way to harass someone like this individual has done.  Usually, when someone bullies someone online, from a psychological standpoint, it is because they are trying to fill the gap over something they have no control over in life, be it divorce, problems with friends or family, etc.  

There are certainly better things to do with one's free time.  Just don't let this stuff get you down.  
I have dealt with my own share of bullies when working on various online projects.  But, you just gotta keep strong in mind at all times.  And, you will prevail.

When I first got into working with the Mini Classics, another team decided to try to push me out of the scene with various tactics.  In the end, me just being me, being nice to everyone, had way more people supporting my unorthodox and creative solutions and workarounds, emulation wise, and I am satisfied with the current state of things.

If you like movies or tv shows, find something you've been meaning to watch!  Just know, people like me will always have your back and appreciate what efforts you put forth in anything and all you do, whether or not they are autistic:)

**Comment by SquidwardKrabs** [comment]
@MrKrabs07 Stop spamming the same request.

The spam links:

#432 
#430 
#425 
#422 
#420 
#419 
#417 
#416 
#415 
#414 
#413 

Those are Master System games (with .sms file extension) They don't work on SG-1000 Hardware because SG-1000 has 1KB or 2KB RAM but they need 8KB Before. Master System & Game Gear mode with TMS9918 mode is Incorrect by SMS Plus. Including SMS Plus GX, Kega Fusion, MEKA, Gearsystem Always uses TMS9918. Gearsystem, Kega Fusion, MEKA, SMS Plus's SG-1000 Uses 16KB RAM.

The color look wrong on TMS9918 Content on Master System & Game Gear Hardware. Black Screen On Genesis/Mega Drive Hardware. Genesis/Mega Drive Has No TMS9918-Compatible. Master System Has 256-Colors (Z80 CPU). Like CRT TV CPUs Uses Z80.

**RULES:**

1. No spamming

2. No Not Safe For Work Content

3. No Copyrighted Content

@ekeeke Please lock this conversation and delete issue #432 #425 #422 #420 #419 #417 #416 #415 #414 #413

**Comment by KMFDManic** [comment]
@SquidwardKrabs we all know it's just you under another account.  It is so very nice to see you are such an upstanding individual that you spend all of your free time playing mental games.  You realize, if you keep this up, you will only make it so  ekeeke and others no longer have interest in bettering these emulators for the thousands upon thousands of people that use them.  There are far better things you can do with your free time than bullying others online.

Also note, what you are doing is actually a crime, which can land you in jail if you keep it up.  

@ekeeke Sorry to see you have to go through this nonsense due to an obviously mentally unstable individual who truly needs to get help.
