### ISSUE TITLE
Add configurable ROM Mapping in Master System

### ISSUE THREAD

**Issue by ghost** [ekeeke/Genesis-Plus-GX#440]
ROM Mapping (Choose which ROM mapper the core should apply. 'Auto' will work for a wide range of content, but in some cases automatic detection fails)

> Auto
> SEGA
> Codemasters
> Korea
> Korea MSX
> Korea X-in-1
> Korea 4-Pak
> Korea Janggun
> Korea Nemesis
> Taiwan 8K RAM

from PicoDrive emulator

**Comment by birdybro** [comment]
There's already a bunch of ROM mapping.

https://github.com/ekeeke/Genesis-Plus-GX/tree/master/core/cart_hw

**Comment by ekeeke** [comment]
>but in some cases automatic detection fails

In what cases does it fails ? I prefer adding unrecognized games to the existing internal database rather than adding a setting to manually pick one of the 20 (or so) supported mappers with some obscure mapper naming, especially when the number of games using non-Sega mapper on Master System is very limited and not really going to grow.

**Comment by ekeeke** [comment]
>from PicoDrive emulator

Looking a bit more into it, this setting makes some kind of sense for Picodrive as it does not use an internal ROM database to detect specific game mappers but instead use some code heuristics that might indeed fail for some games.

This is not the case for this emulator since we are using an internal ROM database so such setting does not make much sense here.

Closing this as, as far I know, all the known master system games dumped that use a custom mapper are listed in Genesis Plus GX data base (see https://github.com/ekeeke/Genesis-Plus-GX/blob/master/core/cart_hw/sms_cart.c#L80)
