### ISSUE TITLE
libretro unplayable games

### ISSUE THREAD

**Issue by AngelofMe** [ekeeke/Genesis-Plus-GX#446]
because the emulator's code contains these files
these games are meant to be run by emulators

Genesis-Plus-GX/core/input_hw
activator
terebi_oekaki

**Comment by ekeeke** [comment]
Terebi Oekaki tablet controller is emulated by the core and implemented in libretro frontend code through libretro mouse device (see https://github.com/ekeeke/Genesis-Plus-GX/libretro/libretro.c#L563) so it should work fine

'Activator' is not a game, it is a weird input device supported only in some games but it is hardly emulatable using traditional controller device (I emulate it in standalone gc/wii port iding two analog sticks but honestly, nobody wants to play the games like that, it is unplayable). It is not hooked in libretro code because of that and because the few games that supported activator were playable using normal controllers (3b or 6b control pad). I am not responsible for the libretro port so you will have to ask libretro team if you really need this feature.
