### ISSUE TITLE
Harsh background noise at the Monster World II's title screen

### ISSUE THREAD

**Issue by Mint128** [ekeeke/Genesis-Plus-GX#448]
Recent versions of GPGX introduced a continuous harsh noise at Monster World II's title screen. Older versions (like from early 2021 or so) are silent.

Comparison:

https://user-images.githubusercontent.com/110358354/182523773-8275a83c-e1cb-4250-86b1-8e3b0c21ec5a.mp4

https://user-images.githubusercontent.com/110358354/182523819-c0773b78-44a2-4527-933c-f9c0d488ce68.mp4

**Comment by ekeeke** [comment]
Indeed, this was a consequence of [this](https://github.com/ekeeke/Genesis-Plus-GX/commit/de47d1db5678780942af0a7891c76dce661783c9) change, which broke operator behavior when envelope generator is off (output should be silent, as indicated [here](https://github.com/ekeeke/Genesis-Plus-GX/blob/master/core/sound/opll.c#L880) in nuked OPLL core.

This has been fixed by https://github.com/ekeeke/Genesis-Plus-GX/commit/47d20265c9d7c26cc1062f105651c607dc0dacbf
