### ISSUE TITLE
Has an incorrect line at the bottom of screen for Yuu Yuu Hakusho - Makyou Toitsusen

### ISSUE THREAD

**Issue by Mengze-L** [ekeeke/Genesis-Plus-GX#462]
When I use RetroArch with Genesis-Plus-GX core to play with Yuu Yuu Hakusho - Makyou Toitsusen, I found an incorrect line shown at the bottom of the screen for most of the stages as below:

![Genesis_Plus_GX_4_1](https://user-images.githubusercontent.com/109141142/190842964-8164c226-a9fb-4775-8485-54752f1a7921.png)
![Genesis_Plus_GX_3](https://user-images.githubusercontent.com/109141142/190843387-97750aed-7706-4630-8b61-68179997ddbc.png)
![Genesis_Plus_GX_1](https://user-images.githubusercontent.com/109141142/190842972-689db79f-777e-4391-8ae2-66b28ebb3ae4.png)

But some stages do not have this issue like this one:

![Genesis_Plus_GX_5](https://user-images.githubusercontent.com/109141142/190843013-28256e93-4bf5-4503-a26e-21884f5826b1.png)

Also I tried the BizHawk with this core, it has the same output. So, I think it should be related to the core but not RetroArch. Pico also does not have this line at bottom for all stages.

And I compare the same game on standalone genesis emulator Gens+ 0.0.9.61. It does not have this issue. The screen shots are shown as below:

![Gens+_2](https://user-images.githubusercontent.com/109141142/190843077-3f1cdce3-8afe-4cea-9a26-de3705e53f19.png)
![Gens+_1](https://user-images.githubusercontent.com/109141142/190843079-4a00ef21-a355-4c44-a562-a55486d03134.png)

Does it an issue? Thanks!

**Comment by birdybro** [comment]
A good question to ask is, what does it do on original hardware?

**Comment by Mengze-L** [comment]
Good suggestion. I just took photo from my MD1 VA6 JAP NTSC system as below:

![IMG20220918082543](https://user-images.githubusercontent.com/109141142/190881500-488b004b-4864-4572-89a5-c92311af467b.jpg)
![IMG20220918082554](https://user-images.githubusercontent.com/109141142/190881505-a465dd2d-c2e2-4e01-9fd6-d619c77417f4.jpg)
![IMG20220918082533](https://user-images.githubusercontent.com/109141142/190881507-6824368b-f69e-4c4f-b484-e3cab41273e4.jpg)

I connected the system through the AV cable with my LCD TV. There is no incorrect line at the bottom. However, I do not know why there is border on the left and right. I can remember there is no border with the CRT. But I do not have CRT on hand. 

Also, today I tried to tune some parameters on RetroArch and found that the CPU overclock has some impact on the line at the bottom for this game on Genesis Plus GX. Hope it is helpful

125% overclock:
![Genesis_Plus_GX_6_1](https://user-images.githubusercontent.com/109141142/190881706-0e231e78-1252-42b9-8ab0-86c444d667c4.png)

150% overclock:
![Genesis_Plus_GX_7_1](https://user-images.githubusercontent.com/109141142/190881727-9e3e9e04-3e6b-484c-a22e-e685dff0366f.png)

**Comment by ekeeke** [comment]
Thanks for the report.

For the record, this games reduces the size of active screen by disabling the display before the last active line. This is done during HBLANK so there is no flickering and then the game also updates the border color (shown when display is disabled) shortly after disabling the display. This also occurs during HBLANK so that color chane is not visible.

This emulator supported display disable/enable during HBLANK but only supported changes to Color RAM during HBLANK for active lines (as I initially thought no games would change the border color mid line). This is now fixed by linked commit.

>And I compare the same game on standalone genesis emulator Gens+ 0.0.9.61. It does not have this issue.
Gens does not support mid-line changes to display enable status so it will disable the display for the next line (one line later than real hardware) so when border color is being shown, it is already changed to correct value.
