### ISSUE TITLE
mouse + keyboard and data recorder

### ISSUE THREAD

**Issue by soundsnow** [ekeeke/Genesis-Plus-GX#463]
https://github.com/Rakashazi/emu-ex-plus-alpha/issues/742

https://segaretro.org/Data_Recorder_SR-1000

**Comment by ekeeke** [comment]
@birdybro is correct about the mouse, it is already emulated so it is only a matter of configuring emulator input in proper port.

About the keyboard, it is a little bit more complicated than that. It is actually a saturn keyboard that indeed plugs in MD input port through a custom homebrew adapter but this game implements the protocol to read the keyboard keys from control port, it is not just a "keyboard to gamepad" converter. Anyway, just like SC-3000 computer or SK-1000 keyboard emulatoon, I have no plan to emulate keyboard in general. I think Blastem emulator supports it so you can use it if you really want to play this game using a keyboard.

About the SR-1000 data recorder, there is afaik no software that use it so it is impossible yo know jow it is supposed to work and no tape exclusive games dumped so no way to support tape format.  Its use is basically to load games from a tape instead of cartridge, which, from emulator point of view, makes zero difference.
