### ISSUE TITLE
enabling the j-cart multiplayer

### ISSUE THREAD

**Issue by janezkranjc** [ekeeke/Genesis-Plus-GX#47]
Hello

I would like to know what setting should I use to enable j-cart multiplayer in games such as pete sampras tennis?

**Comment by ekeeke** [comment]
There are no specific settings, player 3 and player 4 are automatically enabled in Genesis Plus GX for j-cart games. In standalone Wii version, you can configure them in controller settings menu. In retroarch, input settings normally let you configure each player too.

**Comment by janezkranjc** [comment]
I'm using retroarch on raspberry pi and by default it doesn't work.

I tried changing the User 2 Device type to MD Joypad 3 Button + 4-WayPlay
(which works in General Chaos, Fifa and NBA Jam) but it doesn't work in
Pete Sampras which uses j-cart - whatever I press on each controller,
nothing works.

**Comment by ekeeke** [comment]
4-wayplay is a multitap, it is not supported by j-cart games like Pete Sampras so enabling it makes no sense (also this reminds me multitaps should be moved to core options since it makes little sense to assign them to a player device).

Like I said, additional players are automatically enabled for j-cart games, there is nothing that you need to configure besides the input devices you want to be mapped to player 3 and player 4. As for emulated devices, leave MD joypad for all players and it should work. If it doesn't, i'm afraid it's a problem with retroarch and is not my concern.
