### ISSUE TITLE
Crash issue related to region switching

### ISSUE THREAD

**Issue by Sonia-7** [ekeeke/Genesis-Plus-GX#475]
Hello. I don't know if I should really be reporting this here, but I was told to do so from another repo so here I am. Instead of repeating everything that was posted there, I'll just point to the appropriate comment:
https://github.com/TASEmulators/BizHawk/issues/3482#issuecomment-1342088293

So yeah, the problem is in that thread and the last comment is detailing what's causing the crash. I wonder if it's something that can be fixed?

**Comment by ekeeke** [comment]
From the linked comment, it looks more like a misuse of audio_xxx functions control flow in libretro dedicated code (libretro.c) than a core issue. Surely I could add safeguards in all audio functions to prevent this but some of these functions (namely audio_set_rate and audio_update) can be called during emulation runtime so I would prefer not to have unnecessary   checks in them and have frontend developers properly respecting the control flow.

As I am not that well confident with libretro specific code (which is maintained by libretro devs, not me), I suggest you report this into libretro repository, under https://github.com/libretro/Genesis-Plus-GX/issues

Note that I am not sure (from the linked issue report) what the issue is, how to exactly reproduce it and if it actually occurs in every libretro frontend (including Retroarch) or is specific to Bizhawk use of libretro code, so you might want to clarify that as well when you report it.

**Comment by Sonia-7** [comment]
Not sure if you've noticed it (sorry if you have), but the issue got fixed over there, so it can be pushed into upstream here now.
