### ISSUE TITLE
Broken save state compatibility

### ISSUE THREAD

**Issue by clobber** [ekeeke/Genesis-Plus-GX#50]
In this commit r927/https://github.com/ekeeke/Genesis-Plus-GX/commit/ec554b4b702d337168dfcaf4b4a6248062e2db5b, compatibility broke with previous save states. Is it possible to have a conversion routine that would allow loading of save states before that commit? My implementation is based on r878 - I was going to ship an update with the latest here from upstream but I cannot do that if save states are broken for all users.

**Comment by ekeeke** [comment]
This update completely changed the timing of frame emulation, which changes a lot of assumptions usually not in savestates (since they are done between frames) and made it much more complicated too maintain compatibility with previous version. I am not even sure a conversion can be easily done and various other changes were made to savestate since this quite old revision, I'm definitively not going to write a converter for each possible outdated revision people are still using, sorry.
