### ISSUE TITLE
Sega/Mega CD issue with OGG audo playback

### ISSUE THREAD

**Issue by Zombie-Ryushu** [ekeeke/Genesis-Plus-GX#52]
I have occasional issues with OGG audio playable of CD Tracks. Sometimes CD tracks are passed as Waves, making you hear a bizzare racket on some tracks and sometimes not others. This is most often seen with Mortal Kombat CD  Also often Audio tracks only play once instead of looping when the track is finished. This is seen in Sonic CD

**Comment by ekeeke** [comment]
What version are you using ? Are you using CUE files ?
There was an issue when using OGG files through CUE file that could cause such issues when restarting or generally seeking within audio tracks but it was fixed in https://github.com/ekeeke/Genesis-Plus-GX/commit/a07f7a3d24e77d7a6ebdcbae6ca51bc19c539edb so make sure you are using the latest build.

**Comment by Zombie-Ryushu** [comment]
I am using CUE Files with OGGs,

**Comment by ekeeke** [comment]
You don't want to tell me what version of the emulator you are using or at least if you are using the latest compiled revision ?

**Comment by Zombie-Ryushu** [comment]
I rebuilt the latest GIT, and the result was a black screen. The BIOS never loaded.

**Comment by ekeeke** [comment]
This is a problem with your build, try to get it from retroarch nightly instead (it was never precised but I assume you use the libretro port).

As for your issue with OGG files, it was fixed in 1ee6648

**Comment by Zombie-Ryushu** [comment]
Yes, This was a Fresh checkout compiled under Rosa 2012.1 with gcc-4.7.4_2014.01 Is that supported?

**Comment by ekeeke** [comment]
I have no idea, you will have to ask libretro devs. Is this the first time you try to compile Genesis Plus GX core ?

All I know is that I compiled the libretro core with MinGW before committing the last changes and tested it with retroarch 1.0.0.2 windows 32-bit : it worked fine as usual with CD games. That compiled build is available here: https://github.com/ekeeke/Genesis-Plus-GX/blob/master/builds/genesis_plus_gx_libretro.dll

You could also upload the CUE file (including OGG files) that you have problem with so I can have a look when I got some time.

**Comment by Zombie-Ryushu** [comment]
Sorry I fell asleep, I'm running Rosa Linux 2012.1 and Rosa  Linux 2014.1 (Depending on the node in question.) I can of course upload the CUE Sheet I made, All of my CUE Sheets come from a master Template.

**Comment by Zombie-Ryushu** [comment]
https://abf.rosalinux.ru/build_lists/2506783 Here is a URL to the build I made, it contains an RPM, and an SRPM containing the source code. http://pastebin.com/F1C7xdAt Here is the OGG Cue sheet.

**Comment by ekeeke** [comment]
Like I said, I have zero idea about linux so this is chinese for me.

I can tell you that there are several mistakes in that CUE file though:

1) filename in FILE command must use double-quotes (" ") if there are any space characters being used => they are missing for the first (.iso) file

This explains the black screen on load (the emulator will fail to load the iso file as a CD track). This worked by chance in previous versions because the emulator would keep reading filename until "BINARY" keyword is detected but this can not be assumed anymore for first track since audio CD are now supported.

2) INDEX commands should always come AFTER the associated TRACK command and there should be one INDEX01 per TRACK: not sure why you formatted your CUE like this but you ended up missing one INDEX 01 command at the end for the last track (TRACK 35) so there is likely going to be playback issue for the last track (even with previous versions).

So, fix your CUE file(s) and it will likely works fine with last version.

But really, you need to understand that using CUE file like this with ISO + WAV or OGG files is absolutely unnecessary as it does not bring any additional value to emulator that it can't figure itself, so if your disc image does not come with a CUE, there is no point in trying to make one.

Just rename your ISO "Sonic CD.iso", delete your CUE file and load the ISO file: the emulator will automatically detect all tracks if named "Sonic CD_xx.ogg" with xx being track no. This actually works with any .iso file, providing the .wav or .ogg files are named like the .iso file with either "xx", " xx", "-xx", " - xx" or "_xx" suffix appended to their filename.

**Comment by Zombie-Ryushu** [comment]
I'll work on that and get back to you.

**Comment by Zombie-Ryushu** [comment]
Fixing the CUE Files resolved the problem. Thank you.

**Comment by romulof** [comment]
I'm having a similar problem using OpenEmu port.
CUE+ISO+WAV = glorious music
CUE+ISO+OGG = no music :(

Here's how my CUE file looks like:
```
FILE "Sonic CD.iso" BINARY
TRACK 01 MODE2/2352
INDEX 01 00:00:00

FILE "Sonic CD #02.ogg" OGG
TRACK 02 AUDIO
INDEX 01 00:00:00

FILE "Sonic CD #03.ogg" OGG
TRACK 03 AUDIO
INDEX 01 00:00:00
...
```

**Comment by ekeeke** [comment]
Not the same problem though, yours is that game plays fine but without any music, which is different.

This could be a problem with Open Emu file library not liking '#´ character in filenames or just that Genesis Plus GX core in Open Emu is not compiled with OGG support (this must be a parameter defined in Makefile as it is disabled by default) but in either case, there is nothing for me to fix and you would be better reporting this to Open Emu repository.

**Comment by romulof** [comment]
The "#" character is not the problem, since WAV files plays perfectly and I've tried without them.

I just came here to see if it was something with my CUE file. It's probably not being compiled with ogg.

Thanks.
