### ISSUE TITLE
[libretro] Cannot use Mouse as Paddle Control on SMS/Mark 3 games

### ISSUE THREAD

**Issue by davidj1987** [ekeeke/Genesis-Plus-GX#53]
I doubt I am missing something but for the life of me when I enable paddle control I cannot get this working with a mouse - testing on latest nightly Windows x64 build of Retroarch and core via buildbot. I haven't tried Sports Paddle games so I can't confirm or deny.

**Comment by ekeeke** [comment]
The paddle in libretro port uses the retropad analog stick (x-axis) because it's an analog input device.

I am not sure if the PC mouse can be used as a libretro analog input device in retroarch but if not, this should be handled by the frontend, not the core, as the latter is not supposed to know what kind of input device you are using, at least, that's the "philosophy" of retropad abstraction as I understand it.
