### ISSUE TITLE
Faster Sega CD Playback on GameCube?

### ISSUE THREAD

**Issue by GK6475** [ekeeke/Genesis-Plus-GX#534]
Sega CD games that use audio streaming are quite slow on the GameCube and have frequent stutters. Is this something that can be improved?

**Comment by ekeeke** [comment]
Using faster SD card can help. It has been years since I tried the gamecube version (I am not even sure if my modded gamecube still boots homebrew) but I don't remember any particular slowdown or stutters when playing CD games from SD Gekko adapter with SDHC card.

If you are using latest builds from this repository, try switching to older builds which maybe are more optimized (but with less accurate emulation).

**Comment by GK6475** [comment]
Well, I did try loading games from a GC-Loader (files on a DVD ISO) with an SD card that is pretty fast but it didn't seem to do much good. I guess I'll try some older builds and see how that goes. The game I'm testing with is Sonic CD.

**Comment by GK6475** [comment]
I did try using a fast SD card and older versions of GPGX, but it still ran slow whenever redbook CD audio played. It runs perfectly whenever CD audio is not being used, but lags whenever it is. In Sonic CD, the past stages run perfectly, but present and future stages are laggy. The past stages use MIDI and the present/future stages use CD audio tracks, so it seems to be an issue with audio streaming. Will there be any fixes for this?
