### ISSUE TITLE
Commit "[Core/CD] added CD-AUDIO & CD+G support" issue

### ISSUE THREAD

**Issue by DavidKnight247** [ekeeke/Genesis-Plus-GX#54]
When testing this commit I noticed a buzzing noise in the intro fmv on Mortal Kombat (USA) (SCD). It went away when I reverted to the previous version of core/cd_hw/cdd.c. Unfortunately given the size of the changes in this file I have not been able to figure out why this is happening yet. 

I have no other SCD roms to test. MD and SMS roms sound fine as you would expect.

I'm testing on my most recent GCW0 console build so it may be an issue on my side.

**Comment by ekeeke** [comment]
A continuous noise or a brief one ? If so, where exactly and with which BIOS version because I cannot hear anything wrong on my side ?. The intro does not use CD-DA (audio CD) track btw but PCM sound chip for which nothing was changed.

It might be an issue with the CUE file you are using, this commit (despite the size of changes) should have no impact on CD emulation but is mainly focused on the CUE file parsing side and is a little bit more restrictive than in previous versions.

**Comment by DavidKnight247** [comment]
It was a continuous noise only when playing fmv or cd-quality audio. I tried removing the .cue file, no change. I then tried recompiling with libtremor instead of libvorbis. The problem went away! I then recompiled with libvorbis and the problem appears to have gone. 

So it looks like it was a compile time problem my side, probably because I didn't "make clean" first.
