### ISSUE TITLE
set rom default rom path

### ISSUE THREAD

**Issue by grandosegood** [ekeeke/Genesis-Plus-GX#543]
hi all, would it be possible to include a menu option for setting default rom path, so it will always check that path on startup? thanks.

**Comment by ekeeke** [comment]
I assume you are talking about Retroarch so you will need to ask this to Retroarch devs as this is something handled by the frontend, not the core

On Gamecube/Wii port, the latest directory where ROM was loaded from is saved and used as default, there is no plan to make it configurable.

**Comment by BenMcLean** [comment]
> On Gamecube/Wii port, the latest directory where ROM was loaded from is saved and used as default, there is no plan to make it configurable.

Just want to say how completely stupid that is. What if you've never loaded a ROM from this program before? What if (thank God) Genesis-Plus-GX isn't the only emulator using the ROMs on your device? It needs to be configurable, at least by means of a text file if you don't want to make GUI for it, but really, it should be capable of simply navigating whatever storage libogc can detect, because the library does provide that for you.

**Comment by BenMcLean** [comment]
What's happening for me is that I am using a GC Loader and trying to store the ROMs on its micro SD card. When I start this program, all of the options for loading ROMs say, "Unable to open directory. Press A to continue" and that's all. No way to navigate anywhere else. No way to set any starting directory the program can actually open. No way to fix it. So I get online and look for issues and this is the only one I find that seems related and its marked "wontfix". Maybe I overreacted but still, this seems like a really nasty bug.

**Comment by ekeeke** [comment]
>Would you accept a PR for this if I was to fix it myself?

Sure, pull requests are always welcomed and usually get merged if i can make sense of them and they do not break existing codebase.

**Comment by ekeeke** [comment]
>The GC Loader is supported without any additional work. However, many people are using exFAT, and your build is using libfat.

Oh, nice to know, so it should work straightly with standard libfat + libogc2 if you use FAT32 formattted sdcard ? i did not really followed gamecube/wii homebrew development news these last years and haven't really looked in libogc2 changes but i always thought we also needed to update libfat's disc.c to add support for new devices ?

**Comment by Extrems** [comment]
> I guess that it can be handy when you start using a single SD card in GC Loader with your gamecube isos along with emulator roms but it's also easy to use a separated SD card formatted to FAT32 for homebrew emulators.

Well, you're the only one that chose to use libfat. dborth and emukidid are using libdvm.

**Comment by BenMcLean** [comment]
I got it working. Apparently, the lack of exFAT support was the problem, but even still, it would be nice if the program would at least say what the problem was in that case.

I managed to get Genesis-Plus-GX working by reformatting my SD card as FAT32 using [fat32format / GuiFormat by Ridgecorp Consultants](http://ridgecrop.co.uk/index.htm?guiformat.htm).
