### ISSUE TITLE
Wii u gamepad support and channel forwarder

### ISSUE THREAD

**Issue by AVissies** [ekeeke/Genesis-Plus-GX#552]
Hi, i would just like to know, does Genesis Plus GX have gamepad support on wii u and if so is there a channel forwarder for genesis plus gx for the wii u?

**Comment by ekeeke** [comment]
WiiU controller is supported by the Wii version since many years and, although I never tested it myself as I don't have a WiiU, it was reported to work fine by others. It is using code from Fix94 (who developped WiiDRC library) copied from other GX emulators with WiiU controller support.

As for channel forwarder, I don't provide one myself as I have no use for it but I know there are several ones done by other people when the Wii scene was active. No idea if there are differences between Wii and WiiU forwarder channels but I am sure you can find what you need on usual Wii hacking websites or forums.
