### ISSUE TITLE
(Libretro) wrong core name version.

### ISSUE THREAD

**Issue by KamiLordus** [ekeeke/Genesis-Plus-GX#556]
@ekeeke can you change the name of the version of the Genesis Plus Gx core for libretro retroarch ?
The correct version name is 1.7.5, the one displayed in retroarch is 1.7.4. 
The retroarch core version is upstream compatible, so this creates unnecessary confusion.

![Zrzut ekranu 2024-05-03 160801](https://github.com/ekeeke/Genesis-Plus-GX/assets/123302593/7224464f-5981-464c-99b6-2be5f5a33598)

**Comment by ekeeke** [comment]
1.7.5 was never officially released, that is the reason why version is still 1.7.4 so "correct" version is subjective in my opinoon

When libretro core was first created, libretro devs choosed to pick the latest official version number as core version number  even if it was based on latest github commits at this time, so  way beyond last official version. This is still the case now, first number is latest official version and second number is GIT version.

They could have anticipated the next version and bump version as soon as a commit is made after the latest release but I think this cause more confusion than current situation as:
- it makes people think new version was officially released upstream when it is not the case
- it assumes the next official version is going to be 1.7.5 (for example) when I could (probably) bump directly to 1.8.0 because of the amount of changes since latest official release

In the end, I don't think it matters much, what matters is that the core version is properly identified so that people can report which one they are using when reporting bugs or checking if they have the latest github build.

**Comment by KamiLordus** [comment]
Sorry, I was suggesting that this was a mistake when porting Genesis Plus GX to the libretro platform.
https://github.com/ekeeke/Genesis-Plus-GX/commit/f9f16d7a552c5606caea52c2179ca2831b8e0177
Thanks for the clarification.
