### ISSUE TITLE
Feature Request: Eliminate region lock-ups option

### ISSUE THREAD

**Issue by eugene-s-nesdev** [ekeeke/Genesis-Plus-GX#558]
Hello, ekeeke!

I have a Mega Drive 2 PAL "Asia" region + Everdrive X5 (megakey emulation enabled),
so these hardware can run almost any NTSC games at 50FPS regardless ROM header info.

I've tried to replicate same behavior using Raspberry Pi3 (+Lakka/RetroPie)
forced to RCA PAL mode via composite-out to work on real PAL CRT TV. 
I've set GenesisPlusGX system region forced to "PAL" also, for perfect synchro/no tearing.

It works very good, but there is a problem:
- GenesisPlusGX core can run most of games only if it's header region is (E), (UE) or (W),
but get lock-up on startup if it's header region is (U) or (J).

I need to fix NTSC ROM-headers manually to (E) using MegaDriveRomAnalyzer tool,
and most of them work very good after this "fix".
Another "crutch" solution is:  to start any NTSC ROM in correct mode, then change 
GenesisPlusGx system region to PAL on-the-fly every time.

Is it possible to add an option that eliminates header region-check at startup for no lock-ups?
There are many of good NTSC games that haven't been released for the PAL region.

**Comment by ekeeke** [comment]
Region lockup is implemented by each game software, not hardware so the only thing the emulator can do is emulating different region hardware so that I/O version register returns expected region code when read by game (which is also what megakey or similar products do, by intercepting reads to this register and forcing read value). This is what the region setting does but indeed, by default, this also sets the default VDP mode (50Hz or 60Hz)

Now, I am not sure why you absolutely want to run NTSC games at 50 Hz as there are zero benefits (and most likely only downsides) doing this but there is already a way to do this in emulator through core settings, although not exposed in retroarch/libretro port I think (if that is what you are using). The solution is to set:
- config.region_detect to 0 (AUTO) to prevent region lockout in most games
- config.vdp_mode to 2 to force VDP in 50Hz mode (0 by default is AUTO, 1 is 60Hz)

You will need to ask libretro devs for adding a VDP mode setting in libretro port as I don't maintain it myself (it is implemented in the Wii/Gamecube port if code reference is needed)

**Comment by eugene-s-nesdev** [comment]
Libretro devs have added this feature.
It works like a charm. 
Thank you for the information!

**Comment by eugene-s-nesdev** [comment]
@ekeeke,
Libretro and BizHawk devs have added this feature. It works very good. Thank you for the information!
Can you merge this commit (https://github.com/libretro/Genesis-Plus-GX/commit/ba9fc37cfa4930311a9c77b1d8a23df0cae95e9a) to the your libretro branch (https://github.com/ekeeke/Genesis-Plus-GX/tree/master/libretro) please?

**Comment by ekeeke** [comment]
I don't know how I can merge commits from a fork repository but if you (or someone else) submit a pull request in this repository with these changes, I will merge it.

**Comment by eugene-s-nesdev** [comment]
PR is here: https://github.com/ekeeke/Genesis-Plus-GX/pull/565

**Comment by eugene-s-nesdev** [comment]
@ekeeke ,
PR is here: https://github.com/ekeeke/Genesis-Plus-GX/pull/565

Thank you!
