### ISSUE TITLE
Snapshots

### ISSUE THREAD

**Issue by camilitox** [ekeeke/Genesis-Plus-GX#59]
the program does not show snapshots of the image set no-intro (Excuse me for my bad English
![3 ninjas kick back usa](https://cloud.githubusercontent.com/assets/14097392/9640019/8a45426c-5185-11e5-8e0e-8d96b250bbcf.png)
![sonic the hedgehog usa europe](https://cloud.githubusercontent.com/assets/14097392/9640025/98a582b8-5185-11e5-89a7-a0ecbdf542f0.png)

)

**Comment by ekeeke** [comment]
Not sure what you are doing or using but pictures should be:
1) in PNG format
2) named like the loaded file (exemple: Sonic.zip -> Sonic.png)
3) stored in /genplus/snaps/md directory (for Megadrive/Genesis games) on your default storage device (SD if present, USB otherwise)

The emulator can itself make a snapshot and store it in appropriate place if you use the snapshot button in main menu.

All these things are explained in the included User Manual.
