### ISSUE TITLE
USB joypad

### ISSUE THREAD

**Issue by camilitox** [ekeeke/Genesis-Plus-GX#61]
Will be possible use a USB joypad, as you can with nintendont?

**Comment by ekeeke** [comment]
This will need a USB HID driver first and I have no idea how to write one or how difficult this is. Not saying it won't ever happen but it's very unlikely and really not a priority considering the available controller options are enough (for me at least).

If you want to use original controllers, you can buy on of these adapters (i have both and they work fine, with a preference for the wiimote extension solution since it's more practical than having controllers hooked to the console):

http://www.brunofreitas.com/?q=node/40
http://www.raphnet-tech.com/products/genesis_to_wii/index.php


There is also this one (untested):
http://www.raphnet-tech.com/products/genesis_to_wiimote/index.php

**Comment by ekeeke** [comment]
Duplicated into #321
