### ISSUE TITLE
HD tile replacement 

### ISSUE THREAD

**Issue by ADormant** [ekeeke/Genesis-Plus-GX#62]
Would be possible to implement this interesting feature in Genesis Plus GX?
https://github.com/shonumi/gbe-plus/tree/master/src/common
https://github.com/mkwong98/HDNes

![hd tiles](https://cloud.githubusercontent.com/assets/10523326/10639644/ab29c644-7811-11e5-8e05-cbc2abde50d0.jpg)

**Comment by ekeeke** [comment]
Might be possible although never done with Mega Drive emulation but that would likely require rewriting a lot of the emulator rendering process, making it less accurate and it's really not something I am interested in.

**Comment by ADormant** [comment]
@ekeeke The method used in GBE+ does not have any influence on accuracy. This method shouldn't affect anything about how accurate emulation is. All GBE+ is doing is drawing different pixels to a buffer. The internal stuff (timings, interrupts, memory accesses) aren't touched at all, so it only affects final screen output. To put it another way, the buffer really has no way to change if the rest of emulation is accurate. Instead of drawing the original pixels, it's swapped with custom ones when applicable

**Comment by ekeeke** [comment]
I don't really care, it would still need to process graphics on a tile basis instead of line / pixel granularity like done actually so it's less accurate to me and still require to break the way the emulator is actually rendering planes/sprites/tiles/pixels.

It also seems it requires pre-making your own HD tiles for each games specifically and that's not something I'm interested in doing (or even using).

I personally like the way older pixel design looked better and feel this HD feature is just some hyped gimmick that only a few people will care about, maybe experiment with it a little to have some fun or show off to their friends then drop out once they realize nobody is making complete tilesets for more games and that it doesn't make those games any "better" ;-)

**Comment by ADormant** [comment]
> It also seems it requires pre-making your own HD tiles for each games specifically and that's not something I'm interested in doing (or even using) since it seems a very painful thing to do, especially with systems such as Mega Drive where games can use a huge amount of tiles, modify them on the fly, etc.

Well it's best to leave making custom tiles to end-users if Genesis-Plus-GX will ever get such feature I don't expect  you making them yourself.


Perhaps @shonumi can explain in more detail how it works, if it breaks anything and if special effects are doable.

> I don't really care, it still requires to break the way the emulator is actually fetching pixels from tiles in VRAM memory and require to increase the number of rendered lines.


> Similarly, for games that do tricky effects by changing stuff mid-line or on a line basis, those fixed HD tiles wouldn't do any good.

**Comment by ekeeke** [comment]
I am not sure why you keep insisting, I already said I was not interested in modifying the emulator to support this and I really don't need to be lectured how it is done on different systems, I think I understand quite well how this works and what would be the limitations (at least for tile-based systems and Genesis in particular).

Another thing you don't seem to understand (since you keep quoting or linking random emulator projects as if it was some key piece of information to get things started) is that each emulated hardware is different, i.e Genesis does not work the same as GBA, etc... so the way it is done on other emulated systems is quite (if not completely) irrelevant.

**Comment by shonumi** [comment]
I'm not going to say much, but I'll just touch upon the method I came up with. Basically, an emulator just hashes any tile it comes across in VRAM, stores it in a list, then continually matches this hash to a separate list of hashes pointing to graphical replacements. It's essentially the 2D version of custom textures in Dolphin or PJ64/Mupen64Plus. That's glossing over a lot of details, but that's the gist of it.

Supporting this feature requires substantial hooks into the emulated video code, "deep hooks" as byuu has called it. It's not something that I would casually add on. If you don't have the framework for it, this feature can become very invasive very quickly. And by far, the biggest factor is maintaining GUI code to extract the tiles.

Personally, I don't thing people should be bothered to replicate what I've done. Every emu-dev should follow whatever course he/she wants. I don't push my method on others, but I don't turn away questions. I'd actually rather have people wait until I can finish publishing my findings (there are a lot of challenges to getting it working just right).

About system complexity, in theory, this method should work on most 2D tile based consoles. Fancy stuff, even the scaling/rotation and alpha-blending on the GBA will work. I can't speak about the Genesis. What I do know won't work are some things that aren't tiles at all (Super Metroid's power bomb, other HDMA effects on the SNES and GBA, and bitmap modes). Performance is also currently an area of struggle.

The theory behind my work isn't set, and it'll evolve later. But anyway, I'm not the pushy type. Let's let this project follow its own course.

**Comment by ADormant** [comment]
@shonumi how HDMA effects work scaline manipulation?
