### ISSUE TITLE
Support for Genesis ROM > 10MB

### ISSUE THREAD

**Issue by TheRetroSnake** [ekeeke/Genesis-Plus-GX#67]
I was forwarded here from Bizhawk repo, so I'll just paste what I said there; "So, I noticed while testing with Bizhawk, that you can not load ROM image > 10MB. While this is much better than most emulators (cough only supports 6MB cough), this is still incorrect when SSFII mapper is in use. In fact, while using it, up to 32MB ROM's should work just fine, as it is the hard limit of said mapper, according to HW information we have, and this document http://emu-docs.org/Genesis/ssf2.txt
I would like the emulator to have support for ROMs > 10MB in size. It would likely to be logical to load first 4 or 8 MB to ROM section, and then rely on the source program to map different portions of the ROM to different banks.
One other issue in Bizhawk is that it expects the SSFII header to enable swapping, else it would not work (at least according to my tests) which should really not be the case. Also have a ROM which is 32MB and will print each bank after another. http://natsumi.noip.me/d/misc/a.zip/ "

**Comment by CaptainHIT** [comment]
use retroarch

2015-12-07 13:42 GMT+02:00 Natsumi <notifications@github.com>:

> I was forwarded here from Bizhawk repo, so I'll just paste what I said
> there; "So, I noticed while testing with Bizhawk, that you can not load ROM
> image > 10MB. While this is much better than most emulators (cough only
> supports 6MB cough), this is still incorrect when SSFII mapper is in use.
> In fact, while using it, up to 32MB ROM's should work just fine, as it is
> the hard limit of said mapper, according to HW information we have, and
> this document http://emu-docs.org/Genesis/ssf2.txt
> I would like the emulator to have support for ROMs > 10MB in size. It
> would likely to be logical to load first 4 or 8 MB to ROM section, and then
> rely on the source program to map different portions of the ROM to
> different banks.
> One other issue in Bizhawk is that it expects the SSFII header to enable
> swapping, else it would not work (at least according to my tests) which
> should really not be the case. Also have a ROM which is 32MB and will print
> each bank after another. http://natsumi.noip.me/d/misc/a.zip/ "
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ekeeke/Genesis-Plus-GX/issues/67>.
>



-- 
Captain HIT

**Comment by ekeeke** [comment]
This emulator was originally made for Gamecube then Wii (and it's still the only platform I personally use it for), which has limited RAM, hence this limitation for loaded ROM size. Also, at that time, nobody made a ROM files bigger than 10 MB  and the only game using SSF2 mapper was only 5MB so supporting more was really unneeded. 

Support for bigger ROM (and theoretical maximal range of SSF2 mapper that again, NO existing cartridge can handle either) could easily be implemented but this is very low priority to me atm.

That does not prevent anyone interested by your 32MB demo to submit a patch into this repository, though, so I leave this open for further discussions.

As for needing SSF2 header to activate mapper, again, I can not support what does not exist or what is unknown to exist. You will always need something to identify the cartridge hardware mapper being used by the loaded game and an usused field in an existing header is still better than a fixed game database with CRC listing. Note that you are not forced to use SSF2 game name in ROM header: the emulator partially supports Krikzz extended SSF mapper and will enable it if "SEGA GENESIS" string in header is replaced by "SEGA SSF"...

https://www.dropbox.com/sh/fdt8185a8kpjozb/AAAmFuHi6oV5D9llk068twpRa/mega-everdrive/v2/dev/extended_ssf-v2.txt?dl=0

**Comment by TheRetroSnake** [comment]
Could it at least be changed to something more harmless, say the Serial number, or the title that is not displayed, so custom ROM name can be defined (mind I am unsure of how the implementation works specifically, it could already do either one). Also as far as your other concerns, it is completely understandable. Also speaking of MAXROMSIZE.h, this would force me to compile the emulator just in support of this feature? If so, could it be a switch in .ini file or equivalent, mostly for user conviniency and the fact that I never really work with c myself so compiling it would be pain (as I've tried before and it never quite worked). Either way I appreciate the answer

**Comment by ekeeke** [comment]
Replacing "GENESIS" or "MEGA DRIVE" by "SSF" in console name field is harmless and it's how it is implemented on the only flashcart that supports SSF2 mapper for any games other than SSF2. Serial number is game specific so it's really not a good idea to use it for a generic mapper.

As for the value in loadrom.h, it cannot be put in an .ini file because by default the ROM buffer is statically allocated (i.e buffer size is fixed) for portability reason. It's possible to enable dynamic ROM buffer allocation through a compiling option though so the right way to do it would be to make the allocated size correspond to the loaded ROM file size but like I explained, this is very low priority to me and I personally have no plan to spend time changing this atm.

However, since you mentionned you were using bizhawk and I think this only runs on PC, this minimal change of MAXROMSIZE value in loadrom.h could actually be made directly by bizhawk devs with no harm or risk to run out of memory. I know they already made bizhawk specific changes to the emulator code and it does not seem like they are going to submit their changes back here anyway.

**Comment by TheRetroSnake** [comment]
ok, I will link then here and let them decide what to do about it. Thanks again.

**Comment by zeromus** [comment]
Thanks for looking into this, ekeeke.  Sorry we don't submit back our changes, but I think you don't want most of them. If you wish, I'll analyze the changelog and look for ones you might like.

**Comment by ekeeke** [comment]
No problem, I figure that most changes are related to TAS but I am always interested in knowing specific issues that people may have encountered while porting the emulator. As for end users bug reports, they generally end up here anyway.

**Comment by ekeeke** [comment]
Since it's very platform-specific, I made the maximal ROM size configurable through compiler define option in https://github.com/ekeeke/Genesis-Plus-GX/commit/0b27a42d2fc2def7057b604f12e56ec7603c8ab5

To allow  support for up to 32MB ROM files in a specific port, you now only need to add -DMAXROMSIZE=33554432 compiler flag in your Makefile.
