### ISSUE TITLE
Higher color depth 

### ISSUE THREAD

**Issue by ADormant** [ekeeke/Genesis-Plus-GX#79]
Higher color depth woild be nice since Megadrive had limited number of colors.
Something like this:
https://github.com/simias/rustation-libretro/commit/3db9e1bbf65baf75166139d136789d18bf65dbfe
https://github.com/simias/rustation-libretro/commit/595ba82463d200b208d4d6be27c446cfe3c179d5
https://github.com/simias/rustation-libretro/commit/518f17ce6c0ce7847db75f7d8f5840d89137c033
https://github.com/simias/rustation/commit/b3e7626c5ce52c1587ff511bf74013ba4fa88558
https://github.com/libretro/beetle-psx-libretro/commit/5ed95bbdf2d7c349476de6d01356124c2e9edeb7
https://github.com/simias/rustation-libretro/commit/9178efe4bfa50777f5b5f253ada9af4fe7cc02e8
https://github.com/libretro/beetle-psx-libretro/pull/29/files
https://sourceforge.net/p/desmume/code/5395/

**Comment by andlabs** [comment]
I don't quite understand what all of those do, and the vague phrase "color depth" could mean anything. Can you go into detail?

**Comment by ekeeke** [comment]
Not sure either what those commits are supposed to do but from the comments, it appears to be related to increasing the native framebuffer pixel depth. I don't get how dithering would increase the number of color though, as the games obviously still pick from a limited palette choice.

 It's not possible on Mega Drive anyway since it does not have a framebuffer or a modern GPU like PS1 or NDS and we already dither the original 9-bit color to 15-bit, 16-bit or 24-bit depending on what the platform supports.

**Comment by ADormant** [comment]
@ekeeke Sorry I mean something like the option in these emulators
GBE+ and I think VBAM and Gambette have this option.

https://github.com/visualboyadvance-m/visualboyadvance-m
https://github.com/shonumi/gbe-plus
https://github.com/libretro/gambatte-libretro

Check GBE+ in particular. Real GBA could only use 15 bit RGB color palette but GBE+ can use 24bit( 24bit or 24bit+8 bit alpha I'm not sure) true color to make colors much more vivid even without replacement tiles. Tomorrow GBE+ should have a campiled stable release.

**Comment by ekeeke** [comment]
As already explained, 9-bit color is already upscaled (or dithered) to 15-bit, 16-bit or 24-bit color equivalent but it's not possible make the color more "vivid" (whatever that means) or increase the number of available colors, because :

1) color depth is determined by the number of bits of data words written in color RAM 
=> palettes are game-specific i.e they are programmed by games themselves by writing words to color RAM so the depth (i.e number of distinct colors) cannot be changed without hacking each games specifically

2) number of color available for the game is fixed by the color RAM size (it's 64 x 9-bit which makes 4 pallettes of 16 colors each)
=> again, this is programmed by the game so this is not possible to hack around without hacking each game specifically
 
On a side note, I really don't see the point in posting walls of links to random projects or commits without explaining or pointing out exactly what you are referring to. I'm sorry but it's still not clear what you are exactly talking about , how converting xx-bit pixel to 24-bit exactly "make the system more colorful" and how whatever is done to these 32-bit consoles which are using texture & framebuffer based GPUs could be applied to Mega Drive / Genesis...

**Comment by ADormant** [comment]
Perhaps @shonumi can elaborate how GBE+ can make it more ''colorful''?

**Comment by shonumi** [comment]
@Adormant - The GBC, GBA, and NDS all have 15-bit color palettes. Each RGB channel is represented by 5 bits. To convert this to 24-bit (8-bits per channel) all I really do is multiply those 5 bits to simulate what their 8-bit version would look like. It's cheap and gets the job done. It's not super accurate, but your eyes usually don't complain about any perceived differences between the emulated colors and the real colors.

The GBC and GBA are special cases; until the AGS-101 really, on-screen colors looked "washed" out due to the way Nintendo built their screens. Most emulators ignore this because 1) it's harder to do properly and 2) it doesn't affect gameplay and is a matter of taste. So washing out the colors is usually an optional feature. But that has nothing to do with extending palettes, rather it has everything to do with emulating different screen technologies and their "looks".

I have to agree with the others here. It's not really applicable or possible to extend the palettes. Converting from xx-bit color to 24-bit color still limits you to the same amount of colors present in xx-bits.

**Comment by ADormant** [comment]
> To convert this to 24-bit (8-bits per channel) all I really do is multiply those 5 bits to simulate what their 8-bit version would look like. It's cheap and gets the job done.
@ekeeke  Is something like that doable for Genesis? Or is that simply dithering?

**Comment by GerbilSoft** [comment]
That's pretty much what it already does.

Check the MAKE_PIXEL() macros at https://github.com/ekeeke/Genesis-Plus-GX/blob/master/core/vdp_render.c#L468.

The only thing that could potentially be improved is the color range. Right now, the maximum RGB value for Mode 5 is 0xEEEEEE, since the color LUT is calculated using bit shifts. A lookup table could be used instead to provide more accurate values: http://gendev.spritesmind.net/forum/viewtopic.php?f=22&t=2188

Note that there's both linear and HW-measured values. Linear might look "better" in the emulator, but the HW-measured values are what the VDP's DAC actually generates.

**Comment by ekeeke** [comment]
@ADormant : you still don't seem to understand, as already said multiple times by me and others, conversion is already done (because obviously no modern platform support Mega Drive 9-bit pixel format natively) and no, it does not magically increase the color palette or make the colors look "better". Some Mega Drive games look very colorful, while some others seem to have more limited palette, that's just the way it is and nothing is going to change that besides implementing game-specific hacks.

@GerbilSoft : yes, this is planned. But from my tests, neither expanding to full range (which isn't necessarely accurate by the way) or using non-linear steps make any really noticeable difference in games.
