### ISSUE TITLE
Pier solar save states don't load properly

### ISSUE THREAD

**Issue by FeRcHuLeS** [ekeeke/Genesis-Plus-GX#80]
I updated to the latest version and loaded a state then the game freezes, It is not the case for another mega drive, game gear or master systems games save states I tested they don't freeze at all.

**Comment by ekeeke** [comment]
I cannot reproduce your issue, saving and loading state works fine for this game on the Wii and SDL version using the latest code. 

Now, the particularity of this game is that can use Mega CD hardware: if a valid Mega CD BIOS file is found when you load it, Mega CD hardware is enabled, else only stock Mega Drive / Genesis hardware is emulated.

You can upload your state file and I will have a look but, most likely, it was initially done with Mega CD hardware disabled (no proper Mega CD BIOS configured) and you are now trying to load it with Mega CD hardware enabled... or the opposite. In both cases, this will cause crash because invalid data is being loaded to current emulated context.

**Comment by FeRcHuLeS** [comment]
You are right, the mega cd bios wasn't enabled, the state load fine now, thanks.
