### ISSUE TITLE
9365ac2 commit causes the screen width to be offset and distorted

### ISSUE THREAD

**Issue by joepogo** [ekeeke/Genesis-Plus-GX#83]
#The recent changes for commit 9365ac2 causes all games to load to a screen that is now off and somewhat huge. (the width is now distorted) If you restart the game it then goes to normal, upon reloading again it goes back to distorted again. 

Something is very off in vdp_ctrl.c or system.c, is this a regression or bug? Eke, please check and let me know i am not crazy here. haha. :) Im usually pretty good at finding bugs for you so let me know friend. :)

**Comment by ekeeke** [comment]
Are you talking about Retroarch version? That does not happen for me in Standalone version and that change has no impact on the screen width (previous commit did though)"

**Comment by ekeeke** [comment]
Tested latest core version with an old Retroarch build for win32 that I had and there was no screen issue either so I don't know what to tell you without more details on your setup (screenshots also generally help if you want to be a good bug reporter)

**Comment by joepogo** [comment]
Thanks eke, once I get off work I will try this again. This is not for the retroarch but the standalone. I will post back here once I can test it again. Thanks for the prompt response and I will include a picture as well if I recompile and have the same issue.

**Comment by ekeeke** [comment]
You don't need to recompile yourself, precompiled builds are made available here when important commits are made

https://github.com/ekeeke/Genesis-Plus-GX/blob/master/builds/genplus_wii.dol

Just click on "Raw" to download and rename the file to boot.dol or whatever file name you need for booting DOL files.

**Comment by joepogo** [comment]
I follow along and add your current code changes to the xbox port. Once I can get home ill be able to post back more info and screens if I cannot fix the problem.

**Comment by joepogo** [comment]
By the way eke, totally off topic but congratulations on 1000 commits! May you have another 10,000 in you! :)

**Comment by ekeeke** [comment]
I see, I remember know, you are the one mixing Genesis Plus GX code with Gens code in one of the Xbox port. Well, since you are manually backporting my changes, doesn't it seems more plausible to you that you possibly made a mistake while copying code rather than a bug in my code, especially something that much noticeable? 

My guess is that you missed or incorrectly copied some stuff from this commit: https://github.com/ekeeke/Genesis-Plus-GX/commit/381a9d114f057c570618c288db257b8eb2d6393c

or that you once altered the original code in system.c and/or vdp_ctrl.c to make it compatible with your port and it somehow is now broken on your side with these changes, I don't know.

Either way, those commits were tested and there is nothing wrong or off in this code.

**Comment by joepogo** [comment]
Thanks eke, yep it was an issue on my end. :)
