### ISSUE TITLE
Racer homebrew game crashing when the vertical borders are disabled 

### ISSUE THREAD

**Issue by FeRcHuLeS** [ekeeke/Genesis-Plus-GX#86]
The series of this game Racer, Racer Easter Edition and Racer Rebooted make you to lose at the begining of the race, when the vertical borders are disabled the game  was tested on real hardware as the author said:

[(http://www.smspower.org/Homebrew/Racer-SMS)]

**Comment by ekeeke** [comment]
Vertical borders are always "enabled" on real hardware so don't complain if something does not work like real hardware if you disable emulation of real-hardware feature, that'skinda expected. It's likely a bug in that homebrew, although I hardly see how border emulation could have any effect on a game engine.

**Comment by FeRcHuLeS** [comment]
That's kinda discrimination what your saying since the other master system games works fine with/without borders

**Comment by ekeeke** [comment]
It's not "discrimination", considering precisely that 
1) other games "work fine" and this bug only affects this game
2) it's an homebrew game that had similar issue with the pause button on real hardware (according to release thread on smspower)
4) it is not possible to test on real hardware with "borders disabled" ,

it was simply more logical to assume that this was a bug in the game rather than the emulator.

Anyway, after looking a bit more into this, I think I know what causes this : sprite collision on Master System can still occur during vertical borders (only a few emulators accurately handle this because no games rely on this) and therefore this emulator still process sprites during vertical borders, even if they are forced disabled (which is accurate behavior since, as already explained, borders can not be "disabled" on real hardware). The thing is, during borders, the line buffer is only cleared if borders are emulated so, a false detection of sprite collision could occur between sprites from different lines.

An optimized solution would be to disable sprite processing during borders if they are disabled, thus being less accurate than when borders are emulated, but that's expected.

**Comment by ekeeke** [comment]
fixed in https://github.com/ekeeke/Genesis-Plus-GX/commit/373b4ff214e3f66d32f05fcdc060eb5cdb5c1fa6
