### ISSUE TITLE
Some issues using the Lightguns

### ISSUE THREAD

**Issue by FeRcHuLeS** [ekeeke/Genesis-Plus-GX#87]
Lightguns - Wii
- The crosshair is stayed drawn over vertical borders as many times as it is  reached, only when the vertical borders are disabled.

Lightguns - PC
- The crosshair aims to the center of the screen when the begining of the borders are reached, besides maybe it would be better the crosshair to dissapear after it reaches the end of the borders not the begining (just like on the Wii).

**Comment by ekeeke** [comment]
1) Border area was not cleared between frames when borders are not rendered. This has been fixed in https://github.com/ekeeke/Genesis-Plus-GX/commit/949e60ee329d57a622ff0a086cc4a2e665b10a39

2) This is a limitation of retroarch, RETRO_DEVICE_POINTER returns (0,0) as coordinate if aiming outside the rendered screen, which corresponds to the center of the screen. There is nothing I can do about it, it needs to be fixed in the RETRO_DEVICE_POINTER implementations of Retroarch PC input drivers.

**Comment by FeRcHuLeS** [comment]
So the PC aiming issue is a Retroarch issue then I'm going to post it to the Retroarch's, and about the Wii's everything is working perfect now, thanks.

**Comment by nobody37** [comment]
Shouldn't these lines in libretro.c (330 & 331) reflect RETRO_DEVICE_LIGHTGUN and its respective RETRO_DEVICE_ID_LIGHTGUN_X and RETRO_DEVICE_ID_LIGHTGUN_Y coordinates respectively instead of using RETRO_DEVICE_POINTER?

https://github.com/ekeeke/Genesis-Plus-GX/blob/master/libretro/libretro.c#L330&L331

I understand that a lightgun is a pointing device, from a hardware standpoint that makes sense, but shouldn't it be up to RetroArch to define what is and isn't a lightgun? That architecturally makes more sense, and besides mixing hardware paradigms like lightgun for the buttons and pointer for the cursor is messy. 

When trying to play Missile Defense 3-D I can shoot at the middle of the screen and see the cursor with my relative coordinate mouse, but there's no movement (actually, there IS movement, if I make a LOT of movement at once for a continuous period, because RetroArch is passing on relative coords anyway as absolute coords).

Technically a gamepad cursor could theoretically be a lightgun cursor (see "The Adventures of Bayou Billy - Game Mode B" on the NES), pretty much anything with a USB HID Report Descriptor of Input(Data,Var,Abs) could be used. It's better to leave that configuration up to the RetroArch side and not worry about it. If people want to change it at the RetroArch level to allow relative coordinate devices behave like absolute coordinate devices (by keeping coordinate relative to some fixed absolute coordinate i.e. (0,0)), then that should be fine.

**Comment by ekeeke** [comment]
This was already explained elsewhere but it's not that the core is "defining what a lightgun is" but the fact RETRO_DEVICE_LIGHTGUN in libretro actually returns relative coordinates (cursor movement) while lightgun emulation requires absolute coordinates (screen position).

Therefore it makes much sense using RETRO_DEVICE_POINTER since the core has no way to know where the initial cursor position  (which returned coordinates are relative to)  was unless it forces it itself to an arbitrary position (which might be incorrect depending on the device used to simulate lightgun). The only rule is that the frontend (retroarch) should comply to the core if this one respects the libretro API.
