### ISSUE TITLE
Error with pausing music in the Sega CD in MODE1.

### ISSUE THREAD

**Issue by Tippek** [ekeeke/Genesis-Plus-GX#92]
When music playback is paused, then after some time the music stops ("stop" command). When the pause is removed, the music does not play.

**Comment by ekeeke** [comment]
With which game and where exactly? In CD player menu?

**Comment by Tippek** [comment]
Yes, mode1, used two roms for this(for correct results) - cd player(genesis rom) and btdd hack with mode1. In cdd.c , cdd_procces() got case 0x01 when game is paused, looks like a music didn't really stopped and music still playing until end.

**Comment by ekeeke** [comment]
I guess those are homebrew roms, where can I find them?

Also, were they tested on a real Sega CD to make sure it's not simply a bug
in the roms? The emulator won't execute a STOP (0x01) command unless the
game actually sends this command itself.

Also, I didn't understand last sentence: audio is stopped or keep playing
when being paused? What you wrote is not clear.

**Comment by Tippek** [comment]
I can send rom when I will home (~ 4 hours later). Audio is stopped when pausing, I mean this looks like music timer not stopped and running until track's end.

**Comment by ekeeke** [comment]
There is no music timer in emulator/hardware, the hardware (and emulator) only responds to CDD command sent by software (through BIOS function calls) so music playback is fully controlled by software.

**Comment by Tippek** [comment]
I will send a rom later for check.

**Comment by Tippek** [comment]
We tested three bioses, and same result. There is player with mode1:
http://www.sega-16.com/forum/showthread.php?19657-SEGA-CD-Mode-1&p=432757&viewfull=1#post432757

**Comment by ekeeke** [comment]
upd? What does that mean?
I will test this CD player when I got some time but please PRECISELY describe the EXACT steps to reproduce your issue because it's still not very clear from your posts what you are doing, what you are expecting and what is happening instead.

Also, did someone tested this behavior on other emulator (or better on real hardware with an everdrive that I know let you boot Sega CD from flashcart rom)? You could also ask Chilly Willy since it seems you are reusing its code in your hack, it's possible there is a bug in its code like a timeout that will reinit drive  after a while when a track is paused, which indeed sends a stop command. If the time counter is not increasing and audio playback is muted after you pressed the PAUSE key (z button apparently from the links you posted, so make sure you have a 6-button pad emulated and correctly configured), it means the track is correctly paused and does not continue to advance in emulator. 

In the mean time, you can test pause/resume behavior with official CD player (the one that appears if you boot Sega CD in normal mode with an audio cd), that's what I mean by testing in any bios, not testing your hack or Chilly Willy's CD player with different bios.

**Comment by ekeeke** [comment]
Just tested Chilly Willy's CD Player and it indeed automatically switches from "PAUSED" to "STOPPED" after some time but, as I said, this is caused by CD Player software sending an "STOP" (0x00) command after a while. Same thing happens in Kega Fusion so this is likely a bug or an undocumented feature in CD Player code, as expected.
