### ISSUE TITLE
Six-Buttons controller support

### ISSUE THREAD

**Issue by fixx1983** [ekeeke/Genesis-Plus-GX#94]
Please add 6 button controller support. Some games, like Comix Zone, shown that a 6 buttons pad is connected, but we can't bind the buttons X-Y-Z

**Comment by ekeeke** [comment]
6-button controller is emulated so I'm not sure what you are talking about?

If you are speaking about a specific port of this emulator, you should probably mention which one you are referring to because there are many ones. I only maintain the Wii/Gamecube and libretro ports so if you are using another one, you will have to ask the port maintainer to expose 6-button option in his frontend.
